import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BookOpen,
  CircleDollarSign,
  Database,
  Gauge,
  MessageCircle,
  Workflow,
  Zap,
} from 'lucide-react';
import { useEffect, useState } from 'react';

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import {
  DateRangeFilter,
  type DateRangeFilterValue,
} from '@/components/ui/date-range-filter';
import { Skeleton } from '@/components/ui/skeleton';

import { analyticsApi } from '../../api';
import type {
  AnalyticsByGraphResponseDto,
  AnalyticsByGraphResponseDtoGraphsInner,
  AnalyticsOverviewDto,
} from '../../autogenerated';
import { useCurrentProject } from '../../hooks/useCurrentProject';
import { extractApiErrorMessage } from '../../utils/errors';

const TOKEN_COLORS = {
  threads: '#d4915e',
  totalTokens: '#e8a676',
  cost: '#b87d52',
  input: '#8a6947',
  output: '#c99167',
  cached: '#b87d52',
  reasoning: '#8a6947',
} as const;

const formatNumber = (num?: number | null): string => {
  if (typeof num !== 'number' || !Number.isFinite(num)) return '\u2014';
  return new Intl.NumberFormat('en-US').format(num);
};

const formatCompact = (num?: number | null): string => {
  if (typeof num !== 'number' || !Number.isFinite(num)) return '\u2014';
  if (num < 10_000) return new Intl.NumberFormat('en-US').format(num);
  return new Intl.NumberFormat('en-US', {
    notation: 'compact',
    maximumFractionDigits: 1,
  }).format(num);
};

const formatUsd = (amount?: number | null): string => {
  if (typeof amount !== 'number' || !Number.isFinite(amount)) return '$\u2014';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 4,
    maximumFractionDigits: 4,
  }).format(amount);
};

const StatCard = ({
  label,
  value,
  icon: iconComponent,
  color,
}: {
  label: string;
  value: string;
  icon: React.ComponentType<{
    className?: string;
    style?: React.CSSProperties;
  }>;
  color: string;
}) => {
  const IconEl = iconComponent;
  return (
    <Card className="p-3 gap-2">
      <div className="text-xs text-muted-foreground mb-2">{label}</div>
      <div className="flex items-center gap-1.5">
        <IconEl className="w-5 h-5" style={{ color }} />
        <span className="text-xl font-semibold" style={{ color }}>
          {value}
        </span>
      </div>
    </Card>
  );
};

const AnalyticsGraphCard = ({
  graph,
}: {
  graph: AnalyticsByGraphResponseDtoGraphsInner;
}) => (
  <Card className="p-3 gap-1">
    <div className="flex items-center justify-between mb-1.5">
      <div className="flex items-center gap-2">
        <Workflow className="w-4 h-4" style={{ color: TOKEN_COLORS.threads }} />
        <span className="text-sm font-medium text-foreground">
          {graph.graphName}
        </span>
      </div>
      <Badge className="px-2 py-0.5 bg-[#b87d52]/10 text-[#b87d52] border-transparent rounded text-xs font-medium hover:bg-[#b87d52]/10">
        {formatUsd(graph.totalPrice)}
      </Badge>
    </div>
    <div className="grid grid-cols-4 gap-2">
      <div className="min-w-0">
        <div className="text-[11px] text-muted-foreground">Threads</div>
        <div className="flex items-center gap-1 min-w-0">
          <MessageCircle className="w-3 h-3 flex-shrink-0 text-[#d4915e]" />
          <span className="text-sm font-semibold text-[#d4915e] truncate">
            {formatCompact(graph.totalThreads)}
          </span>
        </div>
      </div>
      <div className="min-w-0">
        <div className="text-[11px] text-muted-foreground">Total Tokens</div>
        <div className="flex items-center gap-1 min-w-0">
          <Zap className="w-3 h-3 flex-shrink-0 text-[#e8a676]" />
          <span className="text-sm font-semibold text-[#e8a676] truncate">
            {formatCompact(graph.totalTokens)}
          </span>
        </div>
      </div>
      <div className="min-w-0">
        <div className="text-[11px] text-muted-foreground">Input</div>
        <div className="text-sm font-semibold text-[#8a6947] truncate">
          {formatCompact(graph.inputTokens)}
        </div>
      </div>
      <div className="min-w-0">
        <div className="text-[11px] text-muted-foreground">Output</div>
        <div className="text-sm font-semibold text-[#c99167] truncate">
          {formatCompact(graph.outputTokens)}
        </div>
      </div>
    </div>
  </Card>
);

const isEmptyOverview = (overview: AnalyticsOverviewDto): boolean =>
  overview.totalThreads === 0 &&
  overview.totalTokens === 0 &&
  overview.totalPrice === 0;

export const MainPage = () => {
  const { currentProject } = useCurrentProject();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [overview, setOverview] = useState<AnalyticsOverviewDto | null>(null);
  const [byGraph, setByGraph] = useState<AnalyticsByGraphResponseDto | null>(
    null,
  );
  const [dateFilter, setDateFilter] = useState<DateRangeFilterValue>({
    dateFrom: undefined,
    dateTo: undefined,
  });

  useEffect(() => {
    let mounted = true;
    setLoading(true);
    (async () => {
      try {
        const [overviewRes, byGraphRes] = await Promise.all([
          analyticsApi.getOverview(dateFilter.dateFrom, dateFilter.dateTo),
          analyticsApi.getByGraph(dateFilter.dateFrom, dateFilter.dateTo),
        ]);
        if (!mounted) return;
        setOverview(overviewRes.data);
        setByGraph(byGraphRes.data);
      } catch (e) {
        if (!mounted) return;
        console.error('Error fetching analytics:', e);
        const errorMessage = extractApiErrorMessage(
          e,
          'Failed to load analytics',
        );
        setError(errorMessage);
      } finally {
        if (mounted) setLoading(false);
      }
    })();
    return () => {
      mounted = false;
    };
  }, [dateFilter]);

  if (loading) {
    return (
      <div className="p-6">
        <div className="mb-8">
          <Skeleton className="h-8 w-48 mb-2" />
          <Skeleton className="h-5 w-80" />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-20 rounded-xl" />
          ))}
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
          <Skeleton className="h-20 rounded-xl" />
        </div>
        <Skeleton className="h-6 w-40 mb-4" />
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-24 rounded-xl" />
          ))}
        </div>
      </div>
    );
  }

  const hasGraphData = byGraph && byGraph.graphs.length > 0;
  const showEmptyState =
    !error && overview && isEmptyOverview(overview) && !hasGraphData;

  return (
    <div className="p-6">
      <div className="mb-8">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 mb-2">
            <Gauge className="w-6 h-6 text-foreground" />
            <h1 className="text-foreground">Dashboard</h1>
          </div>
          <DateRangeFilter value={dateFilter} onChange={setDateFilter} />
        </div>
        {currentProject && (
          <p className="text-muted-foreground">{currentProject.name}</p>
        )}
        {!currentProject && (
          <p className="text-muted-foreground">
            Analytics overview for your agent graphs.
          </p>
        )}
      </div>

      {error && (
        <Alert variant="destructive" className="mb-6">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>Failed to load analytics</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {showEmptyState && (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <BookOpen className="w-12 h-12 text-muted-foreground/30 mb-4" />
          <p className="text-sm text-muted-foreground">
            No analytics data yet. Run some agent graphs to see usage statistics
            here.
          </p>
        </div>
      )}

      {overview && !showEmptyState && (
        <>
          {/* Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
            <StatCard
              label="Total Threads"
              value={formatNumber(overview.totalThreads)}
              icon={MessageCircle}
              color={TOKEN_COLORS.threads}
            />
            <StatCard
              label="Total Tokens"
              value={formatNumber(overview.totalTokens)}
              icon={Zap}
              color={TOKEN_COLORS.totalTokens}
            />
            <StatCard
              label="Total Cost"
              value={formatUsd(overview.totalPrice)}
              icon={CircleDollarSign}
              color={TOKEN_COLORS.cost}
            />
            <StatCard
              label="Input Tokens"
              value={formatNumber(overview.inputTokens)}
              icon={ArrowRight}
              color={TOKEN_COLORS.input}
            />
          </div>

          {/* Output Tokens + conditional cards */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-4">
            <StatCard
              label="Output Tokens"
              value={formatNumber(overview.outputTokens)}
              icon={ArrowLeft}
              color={TOKEN_COLORS.output}
            />
            {overview.cachedInputTokens > 0 && (
              <StatCard
                label="Cached Input"
                value={formatNumber(overview.cachedInputTokens)}
                icon={Database}
                color={TOKEN_COLORS.cached}
              />
            )}
            {overview.reasoningTokens > 0 && (
              <StatCard
                label="Reasoning Tokens"
                value={formatNumber(overview.reasoningTokens)}
                icon={BookOpen}
                color={TOKEN_COLORS.reasoning}
              />
            )}
          </div>
        </>
      )}

      {hasGraphData && (
        <>
          <div className="flex items-center gap-2 mb-4">
            <div className="w-1 h-4 bg-foreground" />
            <h2 className="text-lg font-medium text-foreground">
              Usage by Graph
            </h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-3">
            {byGraph.graphs.map((graph) => (
              <AnalyticsGraphCard graph={graph} key={graph.graphId} />
            ))}
          </div>
        </>
      )}
    </div>
  );
};
