import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useState,
} from 'react';

import { projectsApi } from '../api';
import type { ProjectDto } from '../autogenerated';

const STORAGE_KEY = 'geniro:last-project-id';
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function readStoredProjectId(): string | null {
  try {
    const val = localStorage.getItem(STORAGE_KEY);
    return val && UUID_RE.test(val) ? val : null;
  } catch {
    // Private browsing or storage disabled
    return null;
  }
}

function writeStoredProjectId(id: string | null): void {
  try {
    if (id) {
      localStorage.setItem(STORAGE_KEY, id);
    } else {
      localStorage.removeItem(STORAGE_KEY);
    }
  } catch {
    // Private browsing or storage disabled
  }
}

interface ProjectContextValue {
  projects: ProjectDto[];
  loading: boolean;
  loadProjects: () => Promise<void>;
  currentProjectId: string | null;
  setCurrentProjectId: (id: string | null) => void;
}

export const ProjectContext = createContext<ProjectContextValue>({
  projects: [],
  loading: false,
  loadProjects: async () => {},
  currentProjectId: null,
  setCurrentProjectId: () => {},
});

export const ProjectProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [projects, setProjects] = useState<ProjectDto[]>([]);
  const [loading, setLoading] = useState(false);
  const [currentProjectId, setCurrentProjectIdState] = useState<string | null>(
    () => readStoredProjectId(),
  );

  const setCurrentProjectId = useCallback((id: string | null) => {
    setCurrentProjectIdState(id);
    writeStoredProjectId(id);
  }, []);

  const loadProjects = useCallback(async () => {
    setLoading(true);
    try {
      const res = await projectsApi.getAllProjects();
      setProjects(res.data);
    } catch (err) {
      // Ignore on load failure — show empty state
      console.error('[ProjectContext] Failed to load projects:', err);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadProjects();
  }, [loadProjects]);

  // Validate stored project ID against loaded projects
  useEffect(() => {
    if (loading || projects.length === 0) return;
    if (currentProjectId && !projects.some((p) => p.id === currentProjectId)) {
      setCurrentProjectId(null);
    }
  }, [projects, loading, currentProjectId, setCurrentProjectId]);

  return (
    <ProjectContext.Provider
      value={{
        projects,
        loading,
        loadProjects,
        currentProjectId,
        setCurrentProjectId,
      }}>
      {children}
    </ProjectContext.Provider>
  );
};

export const useProjectContext = () => useContext(ProjectContext);
