import '@uiw/react-md-editor/markdown-editor.css';

import MDEditor from '@uiw/react-md-editor';
import { Sparkles } from 'lucide-react';
import { X } from 'lucide-react';
import { useState } from 'react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

import type { KnowledgeDocDto } from '../../../autogenerated';

export type KnowledgeFormValues = {
  title: string;
  tags?: string[];
  politic?: string;
};

type KnowledgeEditorModalProps = {
  open: boolean;
  activeDoc: KnowledgeDocDto | null;
  saving: boolean;
  form: {
    getFieldsValue: () => KnowledgeFormValues;
    setFieldsValue: (values: Partial<KnowledgeFormValues>) => void;
    validateFields: () => Promise<KnowledgeFormValues>;
    resetFields: () => void;
  };
  editorValue: string;
  onEditorChange: (nextValue: string) => void;
  tagOptions: string[];
  onCancel: () => void;
  onSubmit: () => void;
  onOpenAiSuggestion: () => void;
  aiActionLabel: string;
};

const ALWAYS_FETCH_FULL_CONTENT =
  'If this document is relevant to the current task - always fetch the full content instead of fetching only specific chunks.';

function TagsInput({
  tags,
  onChange,
  suggestions,
}: {
  tags: string[];
  onChange: (tags: string[]) => void;
  suggestions: string[];
}) {
  const [input, setInput] = useState('');

  const addTag = (raw: string) => {
    const parts = raw
      .split(',')
      .map((t) => t.trim())
      .filter(Boolean);
    onChange([...new Set([...tags, ...parts])]);
    setInput('');
  };

  const removeTag = (tag: string) => onChange(tags.filter((t) => t !== tag));

  return (
    <div className="border border-border rounded-md px-3 py-2 flex flex-wrap gap-1.5 min-h-[38px] focus-within:ring-1 focus-within:ring-ring cursor-text">
      {tags.map((tag) => (
        <Badge
          key={tag}
          variant="secondary"
          className="gap-1 px-2 py-0.5 text-xs">
          {tag}
          <button
            type="button"
            onClick={() => removeTag(tag)}
            className="ml-0.5 hover:text-destructive transition-colors">
            <X className="w-3 h-3" />
          </button>
        </Badge>
      ))}
      <input
        className="flex-1 min-w-[140px] text-sm outline-none bg-transparent placeholder:text-muted-foreground"
        placeholder={
          tags.length === 0 ? 'Add tag, press Enter or comma' : 'Add more...'
        }
        value={input}
        onChange={(e) => setInput(e.target.value)}
        list="tag-suggestions"
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ',') {
            e.preventDefault();
            if (input.trim()) addTag(input);
          }
          if (e.key === 'Backspace' && !input && tags.length) {
            removeTag(tags[tags.length - 1]);
          }
        }}
        onBlur={() => {
          if (input.trim()) addTag(input);
        }}
      />
      <datalist id="tag-suggestions">
        {suggestions
          .filter((s) => !tags.includes(s))
          .map((s) => (
            <option key={s} value={s} />
          ))}
      </datalist>
    </div>
  );
}

export const KnowledgeEditorModal = ({
  open,
  activeDoc,
  saving,
  form,
  editorValue,
  onEditorChange,
  tagOptions,
  onCancel,
  onSubmit,
  onOpenAiSuggestion,
  aiActionLabel,
}: KnowledgeEditorModalProps) => {
  const values = form.getFieldsValue();

  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onCancel()}>
      <DialogContent className="sm:max-w-[900px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>
            {activeDoc ? 'Edit knowledge' : 'Create knowledge'}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-2">
          <div className="space-y-2">
            <Label>
              <span className="text-destructive mr-0.5">*</span>Title
            </Label>
            <Input
              value={values.title || ''}
              onChange={(e) => form.setFieldsValue({ title: e.target.value })}
              placeholder="Knowledge title"
            />
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <Label>LLM Guidance (Politic)</Label>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                className="text-xs h-6 px-2 text-muted-foreground hover:text-foreground"
                onClick={() =>
                  form.setFieldsValue({ politic: ALWAYS_FETCH_FULL_CONTENT })
                }>
                Always fetch full content
              </Button>
            </div>
            <Textarea
              value={values.politic || ''}
              onChange={(e) => form.setFieldsValue({ politic: e.target.value })}
              placeholder="Add LLM guidance"
              className="min-h-[72px] resize-none text-sm"
            />
            <p className="text-xs text-muted-foreground">
              Notes for the LLM explaining when and what it should fetch from
              this document.
            </p>
          </div>

          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <Label>Content</Label>
              <Button
                type="button"
                variant="link"
                size="sm"
                className="p-0 h-auto text-xs"
                onClick={onOpenAiSuggestion}>
                {aiActionLabel}
              </Button>
            </div>
            <div data-color-mode="light">
              <MDEditor
                value={editorValue}
                onChange={(value) => onEditorChange(value || '')}
                height={320}
                preview="live"
              />
            </div>
          </div>

          <div className="space-y-2">
            <Label>Tags</Label>
            <TagsInput
              tags={values.tags || []}
              onChange={(tags) => form.setFieldsValue({ tags })}
              suggestions={tagOptions}
            />
          </div>
        </div>

        <DialogFooter className="flex items-center justify-between sm:justify-between gap-2 mt-2">
          <Button
            variant="outline"
            className="gap-2"
            onClick={onOpenAiSuggestion}>
            <Sparkles className="w-4 h-4" />
            {aiActionLabel}
          </Button>
          <div className="flex gap-2">
            <Button variant="outline" onClick={onCancel}>
              Cancel
            </Button>
            <Button onClick={onSubmit} disabled={saving}>
              {activeDoc ? 'Save' : 'Create'}
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
