import { Loader2 } from 'lucide-react';
import React, { useMemo } from 'react';

import type { GraphDto } from '../../../autogenerated';
import { Badge } from '../../../components/ui/badge';
import { GRAPH_STATUS_META } from '../utils/chatsPageUtils';

interface GraphPickerContentProps {
  graphs: GraphDto[];
  loading: boolean;
  error: string | null;
  onSelect: (graphId: string) => void;
}

export const GraphPickerContent: React.FC<GraphPickerContentProps> = React.memo(
  ({ graphs, loading, error, onSelect }) => {
    const content = useMemo(() => {
      if (loading) {
        return (
          <div className="p-3 text-center">
            <Loader2 className="h-4 w-4 animate-spin mx-auto text-muted-foreground" />
          </div>
        );
      }
      if (error) {
        return <span className="text-xs text-muted-foreground">{error}</span>;
      }
      if (graphs.length === 0) {
        return (
          <span className="text-xs text-muted-foreground">
            No graphs available
          </span>
        );
      }
      return (
        <div className="max-h-[300px] overflow-y-auto min-w-[260px] flex flex-col gap-1">
          {graphs.map((graph) => (
            <button
              key={graph.id}
              type="button"
              className="text-left px-3 py-2 h-auto leading-tight flex flex-col items-start border border-border rounded-md w-full hover:bg-muted/50 transition-colors"
              onClick={() => onSelect(graph.id)}>
              <div className="flex items-center gap-1.5 w-full">
                <span className="font-medium text-xs leading-tight">
                  {graph.name && graph.name.trim().length > 0
                    ? graph.name
                    : `Graph ${graph.id.slice(-6)}`}
                </span>
                <Badge
                  variant="outline"
                  className="text-[9px] leading-none px-1.5 py-0 rounded-full"
                  style={{
                    borderColor:
                      GRAPH_STATUS_META[graph.status]?.color ?? '#d9d9d9',
                    color: GRAPH_STATUS_META[graph.status]?.color ?? '#d9d9d9',
                  }}>
                  {GRAPH_STATUS_META[graph.status]?.label ?? graph.status}
                </Badge>
              </div>
              <span className="text-[10px] text-muted-foreground mt-0.5">
                v{graph.version}
                {graph.createdAt && (
                  <>
                    {' \u00b7 '}
                    {new Date(graph.createdAt).toLocaleDateString()}
                  </>
                )}
              </span>
            </button>
          ))}
        </div>
      );
    }, [error, graphs, loading, onSelect]);

    return content;
  },
);

GraphPickerContent.displayName = 'GraphPickerContent';
