import { formatDistanceToNow } from 'date-fns';
import { Clock, Loader2, RefreshCw, X } from 'lucide-react';

import type { RuntimeInstanceDto } from '../../../autogenerated';
import { RuntimeInstanceDtoStatusEnum } from '../../../autogenerated';
import { Badge } from '../../../components/ui/badge';
import { Button } from '../../../components/ui/button';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '../../../components/ui/tooltip';

const STATUS_BADGE_VARIANT: Record<
  RuntimeInstanceDtoStatusEnum,
  { className: string }
> = {
  Starting: { className: 'border-blue-400 text-blue-600' },
  Running: { className: 'border-green-500 text-green-600' },
  Stopping: { className: 'border-orange-400 text-orange-600' },
  Stopped: { className: 'border-border text-muted-foreground' },
  Failed: { className: 'border-red-400 text-red-600' },
};

interface ThreadRuntimeSidebarProps {
  open: boolean;
  onClose: () => void;
  runtimes: RuntimeInstanceDto[];
  loading: boolean;
  error: string | null;
  onRefresh: () => void;
  nodeDisplayNames?: Record<string, string>;
  nodeAgentNames?: Record<string, string>;
}

export const ThreadRuntimeSidebar = ({
  open,
  onClose,
  runtimes,
  loading,
  error,
  onRefresh,
  nodeDisplayNames,
  nodeAgentNames,
}: ThreadRuntimeSidebarProps) => {
  if (!open) return null;

  const showLoading = loading && runtimes.length === 0;

  return (
    <div className="w-72 shrink-0 border-l border-border flex flex-col bg-background overflow-hidden">
      {/* Header */}
      <div className="px-4 py-4 border-b border-border flex justify-between items-center shrink-0">
        <h3 className="text-base font-semibold">Runtimes</h3>
        <div className="flex items-center gap-1">
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={onRefresh}
                disabled={loading}>
                {loading ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" />
                ) : (
                  <RefreshCw className="h-3.5 w-3.5" />
                )}
              </Button>
            </TooltipTrigger>
            <TooltipContent>Refresh runtimes</TooltipContent>
          </Tooltip>
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={onClose}>
                <X className="h-3.5 w-3.5" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>Close</TooltipContent>
          </Tooltip>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 min-h-0 overflow-y-auto py-1">
        {showLoading && (
          <div className="flex justify-center items-center pt-12">
            <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
          </div>
        )}

        {error && !showLoading && (
          <p className="text-sm text-destructive mb-3">{error}</p>
        )}

        {!showLoading && runtimes.length === 0 && !error && (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <p className="text-sm text-muted-foreground">
              No runtimes for this thread
            </p>
          </div>
        )}

        {runtimes.map((runtime) => (
          <RuntimeCard
            key={runtime.id}
            runtime={runtime}
            nodeName={nodeDisplayNames?.[runtime.nodeId]}
            agentName={nodeAgentNames?.[runtime.nodeId]}
          />
        ))}
      </div>
    </div>
  );
};

const ACTIVE_THRESHOLD_MS = 30_000;

function formatIdleLabel(
  lastUsedAt: string,
  status: RuntimeInstanceDtoStatusEnum,
): string {
  if (status === RuntimeInstanceDtoStatusEnum.Starting) return 'Starting...';
  if (status === RuntimeInstanceDtoStatusEnum.Stopping) return 'Stopping...';

  const date = new Date(lastUsedAt);
  if (isNaN(date.getTime())) return 'Unknown';

  if (status === RuntimeInstanceDtoStatusEnum.Running) {
    const idleMs = Date.now() - date.getTime();
    if (idleMs < ACTIVE_THRESHOLD_MS) return 'Active now';
  }
  return `Idle for ${formatDistanceToNow(date)}`;
}

const RuntimeCard = ({
  runtime,
  nodeName,
  agentName,
}: {
  runtime: RuntimeInstanceDto;
  nodeName?: string;
  agentName?: string;
}) => {
  const badgeStyle =
    STATUS_BADGE_VARIANT[runtime.status] ?? STATUS_BADGE_VARIANT.Stopped;
  const displayName = nodeName ?? runtime.nodeId;

  const createdDate = new Date(runtime.createdAt);
  const createdLabel = isNaN(createdDate.getTime())
    ? '—'
    : formatDistanceToNow(createdDate, { addSuffix: true });

  const isInactive =
    runtime.status === RuntimeInstanceDtoStatusEnum.Stopped ||
    runtime.status === RuntimeInstanceDtoStatusEnum.Failed;

  return (
    <div className="mx-2 my-1.5 px-3 py-2.5 rounded-lg border border-border bg-card hover:bg-muted/40 transition-colors">
      {/* Header: name + status badge */}
      <div className="flex justify-between items-center mb-2">
        <span className="font-mono text-xs font-medium text-foreground truncate mr-2">
          {displayName}
        </span>
        <Badge variant="outline" className={`shrink-0 ${badgeStyle.className}`}>
          {runtime.status}
        </Badge>
      </div>

      {/* Metadata 2-col grid */}
      <div className="grid grid-cols-[auto_1fr] gap-x-3 gap-y-0.5 items-baseline">
        {agentName && (
          <>
            <span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground/60 leading-4">
              Agent
            </span>
            <span
              className="text-xs text-foreground truncate"
              title={agentName}>
              {agentName}
            </span>
          </>
        )}
        <span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground/60 leading-4">
          Type
        </span>
        <span className="text-xs text-foreground">{runtime.type}</span>
        {runtime.containerName && (
          <>
            <span className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground/60 leading-4">
              Ctr
            </span>
            <span
              className="text-xs text-foreground font-mono truncate"
              title={runtime.containerName}>
              {runtime.containerName}
            </span>
          </>
        )}
      </div>

      {/* Lifecycle row — visually separated */}
      <div className="mt-1.5 pt-1.5 border-t border-dashed border-border/50 flex items-center gap-1.5">
        <Clock className="h-3 w-3 text-muted-foreground/50 shrink-0" />
        <span className="text-[11px] text-muted-foreground truncate">
          {createdLabel}
        </span>
        <span className="text-muted-foreground/40 text-[11px]">·</span>
        <span
          className={`text-[11px] shrink-0 ${
            isInactive ? 'text-muted-foreground/60' : 'text-muted-foreground'
          }`}>
          {formatIdleLabel(runtime.lastUsedAt, runtime.status)}
        </span>
      </div>
    </div>
  );
};
