import { AlertTriangle, BarChart3, FileText, Network } from 'lucide-react';
import { type FC, useState } from 'react';

import type {
  ThreadDto,
  ThreadMessageDto,
  ThreadUsageStatisticsDto,
} from '../../../autogenerated';
import { Alert, AlertDescription } from '../../../components/ui/alert';
import { Button } from '../../../components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../../../components/ui/dialog';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '../../../components/ui/tooltip';
import ThreadMessagesView from '../../graphs/components/ThreadMessagesView';
import { ThreadUsageDisplay } from '../../graphs/components/ThreadUsageDisplay';
import { SnapshotGraphView } from './SnapshotGraphView';

/**
 * Locally-defined shape for thread export data.
 * The backend returns this from GET /threads/:id/export, but the OpenAPI spec
 * does not emit a schema for it, so we define the type here.
 */
export interface ThreadExportData {
  version: '1';
  exportedAt: string;
  isRunning: boolean;
  thread: ThreadDto;
  messages: ThreadMessageDto[];
  usageStatistics: ThreadUsageStatisticsDto;
  graph: {
    id: string;
    name: string;
    description?: string | null;
    nodes: {
      id: string;
      template: string;
      config: Record<string, unknown>;
    }[];
    edges?: { from: string; to: string; label?: string }[];
  } | null;
}

interface ThreadSnapshotModalProps {
  open: boolean;
  onClose: () => void;
  snapshot: ThreadExportData | null;
}

export const ThreadSnapshotModal: FC<ThreadSnapshotModalProps> = ({
  open,
  onClose,
  snapshot,
}) => {
  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
      {snapshot && (
        <ThreadSnapshotModalContent snapshot={snapshot} onClose={onClose} />
      )}
    </Dialog>
  );
};

interface ContentProps {
  snapshot: ThreadExportData;
  onClose: () => void;
}

const ThreadSnapshotModalContent: FC<ContentProps> = ({
  snapshot,
  onClose,
}) => {
  const [usageStatsOpen, setUsageStatsOpen] = useState(false);
  const [graphDetailsOpen, setGraphDetailsOpen] = useState(false);

  const nodeDisplayNames = buildNodeDisplayNames(snapshot);

  const exportDate = isValidDate(snapshot.exportedAt)
    ? new Date(snapshot.exportedAt).toLocaleString()
    : snapshot.exportedAt;

  return (
    <>
      <DialogContent
        className="sm:max-w-4xl h-[85vh] flex flex-col overflow-hidden"
        onOpenAutoFocus={(e) => e.preventDefault()}>
        <DialogHeader className="flex-shrink-0">
          <div className="flex items-center justify-between gap-2 min-w-0 pr-8">
            <DialogTitle className="flex items-center gap-2 min-w-0 flex-1">
              <FileText className="size-4 shrink-0" />
              <span className="truncate">
                Thread Snapshot — {snapshot.thread.name ?? 'Unnamed Thread'}
              </span>
            </DialogTitle>
            <div className="flex items-center gap-1 flex-shrink-0">
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-7 w-7"
                    onClick={() => setUsageStatsOpen(true)}>
                    <BarChart3 className="h-4 w-4" />
                  </Button>
                </TooltipTrigger>
                <TooltipContent side="bottom">
                  View usage statistics
                </TooltipContent>
              </Tooltip>
              {snapshot.graph && (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="ghost"
                      size="icon"
                      className="h-7 w-7"
                      onClick={() => setGraphDetailsOpen(true)}>
                      <Network className="h-4 w-4" />
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent side="bottom">
                    View graph configuration
                  </TooltipContent>
                </Tooltip>
              )}
            </div>
          </div>
          <p className="text-xs text-muted-foreground">Exported {exportDate}</p>
        </DialogHeader>

        {snapshot.isRunning && (
          <Alert className="border-amber-200 bg-amber-50 text-amber-800 flex-shrink-0 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-200">
            <AlertTriangle className="size-4 text-amber-600" />
            <AlertDescription className="text-amber-700">
              This snapshot was taken while the thread was still running. The
              messages and statistics may be incomplete.
            </AlertDescription>
          </Alert>
        )}

        {snapshot.messages.length === 0 ? (
          <div className="flex-1 py-10 flex flex-col items-center justify-center text-center text-muted-foreground">
            <FileText className="w-10 h-10 mb-3 opacity-30" />
            <p className="text-sm font-medium">
              No messages in this thread snapshot
            </p>
          </div>
        ) : (
          <div className="flex-1 min-h-0 relative">
            <div className="absolute inset-0 overflow-hidden">
              <ThreadMessagesView
                messages={snapshot.messages}
                messagesLoading={false}
                selectedThreadId={snapshot.thread.id}
                isThreadStopped={true}
                nodeDisplayNames={nodeDisplayNames}
                showNodeHeadings={true}
              />
            </div>
          </div>
        )}

        <DialogFooter className="flex-shrink-0">
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>

      {/* Usage Statistics sub-dialog */}
      <Dialog open={usageStatsOpen} onOpenChange={setUsageStatsOpen}>
        <DialogContent className="sm:max-w-4xl max-h-[80vh] flex flex-col overflow-hidden">
          <DialogHeader className="flex-shrink-0">
            <DialogTitle className="flex items-center gap-2">
              <BarChart3 className="size-4" />
              Usage Statistics
            </DialogTitle>
          </DialogHeader>
          <div className="flex-1 min-h-0 overflow-y-auto">
            <ThreadUsageDisplay
              usage={snapshot.usageStatistics}
              loading={false}
              error={null}
              nodeDisplayNames={nodeDisplayNames}
            />
          </div>
          <DialogFooter className="flex-shrink-0">
            <Button variant="outline" onClick={() => setUsageStatsOpen(false)}>
              Close
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Graph details sub-dialog */}
      {snapshot.graph && (
        <Dialog open={graphDetailsOpen} onOpenChange={setGraphDetailsOpen}>
          <DialogContent className="sm:max-w-4xl h-[75vh] flex flex-col overflow-hidden">
            <DialogHeader className="flex-shrink-0">
              <DialogTitle className="flex items-center gap-2">
                <Network className="size-4" />
                <span className="truncate">{snapshot.graph.name}</span>
              </DialogTitle>
              {snapshot.graph.description && (
                <p className="text-xs text-muted-foreground">
                  {snapshot.graph.description}
                </p>
              )}
            </DialogHeader>
            <div className="flex-1 min-h-0 rounded-md overflow-hidden border border-border">
              <SnapshotGraphView
                graph={snapshot.graph}
                nodeDisplayNames={nodeDisplayNames}
              />
            </div>
            <DialogFooter className="flex-shrink-0">
              <Button
                variant="outline"
                onClick={() => setGraphDetailsOpen(false)}>
                Close
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      )}
    </>
  );
};

function buildNodeDisplayNames(
  snapshot: ThreadExportData,
): Record<string, string> {
  const names: Record<string, string> = {};

  if (snapshot.graph) {
    for (const node of snapshot.graph.nodes) {
      const configName: unknown = node.config?.name;
      if (typeof configName === 'string' && configName.trim()) {
        names[node.id] = configName.trim();
      } else {
        names[node.id] = node.id;
      }
    }
  }

  // Overlay agent names from thread.agents (richer display names)
  const agents = snapshot.thread.agents;
  if (agents) {
    for (const agent of agents) {
      if (agent.name.trim()) {
        names[agent.nodeId] = agent.name.trim();
      } else if (!names[agent.nodeId]) {
        names[agent.nodeId] = agent.nodeId;
      }
    }
  }

  // When graph is null, build from agents only
  if (!snapshot.graph && agents) {
    for (const agent of agents) {
      names[agent.nodeId] = agent.name.trim() || agent.nodeId;
    }
  }

  return names;
}

function isValidDate(str: string): boolean {
  const d = new Date(str);
  return !isNaN(d.getTime());
}
