import { CloseOutlined, ReloadOutlined } from '@ant-design/icons';
import { Button, Empty, Space, Spin, Tag, Tooltip, Typography } from 'antd';

import type {
  RuntimeInstanceDto,
  RuntimeInstanceDtoStatusEnum,
} from '../../../autogenerated';

const { Text, Title } = Typography;

const STATUS_TAG_COLOR: Record<RuntimeInstanceDtoStatusEnum, string> = {
  Starting: 'blue',
  Running: 'green',
  Stopping: 'orange',
  Stopped: 'default',
  Failed: 'red',
};

interface ThreadRuntimeSidebarProps {
  open: boolean;
  onClose: () => void;
  runtimes: RuntimeInstanceDto[];
  loading: boolean;
  error: string | null;
  onRefresh: () => void;
  nodeDisplayNames?: Record<string, string>;
  nodeAgentNames?: Record<string, string>;
}

export const ThreadRuntimeSidebar = ({
  open,
  onClose,
  runtimes,
  loading,
  error,
  onRefresh,
  nodeDisplayNames,
  nodeAgentNames,
}: ThreadRuntimeSidebarProps) => {
  if (!open) return null;

  const showLoading = loading && runtimes.length === 0;

  return (
    <div
      style={{
        width: 360,
        flexShrink: 0,
        borderLeft: '1px solid #f0f0f0',
        display: 'flex',
        flexDirection: 'column',
        background: '#fff',
        overflow: 'hidden',
      }}>
      {/* Header */}
      <div
        style={{
          padding: '16px',
          borderBottom: '1px solid #f0f0f0',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          flexShrink: 0,
        }}>
        <Title level={5} style={{ margin: 0 }}>
          Runtimes
        </Title>
        <Space size={4}>
          <Tooltip title="Refresh runtimes">
            <Button
              type="text"
              size="small"
              icon={<ReloadOutlined />}
              onClick={onRefresh}
              loading={loading}
            />
          </Tooltip>
          <Tooltip title="Close">
            <Button
              type="text"
              size="small"
              icon={<CloseOutlined />}
              onClick={onClose}
            />
          </Tooltip>
        </Space>
      </div>

      {/* Content */}
      <div
        style={{
          flex: 1,
          minHeight: 0,
          overflowY: 'auto',
          padding: '12px 16px',
        }}>
        {showLoading && (
          <div
            style={{
              display: 'flex',
              justifyContent: 'center',
              alignItems: 'center',
              paddingTop: 48,
            }}>
            <Spin />
          </div>
        )}

        {error && !showLoading && (
          <Text type="danger" style={{ display: 'block', marginBottom: 12 }}>
            {error}
          </Text>
        )}

        {!showLoading && runtimes.length === 0 && !error && (
          <Empty
            description="No runtimes for this thread"
            image={Empty.PRESENTED_IMAGE_SIMPLE}
          />
        )}

        {runtimes.map((runtime) => (
          <RuntimeCard
            key={runtime.id}
            runtime={runtime}
            nodeName={nodeDisplayNames?.[runtime.nodeId]}
            agentName={nodeAgentNames?.[runtime.nodeId]}
          />
        ))}
      </div>
    </div>
  );
};

const RuntimeCard = ({
  runtime,
  nodeName,
  agentName,
}: {
  runtime: RuntimeInstanceDto;
  nodeName?: string;
  agentName?: string;
}) => {
  const tagColor = STATUS_TAG_COLOR[runtime.status] ?? 'default';
  const displayName = nodeName ?? runtime.nodeId;

  return (
    <div
      style={{
        padding: '12px',
        marginBottom: 8,
        border: '1px solid #f0f0f0',
        borderRadius: 8,
        background: '#fafafa',
      }}>
      <div
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: 6,
        }}>
        <Text strong>{displayName}</Text>
        <Tag color={tagColor}>{runtime.status}</Tag>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
        {agentName && (
          <Text type="secondary" style={{ fontSize: 12 }}>
            Agent: {agentName}
          </Text>
        )}
        <Text type="secondary" style={{ fontSize: 12 }}>
          Type: {runtime.type}
        </Text>
        {runtime.containerName && (
          <Text
            type="secondary"
            style={{ fontSize: 12 }}
            ellipsis={{ tooltip: runtime.containerName }}>
            Container: {runtime.containerName}
          </Text>
        )}
      </div>
    </div>
  );
};
