import type { FC } from 'react';

import type {
  TemplateDto,
  ThreadDto,
  ThreadUsageStatisticsDto,
} from '../../../autogenerated';
import { Button } from '../../../components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../../../components/ui/dialog';
import { ThreadUsageDisplay } from '../../graphs/components/ThreadUsageDisplay';
import type { GraphCacheEntry } from '../types';

interface UsageStatsModalProps {
  open: boolean;
  onClose: () => void;
  threadId: string | null;
  threads: ThreadDto[];
  graphCache: Record<string, GraphCacheEntry>;
  templatesById: Record<string, TemplateDto>;
  threadUsageStats: Record<string, ThreadUsageStatisticsDto>;
  threadUsageStatsLoading: Record<string, boolean>;
  socketEventsCount: number;
  onShowLocalEvents: (threadId: string) => void;
}

export const UsageStatsModal: FC<UsageStatsModalProps> = ({
  open,
  onClose,
  threadId,
  threads,
  graphCache,
  templatesById,
  threadUsageStats,
  threadUsageStatsLoading,
  socketEventsCount,
  onShowLocalEvents,
}) => {
  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <DialogContent className="sm:max-w-[800px]">
        <DialogHeader>
          <DialogTitle>Thread Usage Statistics</DialogTitle>
        </DialogHeader>
        {threadId &&
          (() => {
            const thread = threads.find((t) => t.id === threadId);
            if (!thread) return null;

            const graph = graphCache[thread.graphId]?.graph;

            const nodeNames: Record<string, string> = {};
            const nodeKinds: Record<string, string> = {};

            if (graph?.schema?.nodes) {
              graph.schema.nodes.forEach((node) => {
                const configName = node.config?.name as string | undefined;
                if (
                  configName &&
                  typeof configName === 'string' &&
                  configName.trim()
                ) {
                  nodeNames[node.id] = configName.trim();
                }

                const template = templatesById[node.template];
                if (template?.kind) {
                  nodeKinds[node.id] = template.kind;
                }
              });
            }

            return (
              <ThreadUsageDisplay
                usage={threadUsageStats[threadId] || null}
                loading={threadUsageStatsLoading[threadId] || false}
                error={null}
                nodeDisplayNames={nodeNames}
                nodeKinds={nodeKinds}
                localEventsCount={socketEventsCount}
                onShowLocalEvents={() => onShowLocalEvents(thread.id)}
              />
            );
          })()}
        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
