import { BarChart3 } from 'lucide-react';
import type { FC } from 'react';

import type {
  ThreadDto,
  ThreadUsageStatisticsDto,
} from '../../../autogenerated';
import { Button } from '../../../components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../../../components/ui/dialog';
import { ThreadUsageDisplay } from '../../graphs/components/ThreadUsageDisplay';
import type { GraphCacheEntry } from '../types';

interface UsageStatsModalProps {
  open: boolean;
  onClose: () => void;
  threadId: string | null;
  threads: ThreadDto[];
  graphCache: Record<string, GraphCacheEntry>;
  getFullGraph: (
    graphId: string,
  ) => import('../../../autogenerated').GraphDto | undefined;
  threadUsageStats: Record<string, ThreadUsageStatisticsDto>;
  threadUsageStatsLoading: Record<string, boolean>;
  socketEventsCount: number;
  onShowLocalEvents: (threadId: string) => void;
}

export const UsageStatsModal: FC<UsageStatsModalProps> = ({
  open,
  onClose,
  threadId,
  threads,
  graphCache,
  getFullGraph,
  threadUsageStats,
  threadUsageStatsLoading,
  socketEventsCount,
  onShowLocalEvents,
}) => {
  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && onClose()}>
      <DialogContent className="sm:max-w-5xl max-h-[85vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <BarChart3 className="size-4" />
            Thread Usage Statistics
          </DialogTitle>
        </DialogHeader>
        {threadId &&
          (() => {
            const thread = threads.find((t) => t.id === threadId);
            if (!thread) return null;

            const entry = graphCache[thread.graphId];
            const graph = entry?.graph;

            const nodeNames: Record<string, string> = {};
            const nodeKinds: Record<string, string> = {};

            // Prefer full schema for complete node kind and name coverage
            const fullGraph = getFullGraph(thread.graphId);
            if (fullGraph?.schema) {
              for (const node of fullGraph.schema.nodes) {
                const configName: unknown = node.config?.name;
                if (typeof configName === 'string' && configName.trim()) {
                  nodeNames[node.id] = configName.trim();
                }
                nodeKinds[node.id] = node.template.replace(
                  /-([a-z])/g,
                  (_, c: string) => c.toUpperCase(),
                );
              }
            } else if (graph) {
              // Fallback: use preview data
              const displayNames = entry?.nodeDisplayNames ?? {};
              for (const [nodeId, name] of Object.entries(displayNames)) {
                nodeNames[nodeId] = name;
              }
            }

            // Always overlay agent info from preview (agents have richer name data)
            if (graph) {
              for (const agent of graph.agents ?? []) {
                if (agent.name.trim()) {
                  nodeNames[agent.nodeId] = agent.name.trim();
                }
                if (!nodeKinds[agent.nodeId]) {
                  nodeKinds[agent.nodeId] = 'simpleAgent';
                }
              }
            }

            return (
              <ThreadUsageDisplay
                usage={threadUsageStats[threadId] || null}
                loading={threadUsageStatsLoading[threadId] || false}
                error={null}
                nodeDisplayNames={nodeNames}
                nodeKinds={nodeKinds}
                localEventsCount={socketEventsCount}
                onShowLocalEvents={() => onShowLocalEvents(thread.id)}
              />
            );
          })()}
        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            Close
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
