import {
  AlertCircle,
  Loader2,
  MoreVertical,
  PlayCircle,
  Save,
  Square,
} from 'lucide-react';
import { type FC, type ReactNode } from 'react';

import { type GraphDto, type GraphRevisionDto } from '../../../autogenerated';
import { Badge } from '../../../components/ui/badge';
import { Button } from '../../../components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '../../../components/ui/dropdown-menu';
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from '../../../components/ui/hover-card';
import { PickerTrigger } from '../../../components/ui/picker-trigger';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '../../../components/ui/popover';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '../../../components/ui/tooltip';
import { REVISION_STATUS_STYLES } from '../utils/graphPageUtils';

interface GraphPageHeaderProps {
  graphName: string;

  // Revision
  graph: GraphDto | null;
  revisionPopoverVisible: boolean;
  onRevisionPopoverChange: (open: boolean) => void;
  onLoadRevisions: () => void;
  revisionPopoverContent: ReactNode;
  displayedVersion: string | number;
  displayedRevisionMeta: {
    label: string;
    color: string;
    pulse?: boolean;
  } | null;
  lastFailedRevision: GraphRevisionDto | null;

  // Error display
  graphError: string | null;

  // Save/Run actions
  saving: boolean;
  isRevisionApplying: boolean;
  hasStructuralChanges: boolean;
  unsavedChangesPopoverContent: ReactNode;
  onSave: () => void;
  isGraphRunning: boolean;
  isGraphCompiling: boolean;
  actionLoading: boolean;
  onGraphAction: () => void;

  // Menu
  graphMenuItems: {
    key: string;
    disabled?: boolean;
    label: ReactNode;
    className?: string;
    separator?: boolean;
  }[];
  onGraphMenuAction: (key: string) => void;
}

export const GraphPageHeader: FC<GraphPageHeaderProps> = ({
  graphName,

  graph,
  revisionPopoverVisible,
  onRevisionPopoverChange,
  onLoadRevisions,
  revisionPopoverContent,
  displayedVersion,
  displayedRevisionMeta,
  lastFailedRevision,

  graphError,

  saving,
  isRevisionApplying,
  hasStructuralChanges,
  unsavedChangesPopoverContent,
  onSave,
  isGraphRunning,
  isGraphCompiling,
  actionLoading,
  onGraphAction,

  graphMenuItems,
  onGraphMenuAction,
}) => {
  return (
    <header className="flex items-center justify-between px-4 py-2 border-b border-border bg-card flex-shrink-0">
      {/* Left: graph name + version/revision trigger */}
      <div className="flex items-center gap-2">
        <Popover
          open={revisionPopoverVisible}
          onOpenChange={(open) => {
            onRevisionPopoverChange(open);
            if (open) onLoadRevisions();
          }}>
          <PopoverTrigger asChild>
            <PickerTrigger>
              <span className="text-sm font-medium text-foreground">
                {graphName}
              </span>
              {graph && (
                <>
                  <span className="text-xs font-mono text-muted-foreground">
                    v{displayedVersion}
                  </span>
                  {displayedRevisionMeta && (
                    <Badge
                      className="text-[11px] px-1.5 py-0 h-4 font-medium"
                      style={{
                        backgroundColor: displayedRevisionMeta.color,
                        color: '#fff',
                        border: 'none',
                        animation: displayedRevisionMeta.pulse
                          ? 'revision-status-pulse 1.5s ease-out infinite'
                          : undefined,
                      }}>
                      {displayedRevisionMeta.label}
                    </Badge>
                  )}
                </>
              )}
            </PickerTrigger>
          </PopoverTrigger>
          <PopoverContent align="start" className="w-auto p-1">
            {revisionPopoverContent}
          </PopoverContent>
        </Popover>
      </div>

      {/* Right: status indicators + action buttons */}
      <div className="flex items-center gap-1.5">
        {lastFailedRevision && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Badge
                variant="outline"
                className="text-[11px] px-2 py-0 h-5 cursor-help"
                style={{
                  borderColor: REVISION_STATUS_STYLES.failed.color,
                  color: REVISION_STATUS_STYLES.failed.color,
                }}>
                v{lastFailedRevision.toVersion} Failed
              </Badge>
            </TooltipTrigger>
            <TooltipContent side="bottom">
              {lastFailedRevision.error ||
                `Revision to v${lastFailedRevision.toVersion} failed`}
            </TooltipContent>
          </Tooltip>
        )}
        {(graph?.error || graphError) && (
          <Popover>
            <PopoverTrigger asChild>
              <button className="flex items-center justify-center text-destructive cursor-pointer">
                <AlertCircle className="size-4" />
              </button>
            </PopoverTrigger>
            <PopoverContent
              align="end"
              className="max-w-[400px] bg-destructive/10 border-destructive/20">
              <div className="text-sm font-semibold mb-1">Graph Error</div>
              <div className="text-sm">{graph?.error || graphError}</div>
            </PopoverContent>
          </Popover>
        )}

        {/* Save */}
        {hasStructuralChanges ? (
          <HoverCard openDelay={100} closeDelay={150}>
            <HoverCardTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                aria-label="Save graph"
                disabled={saving || isRevisionApplying}
                onClick={() => {
                  if (!saving && !isRevisionApplying) onSave();
                }}
                className="w-8 h-8 p-0 text-primary hover:bg-primary/10 hover:border-primary/30 bg-primary/15 border-primary/60">
                {saving || isRevisionApplying ? (
                  <Loader2 className="size-4 animate-spin" />
                ) : (
                  <Save className="size-4" />
                )}
              </Button>
            </HoverCardTrigger>
            <HoverCardContent align="end" className="w-52 p-3">
              <div className="mb-2 text-sm font-semibold">Unsaved changes</div>
              {unsavedChangesPopoverContent}
              <Button
                size="sm"
                className="w-full mt-2"
                disabled={saving || isRevisionApplying}
                onClick={() => {
                  onSave();
                }}>
                {saving ? (
                  <Loader2 className="size-4 animate-spin mr-1" />
                ) : null}
                Save
              </Button>
            </HoverCardContent>
          </HoverCard>
        ) : (
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                aria-label="Save graph"
                disabled={saving || isRevisionApplying}
                onClick={() => {
                  if (!saving && !isRevisionApplying) onSave();
                }}
                className="w-8 h-8 p-0 text-primary hover:bg-primary/10 hover:border-primary/30">
                {saving || isRevisionApplying ? (
                  <Loader2 className="size-4 animate-spin" />
                ) : (
                  <Save className="size-4" />
                )}
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">
              {isRevisionApplying ? 'Applying revision...' : 'Save'}
            </TooltipContent>
          </Tooltip>
        )}

        {/* Run / Stop */}
        {graph && (
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="outline"
                size="sm"
                aria-label={
                  isGraphRunning ? 'Stop graph' : 'Start graph execution'
                }
                disabled={actionLoading || isGraphCompiling}
                onClick={() => {
                  if (!actionLoading && !isGraphCompiling) onGraphAction();
                }}
                className={`w-8 h-8 p-0 ${isGraphRunning ? 'text-destructive hover:bg-destructive/10 hover:border-destructive/30' : 'text-green-600 hover:bg-green-50 hover:border-green-300'}`}>
                {actionLoading || isGraphCompiling ? (
                  <Loader2 className="size-4 animate-spin" />
                ) : isGraphRunning ? (
                  <Square className="size-4" />
                ) : (
                  <PlayCircle className="size-4" />
                )}
              </Button>
            </TooltipTrigger>
            <TooltipContent side="bottom">
              {isGraphRunning
                ? 'Stop graph'
                : isGraphCompiling
                  ? 'Compiling...'
                  : 'Run graph'}
            </TooltipContent>
          </Tooltip>
        )}

        {/* More menu */}
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              variant="outline"
              size="sm"
              aria-label="Graph actions"
              className="w-8 h-8 p-0">
              <MoreVertical className="size-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            {graphMenuItems.map((item) => (
              <span key={item.key}>
                {item.separator && <DropdownMenuSeparator />}
                <DropdownMenuItem
                  disabled={item.disabled}
                  className={item.className}
                  onClick={() => onGraphMenuAction(item.key)}>
                  {item.label}
                </DropdownMenuItem>
              </span>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </header>
  );
};
