import {
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  HelpCircle,
  Search,
} from 'lucide-react';
import { useMemo, useState } from 'react';

import type { TemplateDto } from '../../../autogenerated';
import { Button } from '../../../components/ui/button';
import { Input } from '../../../components/ui/input';
import { ScrollArea } from '../../../components/ui/scroll-area';
import type { GraphNode } from '../types';

interface TemplateSidebarProps {
  onTemplateClick: (template: TemplateDto) => void;
  onClose: () => void;
  templates: TemplateDto[];
  selectedNode?: GraphNode;
  allNodes?: GraphNode[];
}

export const TemplateSidebar = ({
  onTemplateClick,
  onClose,
  templates,
  selectedNode: _selectedNode,
  allNodes: _allNodes = [],
}: TemplateSidebarProps) => {
  const [searchText, setSearchText] = useState('');
  const [expandedKinds, setExpandedKinds] = useState<Set<string>>(
    () => new Set(),
  );
  const isSearchActive = searchText.trim().length > 0;

  const onDragStart = (event: React.DragEvent, template: TemplateDto) => {
    event.dataTransfer.setData(
      'application/reactflow',
      JSON.stringify(template),
    );
    event.dataTransfer.effectAllowed = 'move';
  };

  const filteredTemplates = useMemo(() => {
    return templates.filter((template) => {
      if (template.kind?.toLowerCase() === 'knowledge') {
        return false;
      }
      const matchesSearch =
        !searchText ||
        template.name?.toLowerCase().includes(searchText.toLowerCase()) ||
        template.description
          ?.toLowerCase()
          .includes(searchText.toLowerCase()) ||
        template.kind?.toLowerCase().includes(searchText.toLowerCase());
      return matchesSearch;
    });
  }, [templates, searchText]);

  const groupedTemplates = useMemo(() => {
    const groups = new Map<string, TemplateDto[]>();

    filteredTemplates.forEach((template) => {
      const kind = String(template.kind ?? 'Other');
      const group = groups.get(kind) ?? [];
      group.push(template);
      groups.set(kind, group);
    });

    return Array.from(groups.entries()).sort(([a], [b]) => a.localeCompare(b));
  }, [filteredTemplates]);

  if (templates.length === 0) {
    return (
      <div style={{ padding: 24 }}>
        <span className="text-sm text-muted-foreground">
          No templates available
        </span>
      </div>
    );
  }

  const formatKindLabel = (kind: string) => {
    const normalized = kind.toLowerCase();
    switch (normalized) {
      case 'simpleagent':
        return 'Agent';
      case 'tool':
        return 'Tools';
      case 'trigger':
        return 'Triggers';
      case 'mcp':
        return 'MCP';
      case 'resource':
        return 'Resource';
      case 'runtime':
        return 'Runtime';
      default:
        return kind;
    }
  };

  const toggleKindExpanded = (kind: string) => {
    if (isSearchActive) {
      return;
    }
    setExpandedKinds((prev) => {
      const next = new Set(prev);
      if (next.has(kind)) {
        next.delete(kind);
      } else {
        next.add(kind);
      }
      return next;
    });
  };

  return (
    <div className="h-full bg-muted/40 flex flex-col">
      {/* Header — white card feel */}
      <div className="bg-card px-4 pt-4 pb-3 border-b border-border flex-shrink-0">
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-2">
            <span className="text-base font-semibold text-foreground">
              Templates
            </span>
            <span className="text-xs px-1.5 py-0.5 rounded-full bg-muted text-muted-foreground leading-none">
              {templates.length}
            </span>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={onClose}
            aria-label="Collapse template sidebar"
            className="h-7 w-7 p-0 text-muted-foreground hover:text-foreground">
            <ChevronLeft className="w-4 h-4" />
          </Button>
        </div>

        <div className="relative">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground pointer-events-none" />
          <Input
            placeholder="Search templates..."
            value={searchText}
            onChange={(e) => setSearchText(e.target.value)}
            className="pl-8 h-8 text-sm border-border bg-muted/50 focus-visible:bg-background"
          />
        </div>
        <p className="text-xs text-muted-foreground mt-2">
          Available results: {filteredTemplates.length}
        </p>
      </div>

      <ScrollArea className="flex-1">
        <div className="px-3 py-2 space-y-1">
          {filteredTemplates.length === 0 ? (
            <p className="text-sm text-muted-foreground text-center py-8">
              {searchText
                ? 'No templates match your search'
                : 'No templates available'}
            </p>
          ) : (
            <>
              <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wide px-1 py-2">
                Categories
              </p>
              {groupedTemplates.map(([kind, kindTemplates]) => {
                const isExpanded = isSearchActive || expandedKinds.has(kind);
                const kindLabel = formatKindLabel(kind);

                return (
                  <div key={kind}>
                    <button
                      className="w-full flex items-center justify-between px-3 py-2.5 rounded-lg bg-card border border-border hover:bg-muted/40 transition-colors text-left"
                      onClick={() => toggleKindExpanded(kind)}>
                      <div className="flex items-center gap-2.5 min-w-0">
                        <span className="text-sm font-medium text-foreground">
                          {kindLabel}
                        </span>
                        <span className="text-xs text-muted-foreground tabular-nums">
                          {kindTemplates.length}
                        </span>
                      </div>
                      {isExpanded ? (
                        <ChevronDown className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0" />
                      ) : (
                        <ChevronRight className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0" />
                      )}
                    </button>

                    {isExpanded && (
                      <div className="mt-1 space-y-1">
                        {kindTemplates.map((template) => (
                          <div
                            key={template.id}
                            draggable
                            onDragStart={(e) => onDragStart(e, template)}
                            className="flex items-start gap-2 px-3 py-2.5 rounded-lg bg-card border border-border hover:border-primary/30 hover:shadow-sm transition-all cursor-grab active:cursor-grabbing">
                            <div className="flex-1 min-w-0">
                              <p className="text-sm font-medium text-foreground truncate">
                                {template.name}
                              </p>
                              <p className="text-xs text-muted-foreground leading-relaxed mt-0.5 line-clamp-2">
                                {template.description}
                              </p>
                              <span className="inline-block mt-1.5 text-[11px] text-muted-foreground bg-muted px-2 py-0.5 rounded font-medium">
                                {String(template.kind)}
                              </span>
                            </div>
                            <button
                              className="mt-0.5 flex-shrink-0 text-muted-foreground/50 hover:text-muted-foreground transition-colors"
                              onClick={(e) => {
                                e.stopPropagation();
                                onTemplateClick(template);
                              }}>
                              <HelpCircle className="w-4 h-4" />
                            </button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                );
              })}
            </>
          )}
        </div>
      </ScrollArea>
    </div>
  );
};
