import type { TemplateDto } from '../../../autogenerated';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '../../../components/ui/dialog';
import { JsonViewer } from '../../../components/ui/json-view';
import { ScrollArea } from '../../../components/ui/scroll-area';
import { Separator } from '../../../components/ui/separator';

interface TemplateModalProps {
  template: TemplateDto | null;
  visible: boolean;
  onClose: () => void;
  allTemplates?: TemplateDto[];
}

export const TemplateModal = ({
  template,
  visible,
  onClose,
  allTemplates = [],
}: TemplateModalProps) => {
  if (!template) return null;

  return (
    <Dialog open={visible} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="max-w-lg p-0 gap-0 overflow-hidden">
        {/* Header */}
        <div className="px-5 pt-5 pb-4 border-b border-border">
          <DialogHeader>
            <DialogTitle className="text-base font-semibold text-left flex items-center gap-2">
              <span className="text-[11px] font-medium bg-muted text-muted-foreground px-2 py-0.5 rounded leading-none">
                {template.kind}
              </span>
              {template.name}
            </DialogTitle>
          </DialogHeader>
          <p className="text-xs text-muted-foreground mt-1 leading-relaxed">
            {template.description}
          </p>
        </div>

        <ScrollArea className="max-h-[60vh]">
          <div className="px-5 py-4 space-y-5">
            {/* Available Inputs */}
            <div>
              <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wide mb-2">
                Available Inputs
              </p>
              {template.inputs && template.inputs.length > 0 ? (
                <div className="space-y-3">
                  {template.inputs.map((rule, i) => {
                    const matching = allTemplates.filter((t) =>
                      rule.type === 'kind'
                        ? t.kind === rule.value
                        : t.name === rule.value,
                    );
                    return (
                      <div key={i}>
                        <div className="flex items-center gap-1.5 mb-1.5">
                          <span className="text-[10px] font-mono bg-muted px-1.5 py-0.5 rounded text-muted-foreground">
                            {rule.type}
                          </span>
                          <span className="text-xs font-medium">
                            {rule.value}
                          </span>
                          {rule.required && (
                            <span className="text-[10px] bg-destructive/10 text-destructive px-1.5 py-0.5 rounded">
                              required
                            </span>
                          )}
                          {rule.multiple && (
                            <span className="text-[10px] bg-amber-500/10 text-amber-600 px-1.5 py-0.5 rounded">
                              multiple
                            </span>
                          )}
                        </div>
                        {matching.length > 0 && (
                          <div className="ml-3 border-l border-border pl-3 space-y-1">
                            {matching.map((t) => (
                              <div
                                key={t.id}
                                className="flex items-center gap-2 py-0.5">
                                <span className="text-xs font-medium text-foreground">
                                  {t.name}
                                </span>
                                <span className="text-[10px] text-muted-foreground truncate">
                                  {t.description}
                                </span>
                              </div>
                            ))}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              ) : (
                <p className="text-xs text-muted-foreground italic">
                  No available inputs for this node
                </p>
              )}
            </div>

            <Separator />

            {/* Schema Definition */}
            <div>
              <p className="text-[11px] font-medium text-muted-foreground uppercase tracking-wide mb-2">
                Schema Definition
              </p>
              <div className="w-full rounded-lg border border-gray-200 bg-white overflow-auto max-h-80 p-1.5">
                <JsonViewer value={template.schema as object} />
              </div>
            </div>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
};
