import { History, Loader2 } from 'lucide-react';
import React from 'react';

import type {
  ThreadUsageStatisticsDto,
  ThreadUsageStatisticsDtoSchema0,
} from '../../../autogenerated';
import { Button } from '../../../components/ui/button';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../components/ui/table';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '../../../components/ui/tooltip';

/** Tool row with a stable key and optional children for tree table. */
interface ToolRow extends ThreadUsageStatisticsDtoSchema0 {
  key: string;
  children?: ToolRow[];
  depth?: number;
}

/** Recursively transform byTool entries into rows with unique keys and `children`. */
const toToolRows = (
  items: ThreadUsageStatisticsDtoSchema0[],
  parentKey = '',
  depth = 0,
): ToolRow[] =>
  items.map((item, idx) => {
    const key = parentKey ? `${parentKey}-${idx}` : `tool-${idx}`;
    return {
      ...item,
      key,
      depth,
      children:
        item.subCalls && item.subCalls.length > 0
          ? toToolRows(item.subCalls, key, depth + 1)
          : undefined,
    };
  });

/** Flatten a tree of ToolRow into a flat array for rendering. */
const flattenToolRows = (rows: ToolRow[]): ToolRow[] => {
  const result: ToolRow[] = [];
  for (const row of rows) {
    result.push(row);
    if (row.children) {
      result.push(...flattenToolRows(row.children));
    }
  }
  return result;
};

interface ThreadUsageDisplayProps {
  usage: ThreadUsageStatisticsDto | null;
  loading: boolean;
  error: string | null;
  nodeDisplayNames?: Record<string, string>;
  nodeKinds?: Record<string, string>;
  localEventsCount?: number;
  onShowLocalEvents?: () => void;
}

const formatNumber = (num?: number | null): string => {
  if (typeof num !== 'number' || !Number.isFinite(num)) return '\u2014';
  return new Intl.NumberFormat('en-US').format(num);
};

const formatUsd = (amount?: number | null): string => {
  if (typeof amount !== 'number' || !Number.isFinite(amount)) return '$\u2014';
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 4,
    maximumFractionDigits: 4,
  }).format(amount);
};

const StatItem: React.FC<{ label: string; value: string }> = ({
  label,
  value,
}) => (
  <div>
    <p className="text-xs text-muted-foreground mb-1">{label}</p>
    <p className="font-semibold">{value}</p>
  </div>
);

export const ThreadUsageDisplay: React.FC<ThreadUsageDisplayProps> = ({
  usage,
  loading,
  error,
  nodeDisplayNames = {},
  nodeKinds = {},
  localEventsCount,
  onShowLocalEvents,
}) => {
  if (loading) {
    return (
      <div className="border rounded-lg p-3 mt-2">
        <div className="flex items-center gap-2">
          <Loader2 className="size-4 animate-spin" />
          <span className="text-sm text-muted-foreground">
            Loading usage statistics...
          </span>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="border rounded-lg p-3 mt-2">
        <span className="text-sm text-destructive">{error}</span>
      </div>
    );
  }

  if (!usage) {
    return null;
  }

  const {
    total,
    requests,
    byNode,
    byTool,
    toolsAggregate,
    userMessageCount,
    modelsUsed,
  } = usage;

  // Prepare byNode data
  const byNodeData = byNode
    ? Object.entries(byNode).map(([nodeId, stats]) => ({
        nodeId,
        nodeName: nodeDisplayNames[nodeId] || nodeId,
        nodeKind: nodeKinds[nodeId] || 'Node',
        ...stats,
      }))
    : [];

  // Transform byTool into tree-compatible rows with unique keys
  const toolRows: ToolRow[] = byTool ? toToolRows(byTool) : [];

  // Check if any tool has execution cost
  const anyToolHasOwnCost = toolRows.some(
    (r) =>
      (typeof r.toolTokens === 'number' && r.toolTokens > 0) ||
      (typeof r.toolPrice === 'number' && r.toolPrice > 0),
  );

  const flatToolRows = flattenToolRows(toolRows);

  const hasLocalEvents =
    typeof localEventsCount === 'number' && localEventsCount > 0;

  const formatCompact = (n?: number | null): string => {
    if (typeof n !== 'number' || !Number.isFinite(n)) return '\u2014';
    return n >= 1000
      ? `${(n / 1000).toFixed(1).replace(/\.0$/, '')}K`
      : String(n);
  };

  return (
    <div className="space-y-5 text-sm">
      {hasLocalEvents && onShowLocalEvents && (
        <div className="flex justify-end">
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="ghost"
                size="sm"
                className="gap-1.5 text-xs"
                onClick={onShowLocalEvents}>
                <History className="size-3.5" />
                {localEventsCount} events
              </Button>
            </TooltipTrigger>
            <TooltipContent>View socket events</TooltipContent>
          </Tooltip>
        </div>
      )}

      {/* Total Usage */}
      <div className="border border-border rounded-lg p-4">
        <p className="font-semibold mb-3">Total Usage</p>
        <div className="grid grid-cols-7 gap-3 mb-3">
          {typeof requests === 'number' && (
            <StatItem label="Requests" value={formatNumber(requests)} />
          )}
          {typeof userMessageCount === 'number' && (
            <StatItem
              label="User Messages"
              value={formatNumber(userMessageCount)}
            />
          )}
          <StatItem
            label="Total Tokens"
            value={formatNumber(total.totalTokens)}
          />
          <StatItem
            label="Input Tokens"
            value={formatNumber(total.inputTokens)}
          />
          {typeof total.cachedInputTokens === 'number' && (
            <StatItem
              label="Cached Input"
              value={formatNumber(total.cachedInputTokens)}
            />
          )}
          <StatItem
            label="Output Tokens"
            value={formatNumber(total.outputTokens)}
          />
          {typeof total.reasoningTokens === 'number' && (
            <StatItem
              label="Reasoning"
              value={formatNumber(total.reasoningTokens)}
            />
          )}
        </div>
        <div className="grid grid-cols-4 gap-3 pt-3 border-t border-border">
          <StatItem
            label="Token usage"
            value={`${formatCompact(total.totalTokens)} (${formatUsd(total.totalPrice)})`}
          />
          {typeof total.totalPrice === 'number' && (
            <StatItem label="Total Cost" value={formatUsd(total.totalPrice)} />
          )}
          {typeof total.currentContext === 'number' && (
            <StatItem
              label="Current Context"
              value={formatNumber(total.currentContext)}
            />
          )}
        </div>
      </div>

      {/* Models Used */}
      {modelsUsed && modelsUsed.length > 0 && (
        <div className="border border-border rounded-lg p-4">
          <p className="font-semibold mb-3">
            Models Used ({modelsUsed.length})
          </p>
          <div className="flex flex-wrap gap-2">
            {modelsUsed.map((model) => (
              <span
                key={model}
                className="font-mono text-xs bg-muted px-2 py-1 rounded">
                {model}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Tools Aggregate */}
      {toolsAggregate && (
        <div className="border border-border rounded-lg p-4">
          <p className="font-semibold mb-3">Tools Aggregate</p>
          <div className="grid grid-cols-3 gap-3">
            <StatItem
              label="Requests"
              value={formatNumber(toolsAggregate.requestCount)}
            />
            <StatItem
              label="Tokens"
              value={formatNumber(toolsAggregate.totalTokens)}
            />
            {typeof toolsAggregate.totalPrice === 'number' && (
              <StatItem
                label="Cost"
                value={formatUsd(toolsAggregate.totalPrice)}
              />
            )}
          </div>
        </div>
      )}

      {/* Usage by Agent */}
      {byNodeData.length > 0 && (
        <div className="border border-border rounded-lg overflow-hidden">
          <div className="px-4 py-3 border-b border-border">
            <p className="font-semibold">
              Usage by Agent ({byNodeData.length})
            </p>
          </div>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Agent</TableHead>
                <TableHead>Total Tokens</TableHead>
                <TableHead>Input</TableHead>
                <TableHead>Output</TableHead>
                <TableHead>Cached</TableHead>
                <TableHead>Reasoning</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {byNodeData.map((record) => (
                <TableRow key={record.nodeId}>
                  <TableCell className="font-medium">
                    {record.nodeName}
                  </TableCell>
                  <TableCell>{formatNumber(record.totalTokens)}</TableCell>
                  <TableCell>{formatNumber(record.inputTokens)}</TableCell>
                  <TableCell>{formatNumber(record.outputTokens)}</TableCell>
                  <TableCell>
                    {typeof record.cachedInputTokens === 'number' &&
                    record.cachedInputTokens > 0
                      ? formatNumber(record.cachedInputTokens)
                      : '\u2013'}
                  </TableCell>
                  <TableCell>
                    {typeof record.reasoningTokens === 'number' &&
                    record.reasoningTokens > 0
                      ? formatNumber(record.reasoningTokens)
                      : '\u2013'}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}

      {/* Usage by Tool */}
      {flatToolRows.length > 0 && (
        <div className="border border-border rounded-lg overflow-hidden">
          <div className="px-4 py-3 border-b border-border">
            <p className="font-semibold">Usage by Tool ({byTool.length})</p>
          </div>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Tool Name</TableHead>
                <TableHead>Call Count</TableHead>
                <TableHead>LLM Tokens</TableHead>
                <TableHead>LLM Price</TableHead>
                {anyToolHasOwnCost && (
                  <>
                    <TableHead>Tool Tokens</TableHead>
                    <TableHead>Tool Price</TableHead>
                  </>
                )}
              </TableRow>
            </TableHeader>
            <TableBody>
              {flatToolRows.map((row) => (
                <TableRow key={row.key}>
                  <TableCell className="font-medium">
                    <span
                      style={{
                        paddingLeft: (row.depth ?? 0) * 20,
                      }}>
                      {row.toolName}
                    </span>
                  </TableCell>
                  <TableCell>{formatNumber(row.callCount)}</TableCell>
                  <TableCell>{formatNumber(row.totalTokens)}</TableCell>
                  <TableCell>{formatUsd(row.totalPrice)}</TableCell>
                  {anyToolHasOwnCost && (
                    <>
                      <TableCell>
                        {typeof row.toolTokens === 'number' &&
                        row.toolTokens > 0
                          ? formatNumber(row.toolTokens)
                          : '\u2013'}
                      </TableCell>
                      <TableCell>
                        {typeof row.toolPrice === 'number' && row.toolPrice > 0
                          ? formatUsd(row.toolPrice)
                          : '\u2013'}
                      </TableCell>
                    </>
                  )}
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}
    </div>
  );
};
