import type { SocketNotification } from '../../../services/WebSocketTypes';
export type ThreadTokenUsageSnapshot = {
  inputTokens?: number;
  cachedInputTokens?: number;
  outputTokens?: number;
  reasoningTokens?: number;
  totalTokens?: number;
  totalPrice?: number;
  currentContext?: number;
};

export type ThreadSocketEventEntry = {
  id: string;
  receivedAt: string;
  type: string;
  nodeId?: string;
  runId?: string;
  graphId?: string;
  payload: SocketNotification;
};

export type ThreadStatusTabKey = 'open' | 'resolved' | 'all';

export type MessageMeta = {
  loading: boolean;
  loadingMore: boolean;
  hasMore: boolean;
  offset: number;
  /**
   * When the initial (offset=0) fetch fails, we must not auto-retry in a loop.
   * This flag is cleared on an explicit user retry (force load).
   */
  initialLoadFailed: boolean;
};

export interface DraftThread {
  id: string;
  graphId: string;
  name: string | null;
  status: 'draft';
  createdAt: string;
  updatedAt: string;
  externalThreadId: string;
  isDraft: true;
}

export interface GraphCacheEntry {
  graph: import('../../../autogenerated').GraphPreviewDto;
  triggerNodes: import('../../../utils/graphThreads').TriggerNodeInfo[];
  nodeDisplayNames: Record<string, string>;
}

export interface FullGraphCacheEntry {
  graph: import('../../../autogenerated').GraphDto;
  fetchedAt: number;
}
