import { isAxiosError } from 'axios';
import {
  AlertTriangle,
  Check,
  ChevronDown,
  ChevronsUpDown,
  Database,
  KeyRound,
  Loader2,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Trash2,
  X,
  Zap,
} from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';

import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible';
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandInput,
  CommandItem,
  CommandList,
} from '@/components/ui/command';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { LabelsInput } from '@/components/ui/labels-input';
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from '@/components/ui/sheet';
import { Skeleton } from '@/components/ui/skeleton';
import { Textarea } from '@/components/ui/textarea';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import { cn } from '@/components/ui/utils';

import { litellmApi } from '../../api';
import type {
  CreateLiteLlmModelDtoLitellmParams,
  LiteLlmModelInfoItemDto,
} from '../../autogenerated';
import { extractApiErrorMessage } from '../../utils/errors';

// -- Types --

type ModalMode = 'create' | 'edit';

interface TestStatus {
  loading: boolean;
  success?: boolean;
  latencyMs?: number;
  error?: string;
}

interface ProviderInfo {
  name: string;
  label: string;
  modelHint: string;
}

interface CredentialInfo {
  credentialName: string;
}

interface FormState {
  provider: string;
  litellmModelName: string;
  publicModelName: string;
  existingCredential: string;
  apiKey: string;
  apiBase: string;
  tags: string[];
  litellmParamsJson: string;
  modelInfoJson: string;
}

const EMPTY_FORM: FormState = {
  provider: '',
  litellmModelName: '',
  publicModelName: '',
  existingCredential: '',
  apiKey: '',
  apiBase: '',
  tags: [],
  litellmParamsJson: '',
  modelInfoJson: '',
};

const NONE_CREDENTIAL = '__none__';

const formFromModel = (m: LiteLlmModelInfoItemDto): FormState => ({
  provider: '',
  litellmModelName: m.providerModel,
  publicModelName: m.modelName,
  existingCredential: '',
  apiKey: '',
  apiBase: m.apiBase ?? '',
  tags: [],
  litellmParamsJson: '',
  modelInfoJson: '',
});

// -- Credential management helpers --

interface CredentialFormState {
  credentialName: string;
  apiKey: string;
  apiBase: string;
}

const EMPTY_CREDENTIAL_FORM: CredentialFormState = {
  credentialName: '',
  apiKey: '',
  apiBase: '',
};

// -- CredentialsSheet --

function CredentialsSheet({
  open,
  onOpenChange,
  credentials,
  onCredentialsChanged,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  credentials: CredentialInfo[];
  onCredentialsChanged: () => void;
}) {
  const [credForm, setCredForm] = useState<CredentialFormState>(
    EMPTY_CREDENTIAL_FORM,
  );
  const [savingCredential, setSavingCredential] = useState(false);
  const [confirmDeleteName, setConfirmDeleteName] = useState<string | null>(
    null,
  );
  const [deletingCredential, setDeletingCredential] = useState(false);

  const canSaveCredential =
    credForm.credentialName.trim().length > 0 &&
    credForm.apiKey.trim().length > 0;

  const handleCreateCredential = async () => {
    setSavingCredential(true);
    try {
      const credentialValues: Record<string, string> = {
        api_key: credForm.apiKey,
      };
      if (credForm.apiBase.trim()) {
        credentialValues['api_base'] = credForm.apiBase;
      }
      await litellmApi.createCredential({
        credentialName: credForm.credentialName,
        credentialValues,
      });
      toast.success(`Credential "${credForm.credentialName}" created`);
      setCredForm(EMPTY_CREDENTIAL_FORM);
      onCredentialsChanged();
    } catch (err: unknown) {
      toast.error(extractApiErrorMessage(err, 'Failed to create credential'));
    } finally {
      setSavingCredential(false);
    }
  };

  const handleDeleteCredential = async (name: string) => {
    setDeletingCredential(true);
    try {
      await litellmApi.deleteCredential(name);
      toast.success(`Credential "${name}" deleted`);
      setConfirmDeleteName(null);
      onCredentialsChanged();
    } catch (err: unknown) {
      toast.error(extractApiErrorMessage(err, 'Failed to delete credential'));
    } finally {
      setDeletingCredential(false);
    }
  };

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="sm:max-w-md">
        <SheetHeader>
          <SheetTitle>Manage Credentials</SheetTitle>
        </SheetHeader>

        <div className="flex flex-col gap-4 px-4 pb-4 overflow-y-auto flex-1">
          {/* Existing credentials list */}
          {credentials.length > 0 && (
            <div className="border border-border rounded-xl overflow-hidden bg-card">
              {credentials.map((cred) => (
                <div
                  key={cred.credentialName}
                  className="flex items-center justify-between px-3 py-2 border-b border-border last:border-b-0">
                  <div className="flex items-center gap-2 min-w-0">
                    <KeyRound className="w-3.5 h-3.5 text-muted-foreground shrink-0" />
                    <span className="text-sm font-medium truncate">
                      {cred.credentialName}
                    </span>
                  </div>
                  {confirmDeleteName === cred.credentialName ? (
                    <div className="flex items-center gap-1 shrink-0">
                      <Button
                        variant="destructive"
                        size="sm"
                        className="h-7 text-xs"
                        disabled={deletingCredential}
                        onClick={() =>
                          handleDeleteCredential(cred.credentialName)
                        }>
                        {deletingCredential && (
                          <Loader2 className="w-3 h-3 animate-spin mr-1" />
                        )}
                        Confirm
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-7 text-xs"
                        disabled={deletingCredential}
                        onClick={() => setConfirmDeleteName(null)}>
                        Cancel
                      </Button>
                    </div>
                  ) : (
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-7 w-7 p-0 text-muted-foreground hover:text-destructive shrink-0"
                      onClick={() => setConfirmDeleteName(cred.credentialName)}>
                      <Trash2 className="w-3.5 h-3.5" />
                    </Button>
                  )}
                </div>
              ))}
            </div>
          )}

          {credentials.length === 0 && (
            <div className="flex flex-col items-center justify-center py-8 text-center">
              <KeyRound className="h-8 w-8 text-muted-foreground/40 mb-2" />
              <p className="text-sm text-muted-foreground">
                No credentials saved yet.
              </p>
            </div>
          )}

          <Separator />

          {/* Add Credential form */}
          <div className="space-y-3">
            <h4 className="text-sm font-medium">Add Credential</h4>
            <div className="space-y-1.5">
              <Label htmlFor="credName">Credential Name</Label>
              <Input
                id="credName"
                placeholder="e.g. openai-prod"
                value={credForm.credentialName}
                onChange={(e) =>
                  setCredForm((prev) => ({
                    ...prev,
                    credentialName: e.target.value,
                  }))
                }
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="credApiKey">API Key</Label>
              <Input
                id="credApiKey"
                type="password"
                placeholder="sk-..."
                value={credForm.apiKey}
                onChange={(e) =>
                  setCredForm((prev) => ({ ...prev, apiKey: e.target.value }))
                }
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="credApiBase">API Base (optional)</Label>
              <Input
                id="credApiBase"
                placeholder="https://api.openai.com/v1"
                value={credForm.apiBase}
                onChange={(e) =>
                  setCredForm((prev) => ({ ...prev, apiBase: e.target.value }))
                }
              />
            </div>
            <Button
              size="sm"
              disabled={!canSaveCredential || savingCredential}
              onClick={handleCreateCredential}>
              {savingCredential && (
                <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" />
              )}
              Add Credential
            </Button>
          </div>
        </div>
      </SheetContent>
    </Sheet>
  );
}

// -- ModelFormDialog --

function ModelFormDialog({
  open,
  onOpenChange,
  mode,
  editingModel,
  providers,
  credentials,
  onSaved,
  onOpenCredentials,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  mode: ModalMode;
  editingModel: LiteLlmModelInfoItemDto | null;
  providers: ProviderInfo[];
  credentials: CredentialInfo[];
  onSaved: () => void;
  onOpenCredentials: () => void;
}) {
  const [form, setForm] = useState<FormState>(EMPTY_FORM);
  const [providerOpen, setProviderOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [testStatus, setTestStatus] = useState<TestStatus | null>(null);
  const [litellmParamsError, setLitellmParamsError] = useState<string | null>(
    null,
  );
  const [modelInfoError, setModelInfoError] = useState<string | null>(null);

  // Reset form when dialog opens
  useEffect(() => {
    if (open) {
      if (mode === 'edit' && editingModel) {
        setForm(formFromModel(editingModel));
      } else {
        setForm(EMPTY_FORM);
      }
      setTestStatus(null);
      setLitellmParamsError(null);
      setModelInfoError(null);
    }
  }, [open, mode, editingModel]);

  const handleFormChange = <K extends keyof FormState>(
    field: K,
    value: FormState[K],
  ) => {
    setForm((prev) => {
      const next = { ...prev, [field]: value };

      // When credential is selected to a non-None value, clear API Key
      if (
        field === 'existingCredential' &&
        typeof value === 'string' &&
        value !== '' &&
        value !== NONE_CREDENTIAL
      ) {
        next.apiKey = '';
      }

      // When API Key is typed, reset credential to none
      if (field === 'apiKey' && typeof value === 'string' && value !== '') {
        next.existingCredential = '';
      }

      return next;
    });
  };

  const handleProviderChange = (providerName: string) => {
    setForm((prev) => ({ ...prev, provider: providerName }));
  };

  const validateJsonField = (
    value: string,
    setError: (err: string | null) => void,
  ): Record<string, unknown> | null => {
    if (!value.trim()) {
      setError(null);
      return null;
    }
    try {
      const parsed = JSON.parse(value) as Record<string, unknown>;
      setError(null);
      return parsed;
    } catch {
      setError('Invalid JSON');
      return null;
    }
  };

  const buildPayload = (): {
    litellmParams: CreateLiteLlmModelDtoLitellmParams & Record<string, unknown>;
    parsedModelInfo: Record<string, unknown> | null;
  } | null => {
    let parsedLitellmParams: Record<string, unknown> | null = null;
    let parsedModelInfo: Record<string, unknown> | null = null;

    if (form.litellmParamsJson.trim()) {
      try {
        parsedLitellmParams = JSON.parse(form.litellmParamsJson) as Record<
          string,
          unknown
        >;
      } catch {
        setLitellmParamsError('Invalid JSON');
        return null;
      }
    }

    if (form.modelInfoJson.trim()) {
      try {
        parsedModelInfo = JSON.parse(form.modelInfoJson) as Record<
          string,
          unknown
        >;
      } catch {
        setModelInfoError('Invalid JSON');
        return null;
      }
    }

    return {
      litellmParams: {
        model: form.litellmModelName,
        ...(form.apiKey ? { apiKey: form.apiKey } : {}),
        ...(form.apiBase ? { apiBase: form.apiBase } : {}),
        ...(form.existingCredential &&
        form.existingCredential !== NONE_CREDENTIAL
          ? { litellmCredentialName: form.existingCredential }
          : {}),
        ...parsedLitellmParams,
      },
      parsedModelInfo,
    };
  };

  const handleSave = async () => {
    const payload = buildPayload();
    if (!payload) return;

    setSaving(true);
    try {
      if (mode === 'create') {
        await litellmApi.createModel({
          modelName: form.publicModelName,
          litellmParams: payload.litellmParams,
          tags: form.tags.length ? form.tags : undefined,
          modelInfo: payload.parsedModelInfo ?? undefined,
        });
        toast.success(`Model "${form.publicModelName}" created`);
      } else {
        await litellmApi.updateModel({
          modelId: editingModel!.id,
          modelName: form.publicModelName,
          litellmParams: payload.litellmParams,
          tags: form.tags.length ? form.tags : undefined,
          modelInfo: payload.parsedModelInfo ?? undefined,
        });
        toast.success(`Model "${form.publicModelName}" updated`);
      }
      onOpenChange(false);
      onSaved();
    } catch (err: unknown) {
      toast.error(
        extractApiErrorMessage(
          err,
          mode === 'create'
            ? 'Failed to create model'
            : 'Failed to update model',
        ),
      );
    } finally {
      setSaving(false);
    }
  };

  const handleTest = async () => {
    setTestStatus({ loading: true });
    try {
      let response;
      if (mode === 'edit') {
        // For existing models, test via the registered model name
        response = await litellmApi.testModel({
          model: form.publicModelName,
        });
      } else {
        // For new models, test with inline config (no registration needed)
        response = await litellmApi.testModelConnection({
          litellmModel: form.litellmModelName,
          ...(form.apiKey ? { apiKey: form.apiKey } : {}),
          ...(form.apiBase ? { apiBase: form.apiBase } : {}),
          ...(form.existingCredential &&
          form.existingCredential !== NONE_CREDENTIAL
            ? { litellmCredentialName: form.existingCredential }
            : {}),
        });
      }
      const result = response.data;
      setTestStatus({
        loading: false,
        success: result.success,
        latencyMs: result.latencyMs,
        error: result.error,
      });
    } catch (err: unknown) {
      setTestStatus({
        loading: false,
        success: false,
        error: extractApiErrorMessage(err, 'Test failed'),
      });
    }
  };

  const canSave =
    form.publicModelName.trim().length > 0 &&
    form.litellmModelName.trim().length > 0;

  const canTest = canSave;

  const credentialValue =
    form.existingCredential === '' ? NONE_CREDENTIAL : form.existingCredential;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-lg max-h-[85vh] flex flex-col">
        <DialogHeader>
          <DialogTitle>
            {mode === 'create' ? 'Add Model' : 'Edit Model'}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 py-2 overflow-y-auto flex-1 px-1">
          {/* Provider */}
          <div className="space-y-1.5">
            <Label>Provider</Label>
            <Popover open={providerOpen} onOpenChange={setProviderOpen}>
              <PopoverTrigger asChild>
                <Button
                  variant="outline"
                  role="combobox"
                  aria-expanded={providerOpen}
                  className="w-full justify-between font-normal">
                  {form.provider
                    ? (providers.find((p) => p.name === form.provider)?.label ??
                      form.provider)
                    : 'Select a provider...'}
                  <ChevronsUpDown className="ml-2 size-4 shrink-0 opacity-50" />
                </Button>
              </PopoverTrigger>
              <PopoverContent className="w-[--radix-popover-trigger-width] p-0">
                <Command>
                  <CommandInput placeholder="Search providers..." />
                  <CommandList>
                    <CommandEmpty>No provider found.</CommandEmpty>
                    <CommandGroup>
                      {providers.map((p) => (
                        <CommandItem
                          key={p.name}
                          value={p.label}
                          onSelect={() => {
                            handleProviderChange(p.name);
                            setProviderOpen(false);
                          }}>
                          <Check
                            className={cn(
                              'mr-2 size-4',
                              form.provider === p.name
                                ? 'opacity-100'
                                : 'opacity-0',
                            )}
                          />
                          {p.label}
                        </CommandItem>
                      ))}
                    </CommandGroup>
                  </CommandList>
                </Command>
              </PopoverContent>
            </Popover>
          </div>

          {/* LiteLLM Model Name */}
          <div className="space-y-1.5">
            <Label htmlFor="litellmModelName">LiteLLM Model Name</Label>
            <Input
              id="litellmModelName"
              placeholder={
                providers.find((p) => p.name === form.provider)?.modelHint ||
                'e.g. openai/gpt-4o'
              }
              value={form.litellmModelName}
              onChange={(e) =>
                handleFormChange('litellmModelName', e.target.value)
              }
            />
          </div>

          {/* Public Model Name */}
          <div className="space-y-1.5">
            <Label htmlFor="publicModelName">Public Model Name</Label>
            <Input
              id="publicModelName"
              placeholder="e.g. gpt-4o"
              value={form.publicModelName}
              onChange={(e) =>
                handleFormChange('publicModelName', e.target.value)
              }
              disabled={mode === 'edit'}
            />
          </div>

          <Separator />

          {/* Existing Credentials */}
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label>Existing Credentials</Label>
              <Button
                variant="link"
                size="sm"
                className="h-auto p-0 text-xs"
                onClick={onOpenCredentials}>
                Manage Credentials &rarr;
              </Button>
            </div>
            <Select
              value={credentialValue}
              onValueChange={(v) =>
                handleFormChange(
                  'existingCredential',
                  v === NONE_CREDENTIAL ? '' : v,
                )
              }>
              <SelectTrigger>
                <SelectValue placeholder="None" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value={NONE_CREDENTIAL}>None</SelectItem>
                {credentials.map((c) => (
                  <SelectItem key={c.credentialName} value={c.credentialName}>
                    {c.credentialName}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* API Key */}
          <div className="space-y-1.5">
            <Label htmlFor="apiKey">API Key</Label>
            <Input
              id="apiKey"
              type="password"
              placeholder={
                form.existingCredential &&
                form.existingCredential !== NONE_CREDENTIAL
                  ? 'Using credential above'
                  : 'Leave blank to keep existing'
              }
              value={form.apiKey}
              onChange={(e) => handleFormChange('apiKey', e.target.value)}
              disabled={
                !!form.existingCredential &&
                form.existingCredential !== NONE_CREDENTIAL
              }
            />
          </div>

          <Separator />

          {/* API Base */}
          <div className="space-y-1.5">
            <Label htmlFor="apiBase">API Base (optional)</Label>
            <Input
              id="apiBase"
              placeholder="https://api.openai.com/v1"
              value={form.apiBase}
              onChange={(e) => handleFormChange('apiBase', e.target.value)}
            />
          </div>

          <Separator />

          {/* Advanced Settings */}
          <Collapsible>
            <CollapsibleTrigger asChild>
              <Button
                variant="ghost"
                size="sm"
                className="group flex items-center gap-1 px-0 text-muted-foreground hover:text-foreground">
                <ChevronDown className="w-3.5 h-3.5 transition-transform -rotate-90 group-data-[state=open]:rotate-0" />
                Advanced Settings
              </Button>
            </CollapsibleTrigger>
            <CollapsibleContent className="space-y-4 pt-2">
              {/* Tags */}
              <div className="space-y-1.5">
                <Label>Tags</Label>
                <LabelsInput
                  value={form.tags}
                  onChange={(tags) => handleFormChange('tags', tags)}
                  placeholder="Add tag and press Enter"
                />
              </div>

              {/* LiteLLM Params JSON */}
              <div className="space-y-1.5">
                <Label htmlFor="litellmParamsJson">LiteLLM Params (JSON)</Label>
                <Textarea
                  id="litellmParamsJson"
                  placeholder='{"custom_llm_provider": "azure"}'
                  value={form.litellmParamsJson}
                  onChange={(e) =>
                    handleFormChange('litellmParamsJson', e.target.value)
                  }
                  onBlur={() =>
                    validateJsonField(
                      form.litellmParamsJson,
                      setLitellmParamsError,
                    )
                  }
                  rows={3}
                  className="font-mono text-xs"
                />
                {litellmParamsError && (
                  <p className="text-xs text-destructive">
                    {litellmParamsError}
                  </p>
                )}
              </div>

              {/* Model Info JSON */}
              <div className="space-y-1.5">
                <Label htmlFor="modelInfoJson">Model Info (JSON)</Label>
                <Textarea
                  id="modelInfoJson"
                  placeholder='{"max_tokens": 128000}'
                  value={form.modelInfoJson}
                  onChange={(e) =>
                    handleFormChange('modelInfoJson', e.target.value)
                  }
                  onBlur={() =>
                    validateJsonField(form.modelInfoJson, setModelInfoError)
                  }
                  rows={3}
                  className="font-mono text-xs"
                />
                {modelInfoError && (
                  <p className="text-xs text-destructive">{modelInfoError}</p>
                )}
              </div>
            </CollapsibleContent>
          </Collapsible>
        </div>

        {/* Test status inline */}
        {testStatus && !testStatus.loading && (
          <div className="px-1 pb-1">
            {testStatus.success ? (
              <div className="flex items-center gap-1.5 text-sm text-green-600">
                <Check className="w-4 h-4" />
                Connection successful ({testStatus.latencyMs}ms)
              </div>
            ) : (
              <div className="flex items-center gap-1.5 text-sm text-destructive">
                <X className="w-4 h-4" />
                {testStatus.error ?? 'Test failed'}
              </div>
            )}
          </div>
        )}

        <DialogFooter className="gap-2">
          <Button
            variant="outline"
            onClick={handleTest}
            disabled={!canTest || (testStatus?.loading ?? false)}>
            {testStatus?.loading ? (
              <Loader2 className="w-4 h-4 animate-spin mr-1" />
            ) : (
              <Zap className="w-4 h-4 mr-1" />
            )}
            Test Connection
          </Button>
          <div className="flex-1" />
          <Button
            variant="outline"
            onClick={() => onOpenChange(false)}
            disabled={saving}>
            Cancel
          </Button>
          <Button onClick={handleSave} disabled={saving || !canSave}>
            {saving && <Loader2 className="w-4 h-4 animate-spin mr-1" />}
            {mode === 'create' ? 'Create' : 'Save'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// -- Main Page --

export const LiteLlmAdminPage = () => {
  const [models, setModels] = useState<LiteLlmModelInfoItemDto[]>([]);
  const [loading, setLoading] = useState(true);
  const [litellmUnavailable, setLitellmUnavailable] = useState(false);

  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<ModalMode>('create');
  const [editingModel, setEditingModel] =
    useState<LiteLlmModelInfoItemDto | null>(null);

  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [deletingModel, setDeletingModel] =
    useState<LiteLlmModelInfoItemDto | null>(null);
  const [deleting, setDeleting] = useState(false);

  const [testStatus, setTestStatus] = useState<Record<string, TestStatus>>({});

  const [providers, setProviders] = useState<ProviderInfo[]>([]);
  const [credentials, setCredentials] = useState<CredentialInfo[]>([]);
  const [credentialsSheetOpen, setCredentialsSheetOpen] = useState(false);

  const loadModels = useCallback(async () => {
    setLoading(true);
    setLitellmUnavailable(false);
    try {
      const response = await litellmApi.listModelsInfo();
      setModels(response.data);
    } catch (err: unknown) {
      if (
        isAxiosError(err) &&
        (err.response === undefined ||
          (err.response.status >= 500 && err.response.status < 600))
      ) {
        setLitellmUnavailable(true);
      } else {
        toast.error(extractApiErrorMessage(err, 'Failed to load models'));
      }
    } finally {
      setLoading(false);
    }
  }, []);

  const loadProviders = useCallback(async () => {
    try {
      const response = await litellmApi.listProviders();
      setProviders(
        response.data.providers.map((p) => ({
          name: p.name ?? '',
          label: p.label ?? '',
          modelHint: p.modelHint ?? '',
        })),
      );
    } catch {
      toast.error('Failed to load providers');
    }
  }, []);

  const loadCredentials = useCallback(async () => {
    try {
      const response = await litellmApi.listCredentials();
      setCredentials(
        response.data.credentials.map((c) => ({
          credentialName: c.credentialName ?? '',
        })),
      );
    } catch {
      toast.error('Failed to load credentials');
    }
  }, []);

  useEffect(() => {
    loadModels();
    loadProviders();
    loadCredentials();
  }, [loadModels, loadProviders, loadCredentials]);

  const openCreateModal = () => {
    setModalMode('create');
    setEditingModel(null);
    setModalOpen(true);
  };

  const openEditModal = (model: LiteLlmModelInfoItemDto) => {
    setModalMode('edit');
    setEditingModel(model);
    setModalOpen(true);
  };

  const openDeleteDialog = (model: LiteLlmModelInfoItemDto) => {
    setDeletingModel(model);
    setDeleteDialogOpen(true);
  };

  const handleDelete = async () => {
    if (!deletingModel) return;
    setDeleting(true);
    try {
      await litellmApi.deleteModel(deletingModel.id);
      toast.success(`Model "${deletingModel.modelName}" deleted`);
      setDeleteDialogOpen(false);
      setDeletingModel(null);
      await loadModels();
    } catch (err: unknown) {
      toast.error(extractApiErrorMessage(err, 'Failed to delete model'));
    } finally {
      setDeleting(false);
    }
  };

  const handleTest = async (model: LiteLlmModelInfoItemDto) => {
    setTestStatus((prev) => ({
      ...prev,
      [model.modelName]: { loading: true },
    }));
    try {
      const response = await litellmApi.testModel({ model: model.modelName });
      const result = response.data;
      setTestStatus((prev) => ({
        ...prev,
        [model.modelName]: {
          loading: false,
          success: result.success,
          latencyMs: result.latencyMs,
          error: result.error,
        },
      }));
    } catch (err: unknown) {
      setTestStatus((prev) => ({
        ...prev,
        [model.modelName]: {
          loading: false,
          success: false,
          error: extractApiErrorMessage(err, 'Test failed'),
        },
      }));
    }
  };

  const capabilityBadges = (model: LiteLlmModelInfoItemDto) => {
    const caps: string[] = [];
    if (model.supportsToolCalling) caps.push('Tools');
    if (model.supportsStreaming) caps.push('Streaming');
    if (model.supportsReasoning) caps.push('Reasoning');
    return caps;
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <div>
          <Skeleton className="h-5 w-32 mb-2" />
          <Skeleton className="h-4 w-64" />
        </div>
        <div className="border border-border rounded-xl overflow-hidden">
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton
              key={i}
              className="h-10 rounded-none border-b border-border last:border-b-0"
            />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-base font-semibold">LLM Models</h2>
          <p className="text-sm text-muted-foreground mt-1">
            Manage LiteLLM model deployments. Add, configure, and test model
            connections.
          </p>
        </div>
        <Button onClick={openCreateModal} size="sm">
          <Plus className="w-4 h-4 mr-1" />
          Add Model
        </Button>
      </div>

      {litellmUnavailable && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription className="flex items-center justify-between">
            <span>
              LiteLLM service is unavailable. Model management requires a
              running LiteLLM instance.
            </span>
            <Button
              variant="outline"
              size="sm"
              onClick={loadModels}
              className="ml-4 shrink-0">
              <RefreshCw className="w-3.5 h-3.5 mr-1" />
              Retry
            </Button>
          </AlertDescription>
        </Alert>
      )}

      {!litellmUnavailable && models.length === 0 && (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <Database className="h-10 w-10 text-muted-foreground/40 mb-3" />
          <p className="text-sm text-muted-foreground">
            No models configured. Click &quot;Add Model&quot; to get started.
          </p>
        </div>
      )}

      {models.length > 0 && (
        <div className="border border-border rounded-xl overflow-hidden bg-card">
          {models.map((model) => {
            const status = testStatus[model.modelName];
            const caps = capabilityBadges(model);
            return (
              <div
                key={model.id}
                className="grid grid-cols-[1fr_1fr_auto_auto] items-center gap-x-3 px-3 py-1.5 border-b border-border last:border-b-0 hover:bg-muted/30 transition-colors group">
                {/* Model name + provider */}
                <div className="min-w-0">
                  <span className="text-sm font-medium truncate block">
                    {model.modelName}
                  </span>
                  <span className="text-xs text-muted-foreground truncate block">
                    {model.providerModel}
                    {model.apiBase ? ` · ${model.apiBase}` : ''}
                  </span>
                </div>

                {/* Capabilities */}
                <div className="flex gap-1 flex-wrap justify-end">
                  {caps.map((cap) => (
                    <Badge
                      key={cap}
                      variant="secondary"
                      className="text-[10px] px-1.5 py-0.5">
                      {cap}
                    </Badge>
                  ))}
                </div>

                {/* Test status */}
                <div className="w-16 text-right">
                  {status && !status.loading && (
                    <span className="text-xs">
                      {status.success ? (
                        <span className="text-green-600 flex items-center justify-end gap-0.5">
                          <Check className="w-3 h-3" />
                          {status.latencyMs}ms
                        </span>
                      ) : (
                        <span
                          className="text-destructive flex items-center justify-end gap-0.5"
                          title={status.error}>
                          <X className="w-3 h-3" />
                          Failed
                        </span>
                      )}
                    </span>
                  )}
                </div>

                {/* Actions — reveal on hover */}
                <div className="flex items-center gap-0.5 opacity-0 group-hover:opacity-100 transition-opacity">
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-6 w-6 p-0"
                        onClick={() => handleTest(model)}
                        disabled={status?.loading}>
                        {status?.loading ? (
                          <Loader2 className="w-3 h-3 animate-spin" />
                        ) : (
                          <Play className="w-3 h-3" />
                        )}
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>Test</TooltipContent>
                  </Tooltip>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-6 w-6 p-0"
                        onClick={() => openEditModal(model)}>
                        <Pencil className="w-3 h-3" />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>Edit</TooltipContent>
                  </Tooltip>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => openDeleteDialog(model)}
                        className="h-6 w-6 p-0 text-muted-foreground hover:text-destructive hover:bg-destructive/10"
                        aria-label="Delete model">
                        <Trash2 className="w-3.5 h-3.5" />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>Delete</TooltipContent>
                  </Tooltip>
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Model Form Dialog */}
      <ModelFormDialog
        open={modalOpen}
        onOpenChange={setModalOpen}
        mode={modalMode}
        editingModel={editingModel}
        providers={providers}
        credentials={credentials}
        onSaved={loadModels}
        onOpenCredentials={() => setCredentialsSheetOpen(true)}
      />

      {/* Credentials Sheet */}
      <CredentialsSheet
        open={credentialsSheetOpen}
        onOpenChange={setCredentialsSheetOpen}
        credentials={credentials}
        onCredentialsChanged={loadCredentials}
      />

      {/* Delete Confirmation */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Model</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete &quot;{deletingModel?.modelName}
              &quot;? This action cannot be undone. Any agents using this model
              will fail until reconfigured.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={deleting}>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              disabled={deleting}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
              {deleting && <Loader2 className="w-4 h-4 animate-spin mr-1" />}
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};
