import { Loader2 } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';

import { gitRepositoriesApi } from '../../../api';
import type { CreateRepositoryDto } from '../../../autogenerated';
import { extractApiErrorMessage } from '../../../utils/errors';

interface CreateRepositoryModalProps {
  open: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

export const CreateRepositoryModal = ({
  open,
  onClose,
  onSuccess,
}: CreateRepositoryModalProps) => {
  const [creating, setCreating] = useState(false);
  const [formValues, setFormValues] = useState<CreateRepositoryDto>({
    owner: '',
    repo: '',
    url: '',
    token: '',
  });

  const handleCreateRepository = async () => {
    if (!formValues.owner || !formValues.repo || !formValues.url) return;

    setCreating(true);
    try {
      await gitRepositoriesApi.createRepository(formValues);
      toast.success('Repository added successfully');
      setFormValues({ owner: '', repo: '', url: '', token: '' });
      onClose();
      onSuccess();
    } catch (e: unknown) {
      console.error('Error creating repository:', e);
      const errorMessage = extractApiErrorMessage(
        e,
        'Failed to add repository',
      );
      toast.error(errorMessage);
    } finally {
      setCreating(false);
    }
  };

  const handleCancel = () => {
    setFormValues({ owner: '', repo: '', url: '', token: '' });
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={(isOpen) => !isOpen && handleCancel()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Add Repository</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 py-2">
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1.5">
              <Label>
                Owner <span className="text-destructive">*</span>
              </Label>
              <Input
                placeholder="e.g., facebook"
                value={formValues.owner}
                onChange={(e) =>
                  setFormValues({ ...formValues, owner: e.target.value })
                }
              />
            </div>
            <div className="space-y-1.5">
              <Label>
                Repository Name <span className="text-destructive">*</span>
              </Label>
              <Input
                placeholder="e.g., react"
                value={formValues.repo}
                onChange={(e) =>
                  setFormValues({ ...formValues, repo: e.target.value })
                }
              />
            </div>
          </div>
          <div className="space-y-1.5">
            <Label>
              Repository URL <span className="text-destructive">*</span>
            </Label>
            <Input
              placeholder="https://github.com/facebook/react"
              value={formValues.url}
              onChange={(e) =>
                setFormValues({ ...formValues, url: e.target.value })
              }
            />
          </div>
          <div className="space-y-1.5">
            <Label>Personal Access Token (Optional)</Label>
            <Input
              type="password"
              placeholder="ghp_xxxxxxxxxxxxxxxxxxxx"
              value={formValues.token || ''}
              onChange={(e) =>
                setFormValues({ ...formValues, token: e.target.value })
              }
            />
          </div>
        </div>
        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={handleCancel}>
            Cancel
          </Button>
          <Button
            onClick={handleCreateRepository}
            disabled={
              !formValues.owner ||
              !formValues.repo ||
              !formValues.url ||
              creating
            }
            className="gap-1.5">
            {creating && <Loader2 className="w-3.5 h-3.5 animate-spin" />}
            Add Repository
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
