import { formatDistanceToNow } from 'date-fns';
import { GitBranch, Github, Loader2, RefreshCw, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';

import { gitRepositoriesApi } from '../../../api';
import type { GitRepositoryDto, RepoIndexDto } from '../../../autogenerated';
import { extractApiErrorMessage } from '../../../utils/errors';

interface RepoWithIndex extends GitRepositoryDto {
  index?: RepoIndexDto;
}

interface RepositoryCardProps {
  repo: RepoWithIndex;
  deleting: string | null;
  reindexing: string | null;
  onDelete: (id: string) => void;
  onReindexStart: (id: string) => void;
  onReindexEnd: () => void;
  onRefresh: (repositoryId: string) => void;
}

export const RepositoryCard = ({
  repo,
  deleting,
  reindexing,
  onDelete,
  onReindexStart,
  onReindexEnd,
  onRefresh,
}: RepositoryCardProps) => {
  const [confirmDeleteOpen, setConfirmDeleteOpen] = useState(false);

  const handleTriggerReindex = async (repositoryId: string) => {
    onReindexStart(repositoryId);
    try {
      await gitRepositoriesApi.triggerReindex({ repositoryId });
      toast.success('Reindex triggered successfully');
      onRefresh(repositoryId);
    } catch (e: unknown) {
      console.error('Error triggering reindex:', e);
      const errorMessage = extractApiErrorMessage(
        e,
        'Failed to trigger reindex',
      );
      toast.error(errorMessage);
    } finally {
      onReindexEnd();
    }
  };

  const confirmDeleteRepository = () => {
    setConfirmDeleteOpen(true);
  };

  const getIndexProgress = () => {
    if (!repo.index) return 0;

    const { status, indexedTokens, estimatedTokens } = repo.index;

    if (status === 'completed') return 100;
    if (status === 'pending') return 0;
    if (status === 'failed') return 0;

    if (
      status === 'in_progress' &&
      indexedTokens !== null &&
      indexedTokens !== undefined &&
      estimatedTokens !== null &&
      estimatedTokens !== undefined &&
      estimatedTokens > 0
    ) {
      return Math.round((indexedTokens / estimatedTokens) * 100);
    }

    return 0;
  };

  const getProgressLabel = () => {
    if (!repo.index) return 'Not indexed yet';

    const { status, indexedTokens, estimatedTokens } = repo.index;

    if (status === 'completed') {
      const tokens =
        indexedTokens !== null && indexedTokens !== undefined
          ? indexedTokens.toLocaleString()
          : '0';
      return `Indexed (${tokens} tokens)`;
    }
    if (status === 'in_progress') {
      const tokens =
        indexedTokens !== null &&
        indexedTokens !== undefined &&
        estimatedTokens !== null &&
        estimatedTokens !== undefined
          ? ` (${indexedTokens.toLocaleString()} / ~${estimatedTokens.toLocaleString()} tokens)`
          : '';
      return `Indexing...${tokens}`;
    }
    if (status === 'failed') return 'Indexing failed';
    if (status === 'pending') return 'Pending indexing';

    return 'Not indexed yet';
  };

  const getProgressColor = () => {
    if (!repo.index) return 'bg-muted';
    const { status } = repo.index;
    if (status === 'completed')
      return '[&>[data-slot=progress-indicator]]:bg-emerald-600';
    if (status === 'in_progress')
      return '[&>[data-slot=progress-indicator]]:bg-blue-600';
    if (status === 'failed')
      return '[&>[data-slot=progress-indicator]]:bg-red-600';
    return '';
  };

  const updatedAt = new Date(
    repo.updatedAt || repo.createdAt || new Date().toISOString(),
  );
  const progress = getIndexProgress();
  const progressLabel = getProgressLabel();

  return (
    <>
      <Card className="p-4 hover:shadow-md transition-shadow w-[clamp(280px,28vw,360px)]">
        <div className="flex justify-between items-start">
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2">
              <Github className="w-4 h-4 shrink-0" />
              <span className="text-lg font-medium text-foreground truncate">
                {repo.owner}/{repo.repo}
              </span>
            </div>
            <div className="flex items-center gap-2 flex-wrap mt-1">
              <span className="text-xs text-muted-foreground">
                {repo.provider}
              </span>
              {repo.defaultBranch && (
                <Badge
                  variant="outline"
                  className="gap-1 text-[11px] px-1.5 py-0">
                  <GitBranch className="w-3 h-3" />
                  {repo.defaultBranch}
                </Badge>
              )}
            </div>
          </div>
          <Button
            variant="ghost"
            size="sm"
            className="h-8 w-8 p-0 text-destructive hover:text-destructive"
            onClick={(event) => {
              event.stopPropagation();
              confirmDeleteRepository();
            }}
            disabled={deleting === repo.id}>
            {deleting === repo.id ? (
              <Loader2 className="w-4 h-4 animate-spin" />
            ) : (
              <Trash2 className="w-4 h-4" />
            )}
          </Button>
        </div>

        <div className="mb-4 mt-2">
          <a
            href={repo.url}
            target="_blank"
            rel="noopener noreferrer"
            onClick={(e) => e.stopPropagation()}
            className="text-sm text-primary hover:underline">
            {repo.url}
          </a>
          {repo.index?.lastIndexedCommit && (
            <p className="text-[11px] text-muted-foreground font-mono mt-1">
              sha: {repo.index.lastIndexedCommit}
            </p>
          )}
        </div>

        <div className="mb-3">
          <div className="flex justify-between items-center mb-1">
            <span className="text-xs text-muted-foreground">
              {progressLabel}
            </span>
            <Button
              variant="ghost"
              size="sm"
              className="h-6 w-6 p-0 text-muted-foreground"
              onClick={(event) => {
                event.stopPropagation();
                onRefresh(repo.id);
              }}>
              <RefreshCw className="w-3.5 h-3.5" />
            </Button>
          </div>
          <Progress value={progress} className={`h-3 ${getProgressColor()}`} />
        </div>

        {repo.index?.errorMessage && (
          <div className="p-2 bg-red-50 rounded text-xs text-red-700 mb-3">
            {repo.index.errorMessage}
          </div>
        )}

        <div className="flex items-center justify-between gap-3 mt-auto">
          <span className="text-[13px] text-muted-foreground">
            Updated {formatDistanceToNow(updatedAt, { addSuffix: true })}
          </span>
          <Button
            size="sm"
            className="gap-1.5"
            onClick={(event) => {
              event.stopPropagation();
              handleTriggerReindex(repo.id);
            }}
            disabled={
              reindexing === repo.id || repo.index?.status === 'in_progress'
            }>
            {reindexing === repo.id ? (
              <Loader2 className="w-3.5 h-3.5 animate-spin" />
            ) : (
              <RefreshCw className="w-3.5 h-3.5" />
            )}
            Reindex
          </Button>
        </div>
      </Card>

      {/* Delete Confirmation Dialog */}
      <Dialog open={confirmDeleteOpen} onOpenChange={setConfirmDeleteOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Delete repository</DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground py-2">
            Are you sure you want to delete this repository? This action cannot
            be undone.
          </p>
          <DialogFooter className="gap-2">
            <Button
              variant="outline"
              onClick={() => setConfirmDeleteOpen(false)}>
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={() => {
                setConfirmDeleteOpen(false);
                onDelete(repo.id);
              }}
              disabled={deleting === repo.id}>
              {deleting === repo.id && (
                <Loader2 className="w-4 h-4 animate-spin mr-1" />
              )}
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
};
