import { formatDistanceToNow } from 'date-fns';
import { createTwoFilesPatch } from 'diff';
import { Loader2 } from 'lucide-react';
import {
  type MutableRefObject,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';

import { graphRevisionsApi } from '../../../api';
import {
  type GraphDto,
  type GraphRevisionDto,
  GraphRevisionDtoStatusEnum,
} from '../../../autogenerated';
import { Badge } from '../../../components/ui/badge';
import { Button } from '../../../components/ui/button';
import type { UseGraphDraftStateReturn } from '../../../hooks/useGraphDraftState';
import type { GraphDiffState } from '../../../services/GraphStorageService';
import { extractApiErrorMessage } from '../../../utils/errors';
import { toastMessage } from '../../../utils/toastAdapter';
import {
  normalizeGraphDiffSnapshot,
  REVISION_FETCH_LIMIT,
  REVISION_STATUS_STYLES,
  sortRevisions,
} from '../utils/graphPageUtils';

const REVISION_STATUS_RANK: Record<GraphRevisionDtoStatusEnum, number> = {
  [GraphRevisionDtoStatusEnum.Pending]: 0,
  [GraphRevisionDtoStatusEnum.Applying]: 1,
  [GraphRevisionDtoStatusEnum.Applied]: 2,
  [GraphRevisionDtoStatusEnum.Failed]: 2,
};

interface UseGraphRevisionsOptions {
  graphId: string | undefined;
  graph: GraphDto | null;
  serverGraphState: GraphDiffState;
  draftState: {
    draftState: GraphDiffState;
  };
  draftStateRef: MutableRefObject<UseGraphDraftStateReturn>;
  saving: boolean;
  onRevisionComplete?: (revision: GraphRevisionDto) => void;
}

/**
 * Callback type for the confirm-reset flow. The parent component (details.tsx)
 * is expected to wire this to an AlertDialog / confirm pattern.
 */
export type ConfirmResetHandler = (onConfirm: () => void) => void;

export const useGraphRevisions = ({
  graphId,
  graph,
  serverGraphState,
  draftState,
  draftStateRef,
  saving,
  onRevisionComplete,
}: UseGraphRevisionsOptions) => {
  const message = toastMessage;
  // Store onRevisionComplete in a ref so the polling interval doesn't restart
  // when the callback identity changes.
  const onRevisionCompleteRef = useRef(onRevisionComplete);
  useEffect(() => {
    onRevisionCompleteRef.current = onRevisionComplete;
  }, [onRevisionComplete]);
  const [revisions, setRevisions] = useState<GraphRevisionDto[]>([]);
  const [revisionsLoading, setRevisionsLoading] = useState(false);
  const [revisionPopoverVisible, setRevisionPopoverVisible] = useState(false);
  const [revisionDiffRevision, setRevisionDiffRevision] =
    useState<GraphRevisionDto | null>(null);
  const [localDiffModalVisible, setLocalDiffModalVisible] = useState(false);
  const [confirmResetPending, setConfirmResetPending] = useState(false);

  const loadRevisions = useCallback(
    async (options?: { silent?: boolean }) => {
      if (!graphId) return;
      try {
        setRevisionsLoading(true);
        const response = await graphRevisionsApi.getGraphRevisions(
          graphId,
          undefined,
          REVISION_FETCH_LIMIT,
        );
        const revisionList = response.data || [];
        setRevisions(
          sortRevisions(revisionList).slice(0, REVISION_FETCH_LIMIT),
        );
      } catch (error) {
        console.error('Error loading graph revisions:', error);
        if (!options?.silent) {
          const errorMessage = extractApiErrorMessage(
            error,
            'Failed to load graph revisions',
          );
          message.error(errorMessage);
        }
      } finally {
        setRevisionsLoading(false);
      }
    },
    [graphId, message],
  );

  useEffect(() => {
    void loadRevisions({ silent: true });
  }, [loadRevisions]);

  const upsertRevision = useCallback((revision: GraphRevisionDto) => {
    setRevisions((prev) => {
      const next = prev.slice();
      const index = next.findIndex((item) => item.id === revision.id);
      if (index === -1) {
        next.push(revision);
      } else {
        const existing = next[index];
        const existingRank =
          REVISION_STATUS_RANK[existing.status as GraphRevisionDtoStatusEnum] ??
          0;
        const incomingRank =
          REVISION_STATUS_RANK[revision.status as GraphRevisionDtoStatusEnum] ??
          0;
        if (incomingRank >= existingRank) {
          next[index] = revision;
        }
      }
      return sortRevisions(next).slice(0, REVISION_FETCH_LIMIT);
    });
  }, []);

  // Derive a stable key for the active (Pending/Applying) revision.
  const activeRevKey = useMemo(() => {
    const activeRev = revisions.find(
      (r) =>
        r.status === GraphRevisionDtoStatusEnum.Pending ||
        r.status === GraphRevisionDtoStatusEnum.Applying,
    );
    return activeRev ? `${activeRev.id}:${activeRev.status}` : null;
  }, [revisions]);

  // Polling fallback for pending/applying revisions
  useEffect(() => {
    if (!graphId || !activeRevKey) return;

    const [revId] = activeRevKey.split(':');

    const poll = async () => {
      try {
        const response = await graphRevisionsApi.getGraphRevision(
          graphId,
          revId,
        );
        const updated = response.data;
        if (
          updated.status === GraphRevisionDtoStatusEnum.Applied ||
          updated.status === GraphRevisionDtoStatusEnum.Failed
        ) {
          upsertRevision(updated);
          onRevisionCompleteRef.current?.(updated);
        }
      } catch {
        // Silently ignore polling errors
      }
    };

    const POLL_INTERVAL_MS = 3000;
    const POLL_TIMEOUT_MS = 60000;

    const interval = setInterval(() => void poll(), POLL_INTERVAL_MS);
    const timeout = setTimeout(() => clearInterval(interval), POLL_TIMEOUT_MS);

    return () => {
      clearInterval(interval);
      clearTimeout(timeout);
    };
  }, [graphId, activeRevKey, upsertRevision]);

  const activeRevision = useMemo(() => {
    if (!revisions.length) return null;

    const applyingRevision = revisions.find(
      (revision) => revision.status === GraphRevisionDtoStatusEnum.Applying,
    );
    if (applyingRevision) return applyingRevision;

    const pendingRevision = revisions.find(
      (revision) => revision.status === GraphRevisionDtoStatusEnum.Pending,
    );
    if (pendingRevision) return pendingRevision;

    if (graph?.version) {
      const matchingApplied = revisions.find(
        (revision) =>
          revision.toVersion === graph.version &&
          revision.status === GraphRevisionDtoStatusEnum.Applied,
      );
      if (matchingApplied) return matchingApplied;
    }

    const appliedRevision = revisions.find(
      (revision) => revision.status === GraphRevisionDtoStatusEnum.Applied,
    );
    if (appliedRevision) return appliedRevision;

    return revisions[0];
  }, [revisions, graph?.version]);

  const lastFailedRevision = useMemo(() => {
    if (!revisions.length) return null;
    const latest = revisions[0];
    if (latest.status !== GraphRevisionDtoStatusEnum.Failed) return null;
    if (activeRevision && activeRevision.id === latest.id) return null;
    return latest;
  }, [revisions, activeRevision]);

  const isRevisionApplying = useMemo(
    () =>
      revisions.some(
        (revision) => revision.status === GraphRevisionDtoStatusEnum.Applying,
      ),
    [revisions],
  );

  const handleResetAllLocalChanges = useCallback(() => {
    if (saving || isRevisionApplying) return;
    setConfirmResetPending(true);
  }, [saving, isRevisionApplying]);

  const executeReset = useCallback(() => {
    draftStateRef.current.resetToServer();
    message.success('Local changes reset');
    setConfirmResetPending(false);
  }, [draftStateRef, message]);

  const cancelReset = useCallback(() => {
    setConfirmResetPending(false);
  }, []);

  const handleOpenLocalDiff = useCallback(() => {
    setLocalDiffModalVisible(true);
    setRevisionPopoverVisible(false);
  }, []);

  const handleCloseLocalDiff = useCallback(() => {
    setLocalDiffModalVisible(false);
  }, []);

  const unsavedChangesPopoverContent = useMemo(() => {
    return (
      <div className="flex flex-col gap-2">
        <span className="text-sm">You have unsaved changes.</span>
        <Button
          variant="link"
          size="sm"
          onClick={handleOpenLocalDiff}
          className="p-0 h-auto justify-start">
          View local changes
        </Button>
        <Button
          variant="destructive"
          size="sm"
          onClick={handleResetAllLocalChanges}
          disabled={saving || isRevisionApplying}>
          Reset all local changes
        </Button>
      </div>
    );
  }, [
    handleOpenLocalDiff,
    handleResetAllLocalChanges,
    saving,
    isRevisionApplying,
  ]);

  const displayedRevisionMeta: {
    label: string;
    color: string;
    pulse?: boolean;
  } | null = useMemo(() => {
    if (activeRevision) {
      const meta =
        REVISION_STATUS_STYLES[
          activeRevision.status as GraphRevisionDtoStatusEnum
        ] ?? null;

      if (
        activeRevision.status === GraphRevisionDtoStatusEnum.Applying &&
        meta
      ) {
        return { ...meta, label: `Applying` };
      }
      if (meta) {
        return meta;
      }
    }
    if (graph) {
      return {
        label: 'Applied',
        color: '#52c41a',
      };
    }
    return null;
  }, [activeRevision, graph]);

  const displayedVersion = useMemo(() => {
    if (activeRevision) {
      const isAppliedActive =
        activeRevision.status === GraphRevisionDtoStatusEnum.Applied;
      if (!isAppliedActive || activeRevision.toVersion !== graph?.version) {
        return activeRevision.toVersion;
      }
    }
    return graph?.version ?? '\u2014';
  }, [activeRevision, graph?.version]);

  const localDiffPatch = useMemo(() => {
    if (!graph) return '';
    const baseline = normalizeGraphDiffSnapshot(serverGraphState);
    const draft = normalizeGraphDiffSnapshot(draftState.draftState);
    const baselineJson = JSON.stringify(baseline, null, 2);
    const draftJson = JSON.stringify(draft, null, 2);
    if (baselineJson === draftJson) {
      return '';
    }
    const baseVersionLabel = serverGraphState.baseVersion ?? graph.version;
    const baseTitle = baseVersionLabel ? `v${baseVersionLabel}` : 'Server';
    return createTwoFilesPatch(
      baseTitle,
      'Local draft',
      baselineJson,
      draftJson,
      '',
      '',
      { context: 6 },
    ).trimEnd();
  }, [draftState.draftState, graph, serverGraphState]);

  const handleOpenRevisionDiff = useCallback((revision: GraphRevisionDto) => {
    setRevisionDiffRevision(revision);
    setRevisionPopoverVisible(false);
  }, []);

  const handleDownloadGraphBackup = useCallback(() => {
    if (!graph) {
      message.warning('Graph is not loaded yet');
      return;
    }

    try {
      const backupPayload = {
        exportedAt: new Date().toISOString(),
        graph,
        viewport: draftStateRef.current.draftState.viewport,
      };

      const blob = new Blob([JSON.stringify(backupPayload, null, 2)], {
        type: 'application/json',
      });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      const safeVersion = graph.version ? `v${graph.version}` : 'draft';
      link.href = url;
      link.download = `graph-${graph.id ?? 'graph'}-${safeVersion}.json`;
      document.body.appendChild(link);
      link.click();
      link.remove();
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Failed to export graph backup', error);
      message.error('Failed to download graph backup');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [graph, message]);

  const handleCloseRevisionDiff = useCallback(() => {
    setRevisionDiffRevision(null);
  }, []);

  const revisionDiffModalVisible = revisionDiffRevision !== null;

  const revisionDiffPreviousConfig = useMemo(() => {
    if (!revisionDiffRevision) return null;
    const prevRevision = revisions.find(
      (r) => r.toVersion === revisionDiffRevision.baseVersion,
    );
    return prevRevision?.newConfig ?? null;
  }, [revisionDiffRevision, revisions]);

  const revisionPopoverContent = useMemo(() => {
    if (revisionsLoading) {
      return (
        <div
          style={{
            minWidth: 280,
            minHeight: 80,
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
          }}>
          <Loader2 className="size-4 animate-spin" />
        </div>
      );
    }

    if (revisions.length === 0) {
      return (
        <div style={{ minWidth: 280 }}>
          <span className="text-xs text-muted-foreground">
            No revisions available yet.
          </span>
        </div>
      );
    }

    return (
      <div className="w-64 max-h-80 overflow-y-auto">
        {revisions.map((revision) => {
          const meta = REVISION_STATUS_STYLES[
            revision.status as GraphRevisionDtoStatusEnum
          ] ?? {
            label: revision.status,
            color: '#d9d9d9',
          };
          const timestamp = formatDistanceToNow(
            new Date(revision.updatedAt || revision.createdAt),
            { addSuffix: true },
          );

          return (
            <div
              key={revision.id}
              className="flex items-center justify-between px-3 py-2 rounded-md hover:bg-muted/50 transition-colors gap-3 cursor-default">
              <div className="flex flex-col gap-0.5 min-w-0">
                <span className="text-sm font-medium">
                  v{revision.toVersion}
                </span>
                <span className="text-xs text-muted-foreground">
                  {timestamp}
                </span>
                {revision.error && (
                  <span className="text-xs text-destructive">
                    {revision.error}
                  </span>
                )}
              </div>
              <div className="flex flex-col items-end gap-1 flex-shrink-0">
                <Badge
                  className="text-[11px] px-1.5 py-0 h-4 font-medium border-0 text-white"
                  style={{ backgroundColor: meta.color }}>
                  {meta.label}
                </Badge>
                <button
                  onClick={() => handleOpenRevisionDiff(revision)}
                  className="text-xs text-primary hover:underline leading-none">
                  View diff
                </button>
              </div>
            </div>
          );
        })}
      </div>
    );
  }, [revisionsLoading, revisions, handleOpenRevisionDiff]);

  return {
    revisionPopoverVisible,
    setRevisionPopoverVisible,
    revisionDiffRevision,
    revisionDiffPreviousConfig,
    localDiffModalVisible,
    loadRevisions,
    upsertRevision,
    isRevisionApplying,
    displayedVersion,
    displayedRevisionMeta,
    lastFailedRevision,
    localDiffPatch,
    handleCloseLocalDiff,
    unsavedChangesPopoverContent,
    revisionPopoverContent,
    handleDownloadGraphBackup,
    handleCloseRevisionDiff,
    revisionDiffModalVisible,
    confirmResetPending,
    executeReset,
    cancelReset,
  };
};
