import axios from 'axios';
import {
  BarChart3,
  Download,
  ExternalLink,
  GitBranch,
  Github,
  Loader2,
  MessageSquare,
  Network,
  PanelLeftClose,
  PanelLeftOpen,
  Plus,
  ScanSearch,
  Server,
  Upload,
  X,
} from 'lucide-react';
import { type ChangeEvent, useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router';
import { useParams } from 'react-router';

import { type ThreadDto, ThreadDtoStatusEnum } from '../../autogenerated';
import { Avatar, AvatarFallback } from '../../components/ui/avatar';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import {
  Popover,
  PopoverAnchor,
  PopoverContent,
  PopoverTrigger,
} from '../../components/ui/popover';
import { Tabs, TabsList, TabsTrigger } from '../../components/ui/tabs';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '../../components/ui/tooltip';
import { API_URL } from '../../config';
import { useLocalStorage } from '../../hooks/useLocalStorage';
import {
  getStatusBadgeClass,
  getThreadStatusDisplay,
} from '../../utils/threadStatus';
import { toastMessage } from '../../utils/toastAdapter';
import { AnalyzeThreadModal } from './components/AnalyzeThreadModal';
import { GraphPickerContent } from './components/GraphPickerPopover';
import { SocketEventsModal } from './components/SocketEventsModal';
import ThreadChatPanel from './components/ThreadChatPanel';
import { ThreadListItem } from './components/ThreadListItem';
import { ThreadRuntimeSidebar } from './components/ThreadRuntimeSidebar';
import {
  type ThreadExportData,
  ThreadSnapshotModal,
} from './components/ThreadSnapshotModal';
import { ThreadTokenUsageLine } from './components/ThreadTokenUsageLine';
import { UsageStatsModal } from './components/UsageStatsModal';
import { useChatsAnalysis } from './hooks/useChatsAnalysis';
import { useChatsMessages } from './hooks/useChatsMessages';
import { useChatsThreadList } from './hooks/useChatsThreadList';
import { useChatsUsageStats } from './hooks/useChatsUsageStats';
import { useChatsWebSocket } from './hooks/useChatsWebSocket';
import { useFullGraphCache } from './hooks/useFullGraphCache';
import { useThreadRuntimes } from './hooks/useThreadRuntimes';
import {
  formatUsd,
  getAgentColor,
  getAgentInitials,
  isDraftThreadId,
  parseAgentLabel,
} from './utils/chatsPageUtils';

export const ChatsPage = () => {
  const { projectId } = useParams<{ projectId: string }>();

  // --- Messages hook ---
  const {
    messages,
    updateMessages,
    pendingMessages,
    updatePendingMessages,
    externalThreadIds,
    setExternalThreadIds,
    messageMeta,
    setMessageMeta,
    getMessageMeta,
    updateMessageMeta,
    loadMessagesForThread,
    loadMoreMessagesForThread,
  } = useChatsMessages({ toastMessage });

  // --- Thread list hook ---
  const threadList = useChatsThreadList({
    toastMessage,
  });
  const {
    threads,
    setThreads,
    threadsLoading,
    threadsLoadingMore,
    threadStatusTab,
    selectedThreadId,
    setSelectedThreadId,
    setSelectedThreadShadow,
    selectedAgentNodeId,

    draftThread,
    setDraftThread,
    graphCache,
    setGraphCache,
    templatesLoading,
    triggerNodesForSelectedThread,
    graphPickerOpen,
    setGraphPickerOpen,
    graphPickerLoading,
    graphPickerError,
    graphPickerGraphs,
    threadsContainerRef,
    pendingThreadSelectionRef,
    threadsRef,
    graphFilterId,
    graphIsRunning,
    selectedThreadIsDraft,
    selectedThread,
    filteredThreads,
    shouldShowDraftThread,
    filteredGraphLabel,
    getThreadTimestamp,
    sortThreadsByTimestampDesc,
    ensureGraphsLoaded,
    handleThreadsScroll,
    handleThreadStatusTabChange,
    handleClearGraphFilter,
    handleDeleteThread,
    handleCreateDraftThread,
    handleGraphPickerSelect,
    handleThreadChatSwitchRequest,
  } = threadList;

  // --- Full graph cache ---
  const { getFullGraph } = useFullGraphCache({
    selectedThread,
    selectedThreadIsDraft,
  });

  // --- Usage stats hook ---
  const {
    setThreadTokenUsageByNode,
    selectedThreadUsageByNode,

    selectedThreadContextMaxTokens,
    selectedThreadHeaderUsage,
    selectedThreadHeaderContextPercent,
    selectedThreadHeaderContextMaxTokens,
    handleOpenUsageStatsModal,
    handleCloseUsageStatsModal,
    invalidateThreadUsageStats,
    usageStatsModalOpen,
    usageStatsModalThreadId,
    threadUsageStats,
    threadUsageStatsLoading,
  } = useChatsUsageStats({
    toastMessage,
    selectedThread,
    selectedThreadId,
    selectedThreadIsDraft,
    selectedAgentNodeId,
    graphCache,
    getFullGraph,
  });

  // --- WebSocket hook ---
  const { applyThreadCreate, threadSocketEvents } = useChatsWebSocket({
    graphFilterId,
    selectedThreadId,
    draftThread,
    threadsRef,
    pendingThreadSelectionRef,
    setThreads,
    setSelectedThreadId,
    setSelectedThreadShadow,
    setDraftThread,
    setExternalThreadIds,
    setMessageMeta,
    setThreadTokenUsageByNode,
    messages,
    pendingMessages,
    updateMessages,
    updatePendingMessages,
    externalThreadIds,
    sortThreadsByTimestampDesc,
    getThreadTimestamp,
    ensureGraphsLoaded,
    graphCache,
    setGraphCache,
    invalidateThreadUsageStats,
  });

  const socketEventsForUsageStatsThread = useMemo(() => {
    if (!usageStatsModalThreadId) return [];
    return threadSocketEvents[usageStatsModalThreadId] ?? [];
  }, [threadSocketEvents, usageStatsModalThreadId]);

  // --- Analysis hook ---
  const analysis = useChatsAnalysis({
    toastMessage,
    selectedThread,
    selectedThreadId,
    selectedThreadIsDraft,
    graphIsRunning,
    threadSocketEvents,
  });

  const {
    analyzeModalOpen,
    analyzeLoading,
    analysisResult,
    analysisUserInput,
    setAnalysisUserInput,
    analysisModel,
    setAnalysisModel,
    liteLlmModels,
    litellmModelsLoading,
    analysisButtonDisabled,
    handleOpenAnalyzeModal,
    handleCloseAnalyzeModal,
    handleAnalyzeThread,
    threadSocketEventsModalOpen,
    socketEventsForModalThread,
    handleOpenThreadSocketEventsModal,
    handleCloseThreadSocketEventsModal,
    handleCopyThreadSocketEventsJson,
    threadSocketEventsModalThreadId,
  } = analysis;

  // --- Thread list collapse ---
  const [threadListCollapsed, setThreadListCollapsed] =
    useLocalStorage<boolean>('geniro:chats-thread-list-collapsed', false);

  // --- Thread export/import ---
  const [snapshotModalOpen, setSnapshotModalOpen] = useState(false);
  const [snapshotModalData, setSnapshotModalData] =
    useState<ThreadExportData | null>(null);
  const importFileInputRef = useRef<HTMLInputElement>(null);

  const handleExportThread = async (threadId: string, threadName: string) => {
    try {
      const response = await axios.get<Blob>(
        `${API_URL}/api/v1/threads/${threadId}/export`,
        { responseType: 'blob' },
      );
      const date = new Date().toISOString().slice(0, 10);
      const safeName = (threadName || 'thread').replace(/[^a-z0-9-_]/gi, '_');
      const filename = `thread-export-${safeName}-${date}.json`;
      const url = URL.createObjectURL(response.data);
      const anchor = document.createElement('a');
      anchor.href = url;
      anchor.download = filename;
      anchor.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error('[ChatsPage] Failed to export thread', { threadId, err });
      toastMessage.error('Failed to export thread. Please try again.');
    }
  };

  const handleImportFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    // Reset the input immediately so the same file can be re-selected
    e.target.value = '';
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (event) => {
      const text = event.target?.result;
      if (typeof text !== 'string') {
        toastMessage.error('Failed to read the selected file.');
        return;
      }
      let parsed: unknown;
      try {
        parsed = JSON.parse(text);
      } catch {
        toastMessage.error(
          'Invalid JSON file. Please select a valid thread export.',
        );
        return;
      }
      const p = parsed as Record<string, unknown>;
      if (
        !p ||
        typeof p !== 'object' ||
        p['version'] !== '1' ||
        typeof p['thread'] !== 'object' ||
        p['thread'] === null ||
        !Array.isArray(p['messages'])
      ) {
        toastMessage.error(
          'Invalid thread snapshot file: missing or invalid required fields.',
        );
        return;
      }
      setSnapshotModalData(parsed as ThreadExportData);
      setSnapshotModalOpen(true);
    };
    reader.readAsText(file);
  };

  // --- Runtime sidebar ---
  const [runtimeSidebarOpen, setRuntimeSidebarOpen] = useState(false);

  const runtimeNodeNames = useMemo(() => {
    if (!selectedThread || selectedThreadIsDraft) return undefined;
    const entry = graphCache[selectedThread.graphId];
    if (!entry) return undefined;
    const displayNames = entry.nodeDisplayNames ?? {};
    // Use nodeDisplayNames from the preview as the source of truth
    const names: Record<string, string> = {};
    for (const [nodeId, name] of Object.entries(displayNames)) {
      names[nodeId] = name;
    }
    // Also add agent names from the agents array
    for (const agent of entry.graph.agents ?? []) {
      if (!names[agent.nodeId]) {
        names[agent.nodeId] = agent.name;
      }
    }
    return names;
  }, [graphCache, selectedThread, selectedThreadIsDraft]);

  const {
    runtimes,
    loading: runtimesLoading,
    error: runtimesError,
    refresh: refreshRuntimes,
  } = useThreadRuntimes(
    selectedThreadId && !selectedThreadIsDraft ? selectedThreadId : undefined,
    selectedThread && !selectedThreadIsDraft
      ? selectedThread.graphId
      : undefined,
    runtimeSidebarOpen,
  );

  // --- Auto-load messages for selected thread ---

  const messagesRef = useRef(messages);
  useEffect(() => {
    messagesRef.current = messages;
  }, [messages]);

  useEffect(() => {
    if (
      !selectedThread ||
      ('isDraft' in selectedThread && selectedThread.isDraft)
    )
      return;

    const meta = getMessageMeta(selectedThread.id);
    const existingMessages =
      messagesRef.current[selectedThread.id]?.['all'] ?? [];

    if (existingMessages.length > 0) {
      if (meta.offset === 0) {
        updateMessageMeta(selectedThread.id, (prev) => ({
          ...prev,
          loading: false,
          loadingMore: false,
          offset: existingMessages.length,
        }));
      }
      return;
    }

    if (meta.initialLoadFailed) {
      return;
    }

    if (meta.offset === 0 && !meta.loading) {
      void loadMessagesForThread(selectedThread.id);
    }
  }, [
    selectedThread,
    getMessageMeta,
    loadMessagesForThread,
    updateMessageMeta,
  ]);

  // --- Derived thread data ---

  const threadStatusMeta = selectedThread
    ? 'isDraft' in selectedThread && selectedThread.isDraft
      ? null
      : getThreadStatusDisplay((selectedThread as ThreadDto).status)
    : null;

  const selectedThreadAllMessages = useMemo(() => {
    if (!selectedThreadId) return [];
    return messages[selectedThreadId]?.['all'] || [];
  }, [messages, selectedThreadId]);

  const agentsForSelectedThread = useMemo(() => {
    if (!selectedThreadId || !selectedThread || selectedThreadIsDraft) {
      return [];
    }

    // Use thread.agents from API when available
    const apiAgents = (selectedThread as ThreadDto).agents;
    if (apiAgents && apiAgents.length > 0) {
      return apiAgents.map((a) => ({
        nodeId: a.nodeId,
        label: a.name,
        description: a.description,
      }));
    }

    // Fallback to graph preview agents
    const graphId = selectedThread.graphId;
    const graph = graphCache[graphId]?.graph;
    if (!graph) return [];

    return (graph.agents ?? []).map((agent) => ({
      nodeId: agent.nodeId,
      label: agent.name,
      description: agent.description,
    }));
  }, [graphCache, selectedThread, selectedThreadId, selectedThreadIsDraft]);

  // Agents by graphId — used to show avatars in every thread list item
  const agentsByGraphId = useMemo(() => {
    const result: Record<string, { nodeId: string; label: string }[]> = {};

    for (const t of [
      ...filteredThreads,
      ...(draftThread ? [draftThread] : []),
    ]) {
      // Draft threads don't have agents from API
      if ('isDraft' in t && t.isDraft) continue;
      const apiAgents = (t as ThreadDto).agents;
      if (!apiAgents || result[t.graphId]) continue;
      result[t.graphId] = apiAgents.map((a) => ({
        nodeId: a.nodeId,
        label: a.name,
      }));
    }

    // Fallback to graph preview agents for graphIds not covered by thread.agents
    const graphIds = new Set<string>();
    for (const t of filteredThreads) graphIds.add(t.graphId);
    if (draftThread) graphIds.add(draftThread.graphId);

    for (const gId of graphIds) {
      if (result[gId]) continue;
      const cached = graphCache[gId];
      if (!cached) continue;
      result[gId] = (cached.graph.agents ?? []).map((agent) => ({
        nodeId: agent.nodeId,
        label: agent.name,
      }));
    }
    return result;
  }, [filteredThreads, draftThread, graphCache]);

  const runtimeAgentNames = useMemo(() => {
    if (!selectedThread || selectedThreadIsDraft) return {};

    const fullGraph = getFullGraph(selectedThread.graphId);

    // With full schema, build edge-based ancestry to find which agent owns each node
    if (fullGraph?.schema?.edges && fullGraph.schema.edges.length > 0) {
      const { nodes, edges } = fullGraph.schema;

      // Build adjacency: child -> parents
      const parentMap = new Map<string, Set<string>>();
      for (const edge of edges) {
        let parents = parentMap.get(edge.to);
        if (!parents) {
          parents = new Set();
          parentMap.set(edge.to, parents);
        }
        parents.add(edge.from);
      }

      // Identify agent node IDs
      const agentNodeIds = new Set(
        nodes.filter((n) => n.template === 'simple-agent').map((n) => n.id),
      );

      // Build a name lookup from schema config
      const agentNameByNodeId = new Map<string, string>();
      for (const node of nodes) {
        if (agentNodeIds.has(node.id)) {
          const name =
            typeof node.config?.name === 'string' && node.config.name.trim()
              ? node.config.name.trim()
              : node.id;
          agentNameByNodeId.set(node.id, name);
        }
      }

      // For each node, BFS upward to find its closest agent ancestor
      const result: Record<string, string> = {};
      for (const node of nodes) {
        if (agentNodeIds.has(node.id)) {
          result[node.id] = agentNameByNodeId.get(node.id) ?? node.id;
          continue;
        }
        const visited = new Set<string>();
        const queue = [node.id];
        let foundAgent: string | undefined;
        while (queue.length > 0 && !foundAgent) {
          const current = queue.shift()!;
          if (visited.has(current)) continue;
          visited.add(current);
          const parents = parentMap.get(current);
          if (!parents) continue;
          for (const parentId of parents) {
            if (agentNodeIds.has(parentId)) {
              foundAgent = agentNameByNodeId.get(parentId) ?? parentId;
              break;
            }
            queue.push(parentId);
          }
        }
        if (foundAgent) {
          result[node.id] = foundAgent;
        }
      }
      return result;
    }

    // Fallback: without full schema, map each agent nodeId to its own name
    const result: Record<string, string> = {};
    for (const agent of agentsForSelectedThread) {
      result[agent.nodeId] = agent.label;
    }
    return result;
  }, [
    selectedThread,
    selectedThreadIsDraft,
    getFullGraph,
    agentsForSelectedThread,
  ]);

  const visibleMessagesForSelectedThread = useMemo(() => {
    if (!selectedThreadId) return [];
    if (!selectedAgentNodeId) return selectedThreadAllMessages;
    return selectedThreadAllMessages.filter(
      (msg) => msg.nodeId === selectedAgentNodeId,
    );
  }, [selectedAgentNodeId, selectedThreadAllMessages, selectedThreadId]);

  const visiblePendingMessagesForSelectedThread = useMemo(() => {
    if (!selectedThreadId) return [];
    if (selectedAgentNodeId) return [];
    return pendingMessages[selectedThreadId]?.['all'] || [];
  }, [pendingMessages, selectedAgentNodeId, selectedThreadId]);

  // --- Empty state ---

  const threadsEmpty =
    !threadsLoading &&
    !threadsLoadingMore &&
    filteredThreads.length === 0 &&
    !shouldShowDraftThread;

  const threadsEmptyDescription = useMemo(() => {
    const scopeSuffix = graphFilterId ? ' for this graph' : '';
    if (threadStatusTab === 'resolved')
      return `No resolved threads${scopeSuffix}`;
    if (threadStatusTab === 'open') return `No open threads${scopeSuffix}`;
    return graphFilterId ? 'No threads found for this graph' : 'No threads yet';
  }, [graphFilterId, threadStatusTab]);

  // --- Render ---

  return (
    <div className="h-full flex flex-col overflow-hidden">
      <div className="flex flex-1 min-h-0 overflow-hidden">
        {/* Left sidebar: thread list */}
        {threadListCollapsed ? (
          <div className="w-10 bg-card border-r border-border flex flex-col items-center py-2 gap-0.5 flex-shrink-0">
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-7 w-7 mb-1"
                  onClick={() => setThreadListCollapsed(false)}>
                  <PanelLeftOpen className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent side="right">Expand thread list</TooltipContent>
            </Tooltip>
            <div className="flex flex-col items-center gap-0.5 overflow-y-auto w-full px-1 min-h-0">
              {shouldShowDraftThread && draftThread && (
                <Tooltip>
                  <TooltipTrigger asChild>
                    <button
                      onClick={() => setSelectedThreadId(draftThread.id)}
                      className={[
                        'w-7 h-7 rounded-md flex items-center justify-center text-[10px] font-semibold transition-colors flex-shrink-0',
                        draftThread.id === selectedThreadId
                          ? 'bg-primary text-primary-foreground'
                          : 'bg-muted text-muted-foreground hover:bg-muted/80',
                      ].join(' ')}>
                      {(draftThread.name || 'N').charAt(0).toUpperCase()}
                    </button>
                  </TooltipTrigger>
                  <TooltipContent side="right">
                    {draftThread.name || 'New Thread'}
                  </TooltipContent>
                </Tooltip>
              )}
              {filteredThreads.map((thread) => (
                <Tooltip key={thread.id}>
                  <TooltipTrigger asChild>
                    <button
                      onClick={() => setSelectedThreadId(thread.id)}
                      className={[
                        'w-7 h-7 rounded-md flex items-center justify-center text-[10px] font-semibold transition-colors flex-shrink-0',
                        thread.id === selectedThreadId
                          ? 'bg-primary text-primary-foreground'
                          : 'bg-muted text-muted-foreground hover:bg-muted/80',
                      ].join(' ')}>
                      {(thread.name || 'T').charAt(0).toUpperCase()}
                    </button>
                  </TooltipTrigger>
                  <TooltipContent side="right">
                    {thread.name || 'Thread'}
                  </TooltipContent>
                </Tooltip>
              ))}
            </div>
          </div>
        ) : (
          <aside className="w-72 bg-card border-r border-border flex flex-col overflow-hidden flex-shrink-0">
            {/* Header */}
            {graphFilterId ? (
              <div className="px-4 py-3 border-b border-border flex items-center justify-between shrink-0">
                <span className="text-sm font-semibold text-foreground">
                  Chats
                </span>
                <div className="flex items-center gap-1">
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-7 w-7"
                    onClick={handleCreateDraftThread}>
                    <Plus className="w-3.5 h-3.5" />
                  </Button>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-7 w-7"
                        onClick={() => setThreadListCollapsed(true)}>
                        <PanelLeftClose className="h-3.5 w-3.5" />
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>Collapse thread list</TooltipContent>
                  </Tooltip>
                </div>
              </div>
            ) : (
              <Popover open={graphPickerOpen} onOpenChange={setGraphPickerOpen}>
                <PopoverAnchor asChild>
                  <div className="px-4 py-3 border-b border-border flex items-center justify-between shrink-0">
                    <span className="text-sm font-semibold text-foreground">
                      Chats
                    </span>
                    <div className="flex items-center gap-1">
                      <PopoverTrigger asChild>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-7 w-7"
                          onClick={handleCreateDraftThread}>
                          <Plus className="w-3.5 h-3.5" />
                        </Button>
                      </PopoverTrigger>
                      <Tooltip>
                        <TooltipTrigger asChild>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-7 w-7"
                            onClick={() => setThreadListCollapsed(true)}>
                            <PanelLeftClose className="h-3.5 w-3.5" />
                          </Button>
                        </TooltipTrigger>
                        <TooltipContent>Collapse thread list</TooltipContent>
                      </Tooltip>
                    </div>
                  </div>
                </PopoverAnchor>
                <PopoverContent
                  align="center"
                  className="w-[calc(18rem-1rem)] p-1">
                  <GraphPickerContent
                    graphs={graphPickerGraphs}
                    loading={graphPickerLoading}
                    error={graphPickerError}
                    onSelect={handleGraphPickerSelect}
                  />
                </PopoverContent>
              </Popover>
            )}

            {/* Filter tabs */}
            <div className="px-3 py-2 border-b border-border shrink-0">
              <Tabs
                value={threadStatusTab}
                onValueChange={handleThreadStatusTabChange}
                className="w-full">
                <TabsList className="w-full h-7 grid grid-cols-3 p-0.5">
                  <TabsTrigger value="all" className="text-xs h-6">
                    All
                  </TabsTrigger>
                  <TabsTrigger value="open" className="text-xs h-6">
                    Open
                  </TabsTrigger>
                  <TabsTrigger value="resolved" className="text-xs h-6">
                    Resolved
                  </TabsTrigger>
                </TabsList>
              </Tabs>
            </div>
            {graphFilterId && (
              <div className="px-3 py-2 border-b border-border shrink-0">
                <div className="flex items-center gap-2 min-w-0">
                  <Badge
                    variant="secondary"
                    className="gap-1.5 pl-1.5 pr-1 py-0.5 min-w-0 max-w-full"
                    title={filteredGraphLabel}>
                    <Network className="w-3 h-3 shrink-0" />
                    <span className="truncate">{filteredGraphLabel}</span>
                    <button
                      type="button"
                      className="ml-0.5 rounded-sm hover:bg-muted-foreground/20 p-0.5 shrink-0 transition-colors"
                      onClick={handleClearGraphFilter}
                      aria-label="Clear graph filter">
                      <X className="h-3 w-3" />
                    </button>
                  </Badge>
                </div>
              </div>
            )}
            <div
              ref={threadsContainerRef}
              onScroll={handleThreadsScroll}
              className="flex-1 min-h-0 overflow-y-auto py-1">
              {shouldShowDraftThread && draftThread ? (
                <ThreadListItem
                  thread={draftThread}
                  isActive={draftThread.id === selectedThreadId}
                  graphCache={graphCache}
                  onSelect={setSelectedThreadId}
                  onDeleteThread={handleDeleteThread}
                  agents={[]}
                />
              ) : null}
              {filteredThreads.map((thread) => (
                <ThreadListItem
                  key={thread.id}
                  thread={thread}
                  isActive={thread.id === selectedThreadId}
                  graphCache={graphCache}
                  onSelect={setSelectedThreadId}
                  onDeleteThread={handleDeleteThread}
                  agents={
                    thread.id === selectedThreadId
                      ? agentsForSelectedThread
                      : (agentsByGraphId[thread.graphId] ?? [])
                  }
                />
              ))}
              {threadsLoading && (
                <div className="py-6 text-center">
                  <Loader2 className="h-5 w-5 animate-spin mx-auto text-muted-foreground" />
                </div>
              )}
              {threadsEmpty && (
                <div className="py-10 px-4">
                  <div className="flex flex-col items-center justify-center text-center">
                    <MessageSquare className="w-10 h-10 text-muted-foreground/30 mb-3" />
                    <p className="text-sm font-medium text-muted-foreground mb-1">
                      {threadsEmptyDescription}
                    </p>
                    <p className="text-xs text-muted-foreground/70">
                      Start a new chat to begin a conversation
                    </p>
                  </div>
                </div>
              )}
              {threadsLoadingMore && (
                <div className="py-3 text-center">
                  <Loader2 className="h-4 w-4 animate-spin mx-auto text-muted-foreground" />
                </div>
              )}
            </div>
            {/* Footer */}
            <div className="px-4 py-2.5 border-t border-border shrink-0">
              <Button
                variant="ghost"
                size="sm"
                className="w-full justify-start text-xs text-muted-foreground h-7 px-2"
                onClick={() => importFileInputRef.current?.click()}>
                <Upload className="h-3.5 w-3.5 mr-1.5" />
                Import thread snapshot
              </Button>
            </div>
          </aside>
        )}

        {/* Right panel: chat + runtime sidebar */}
        <div className="flex-1 min-h-0 flex overflow-hidden">
          <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
            <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
              {selectedThread ? (
                <>
                  {/* Chat Header */}
                  <div className="px-5 py-2.5 border-b border-border bg-card flex-shrink-0">
                    {/* Two-column: left (title+repo+agents) / right (buttons above, token usage below) */}
                    <div className="flex items-start gap-4">
                      {/* Left */}
                      <div className="flex-1 min-w-0">
                        {/* Title row */}
                        <div className="flex items-center gap-2 min-w-0">
                          <h2 className="text-sm font-semibold m-0 truncate">
                            {selectedThread.name || 'New Thread'}
                          </h2>
                          {threadStatusMeta && (
                            <Badge
                              className={`text-[10px] px-1.5 py-0 h-4 font-medium flex-shrink-0 ${getStatusBadgeClass((selectedThread as ThreadDto).status)}`}>
                              {threadStatusMeta.label}
                            </Badge>
                          )}
                          <span className="text-border">|</span>
                          <Link
                            to={
                              projectId
                                ? `/projects/${projectId}/graphs/${selectedThread.graphId}`
                                : `/graphs/${selectedThread.graphId}`
                            }
                            className="text-xs text-muted-foreground hover:text-foreground hover:underline transition-colors inline-flex items-center gap-1 flex-shrink-0">
                            <Network className="w-3 h-3" />
                            {graphCache[selectedThread.graphId]?.graph.name ||
                              'Loading\u2026'}
                            <ExternalLink className="h-3 w-3" />
                          </Link>
                          {!selectedThreadIsDraft &&
                            (selectedThread as ThreadDto).metadata
                              ?.repositoryOwner && (
                              <>
                                <span className="text-border">|</span>
                                <span className="inline-flex items-center gap-1 text-xs text-muted-foreground flex-shrink-0">
                                  <Github className="w-3 h-3" />
                                  {
                                    (selectedThread as ThreadDto).metadata
                                      ?.repositoryOwner
                                  }
                                  /
                                  {
                                    (selectedThread as ThreadDto).metadata
                                      ?.repositoryName
                                  }
                                </span>
                              </>
                            )}
                          {!selectedThreadIsDraft &&
                            (selectedThread as ThreadDto).metadata?.branch && (
                              <>
                                <span className="text-border">|</span>
                                <span className="inline-flex items-center gap-1 text-xs text-muted-foreground flex-shrink-0">
                                  <GitBranch className="w-3 h-3" />
                                  {
                                    (selectedThread as ThreadDto).metadata
                                      ?.branch
                                  }
                                </span>
                              </>
                            )}
                        </div>
                        {/* Agent chips */}
                        {agentsForSelectedThread.length > 0 && (
                          <div className="flex items-center gap-1.5 mt-1 flex-wrap">
                            {agentsForSelectedThread.map((agent) => {
                              const usage =
                                selectedThreadUsageByNode?.[agent.nodeId];
                              const pct =
                                usage?.currentContext &&
                                selectedThreadContextMaxTokens
                                  ? Math.round(
                                      (usage.currentContext /
                                        selectedThreadContextMaxTokens) *
                                        100,
                                    )
                                  : 0;
                              const parsed = parseAgentLabel(agent.label);
                              const displayRole =
                                parsed.role ?? agent.description;
                              return (
                                <Popover key={agent.nodeId}>
                                  <PopoverTrigger asChild>
                                    <button
                                      type="button"
                                      className="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-muted/60 hover:bg-muted transition-colors focus:outline-none">
                                      <Avatar className="w-4 h-4 shrink-0">
                                        <AvatarFallback
                                          className={`${getAgentColor(agent.nodeId)} text-white text-[8px]`}>
                                          {getAgentInitials(agent.label)}
                                        </AvatarFallback>
                                      </Avatar>
                                      <span className="text-[11px] text-foreground font-medium max-w-[80px] truncate">
                                        {parsed.name}
                                      </span>
                                      {pct > 0 && (
                                        <svg
                                          width="14"
                                          height="14"
                                          viewBox="0 0 14 14"
                                          className="shrink-0">
                                          <circle
                                            cx="7"
                                            cy="7"
                                            r="5"
                                            fill="none"
                                            stroke="currentColor"
                                            strokeWidth="2"
                                            className="text-muted-foreground/20"
                                          />
                                          <circle
                                            cx="7"
                                            cy="7"
                                            r="5"
                                            fill="none"
                                            stroke="currentColor"
                                            strokeWidth="2"
                                            strokeDasharray={`${(pct / 100) * 31.4} 31.4`}
                                            strokeLinecap="round"
                                            transform="rotate(-90 7 7)"
                                            className="text-primary"
                                          />
                                        </svg>
                                      )}
                                    </button>
                                  </PopoverTrigger>
                                  <PopoverContent
                                    className="w-60 p-3 text-xs space-y-1.5"
                                    align="start">
                                    <div className="font-semibold text-foreground mb-2">
                                      {parsed.name}
                                      {displayRole && (
                                        <span className="font-normal text-muted-foreground ml-1">
                                          ({displayRole})
                                        </span>
                                      )}
                                    </div>
                                    {usage && (
                                      <div className="space-y-1">
                                        {(
                                          [
                                            [
                                              'Input tokens',
                                              usage.inputTokens?.toLocaleString() ??
                                                '\u2014',
                                            ],
                                            [
                                              'Cached input',
                                              usage.cachedInputTokens?.toLocaleString() ??
                                                '\u2014',
                                            ],
                                            [
                                              'Output tokens',
                                              usage.outputTokens?.toLocaleString() ??
                                                '\u2014',
                                            ],
                                            [
                                              'Total tokens',
                                              usage.totalTokens?.toLocaleString() ??
                                                '\u2014',
                                            ],
                                            [
                                              'Total cost',
                                              formatUsd(usage.totalPrice),
                                            ],
                                            ['Context usage', `${pct}%`],
                                          ] as [string, string][]
                                        ).map(([label, val]) => (
                                          <div
                                            key={label}
                                            className="flex justify-between text-muted-foreground">
                                            <span>{label}</span>
                                            <span className="text-foreground font-medium">
                                              {val}
                                            </span>
                                          </div>
                                        ))}
                                      </div>
                                    )}
                                  </PopoverContent>
                                </Popover>
                              );
                            })}
                          </div>
                        )}
                      </div>
                      {/* Right: buttons on top, token usage below */}
                      <div className="flex flex-col items-end gap-1 flex-shrink-0">
                        <div className="flex items-center gap-1.5">
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-7 w-7"
                                onClick={handleOpenAnalyzeModal}
                                disabled={analysisButtonDisabled}>
                                <ScanSearch className="h-3.5 w-3.5" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                              {selectedThreadIsDraft
                                ? 'Create the thread before analyzing it'
                                : 'Analyze thread'}
                            </TooltipContent>
                          </Tooltip>
                          {!selectedThreadIsDraft && (
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button
                                  variant={
                                    runtimeSidebarOpen ? 'default' : 'ghost'
                                  }
                                  size="icon"
                                  className="h-7 w-7 p-0"
                                  onClick={() =>
                                    setRuntimeSidebarOpen((v) => !v)
                                  }>
                                  <Server className="h-3.5 w-3.5" />
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent>
                                {runtimeSidebarOpen
                                  ? 'Hide runtimes'
                                  : 'Show runtimes'}
                              </TooltipContent>
                            </Tooltip>
                          )}
                          {selectedThreadHeaderUsage && (
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-7 w-7"
                                  onClick={handleOpenUsageStatsModal}>
                                  <BarChart3 className="h-4 w-4" />
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent>
                                View detailed usage statistics
                              </TooltipContent>
                            </Tooltip>
                          )}
                          {!selectedThreadIsDraft && (
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-7 w-7"
                                  disabled={
                                    (selectedThread as ThreadDto).status ===
                                    ThreadDtoStatusEnum.Running
                                  }
                                  onClick={() =>
                                    handleExportThread(
                                      selectedThread.id,
                                      (selectedThread as ThreadDto).name ?? '',
                                    )
                                  }>
                                  <Download className="h-4 w-4" />
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent>
                                Export thread as JSON
                              </TooltipContent>
                            </Tooltip>
                          )}
                        </div>
                        <ThreadTokenUsageLine
                          usage={selectedThreadHeaderUsage}
                          withPopover
                          contextPercent={selectedThreadHeaderContextPercent}
                          contextMaxTokens={
                            selectedThreadHeaderContextMaxTokens
                          }
                        />
                      </div>
                    </div>
                  </div>

                  <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
                    <ThreadChatPanel
                      graphId={selectedThread.graphId}
                      thread={selectedThread as ThreadDto}
                      triggerNodes={triggerNodesForSelectedThread}
                      templatesLoading={templatesLoading}
                      nodeDisplayNames={
                        graphCache[selectedThread.graphId]?.nodeDisplayNames
                      }
                      graphLoaded={Boolean(graphCache[selectedThread.graphId])}
                      graphIsRunning={graphIsRunning}
                      onRequestThreadSwitch={handleThreadChatSwitchRequest}
                      isDraft={draftThread?.id === selectedThreadId}
                      onDraftMessageSent={applyThreadCreate}
                      messages={
                        selectedThreadId ? visibleMessagesForSelectedThread : []
                      }
                      messagesLoading={
                        selectedThreadId
                          ? (messageMeta[selectedThreadId]?.loading ?? false)
                          : false
                      }
                      hasMoreMessages={
                        selectedThreadId
                          ? isDraftThreadId(selectedThreadId)
                            ? false
                            : (messageMeta[selectedThreadId]?.hasMore ?? true)
                          : false
                      }
                      loadingMoreMessages={
                        selectedThreadId
                          ? (messageMeta[selectedThreadId]?.loadingMore ??
                            false)
                          : false
                      }
                      pendingMessages={
                        selectedThreadId
                          ? visiblePendingMessagesForSelectedThread
                          : []
                      }
                      externalThreadId={
                        selectedThreadId
                          ? externalThreadIds[selectedThreadId]
                          : undefined
                      }
                      onLoadMoreMessages={
                        selectedThreadId
                          ? isDraftThreadId(selectedThreadId)
                            ? undefined
                            : () => loadMoreMessagesForThread(selectedThreadId)
                          : undefined
                      }
                      onUpdateSharedMessages={updateMessages}
                      onUpdatePendingMessages={updatePendingMessages}
                    />
                  </div>
                </>
              ) : (
                <div className="flex-1 flex items-center justify-center">
                  <p className="text-sm text-muted-foreground">
                    Select a thread to view its messages
                  </p>
                </div>
              )}
            </div>
          </div>

          <ThreadRuntimeSidebar
            open={
              runtimeSidebarOpen && !!selectedThread && !selectedThreadIsDraft
            }
            onClose={() => setRuntimeSidebarOpen(false)}
            runtimes={runtimes}
            loading={runtimesLoading}
            error={runtimesError}
            onRefresh={refreshRuntimes}
            nodeDisplayNames={runtimeNodeNames}
            nodeAgentNames={runtimeAgentNames}
          />
        </div>
      </div>

      <AnalyzeThreadModal
        open={analyzeModalOpen}
        onCancel={handleCloseAnalyzeModal}
        onAnalyze={handleAnalyzeThread}
        loading={analyzeLoading}
        disabled={analysisButtonDisabled}
        result={analysisResult}
        userInput={analysisUserInput}
        onUserInputChange={setAnalysisUserInput}
        model={analysisModel}
        onModelChange={setAnalysisModel}
        models={liteLlmModels}
        modelsLoading={litellmModelsLoading}
      />

      <UsageStatsModal
        open={usageStatsModalOpen}
        onClose={handleCloseUsageStatsModal}
        threadId={usageStatsModalThreadId}
        threads={threads}
        graphCache={graphCache}
        getFullGraph={getFullGraph}
        threadUsageStats={threadUsageStats}
        threadUsageStatsLoading={threadUsageStatsLoading}
        socketEventsCount={socketEventsForUsageStatsThread.length}
        onShowLocalEvents={handleOpenThreadSocketEventsModal}
      />

      <SocketEventsModal
        open={threadSocketEventsModalOpen}
        onClose={handleCloseThreadSocketEventsModal}
        threadId={threadSocketEventsModalThreadId}
        events={socketEventsForModalThread}
        onCopyJson={handleCopyThreadSocketEventsJson}
      />

      {/* Hidden file input for thread snapshot import */}
      <input
        ref={importFileInputRef}
        type="file"
        accept=".json"
        className="hidden"
        onChange={handleImportFileChange}
      />

      {/* Thread snapshot viewer modal */}
      <ThreadSnapshotModal
        open={snapshotModalOpen}
        onClose={() => {
          setSnapshotModalOpen(false);
          setSnapshotModalData(null);
        }}
        snapshot={snapshotModalData}
      />
    </div>
  );
};

export default ChatsPage;
