import {
  BarChart3,
  ExternalLink,
  Loader2,
  MessageSquare,
  Network,
  Plus,
  Server,
  X,
} from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router';
import { useParams } from 'react-router';

import type { ThreadDto } from '../../autogenerated';
import { Avatar, AvatarFallback } from '../../components/ui/avatar';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import {
  Popover,
  PopoverAnchor,
  PopoverContent,
  PopoverTrigger,
} from '../../components/ui/popover';
import { Tabs, TabsList, TabsTrigger } from '../../components/ui/tabs';
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '../../components/ui/tooltip';
import {
  getStatusBadgeClass,
  getThreadStatusDisplay,
} from '../../utils/threadStatus';
import { toastMessage } from '../../utils/toastAdapter';
import { AnalyzeThreadModal } from './components/AnalyzeThreadModal';
import { ContextUsageGauge } from './components/ContextUsageGauge';
import { GraphPickerContent } from './components/GraphPickerPopover';
import { SocketEventsModal } from './components/SocketEventsModal';
import ThreadChatPanel from './components/ThreadChatPanel';
import { ThreadListItem } from './components/ThreadListItem';
import { ThreadRuntimeSidebar } from './components/ThreadRuntimeSidebar';
import { ThreadTokenUsageLine } from './components/ThreadTokenUsageLine';
import { UsageStatsModal } from './components/UsageStatsModal';
import { useChatsAnalysis } from './hooks/useChatsAnalysis';
import { useChatsMessages } from './hooks/useChatsMessages';
import { useChatsThreadList } from './hooks/useChatsThreadList';
import { useChatsUsageStats } from './hooks/useChatsUsageStats';
import { useChatsWebSocket } from './hooks/useChatsWebSocket';
import { useThreadRuntimes } from './hooks/useThreadRuntimes';
import {
  formatUsd,
  getAgentColor,
  getAgentInitials,
  isDraftThreadId,
  parseAgentLabel,
} from './utils/chatsPageUtils';

export const ChatsPage = () => {
  const { projectId } = useParams<{ projectId: string }>();

  // --- Messages hook ---
  const {
    messages,
    updateMessages,
    pendingMessages,
    updatePendingMessages,
    externalThreadIds,
    setExternalThreadIds,
    messageMeta,
    setMessageMeta,
    getMessageMeta,
    updateMessageMeta,
    loadMessagesForThread,
    loadMoreMessagesForThread,
  } = useChatsMessages({ toastMessage });

  // --- Thread list hook ---
  const threadList = useChatsThreadList({
    toastMessage,
  });
  const {
    threads,
    setThreads,
    threadsLoading,
    threadsLoadingMore,
    threadStatusTab,
    selectedThreadId,
    setSelectedThreadId,
    setSelectedThreadShadow,
    selectedAgentNodeId,
    setSelectedAgentNodeId,
    draftThread,
    setDraftThread,
    graphCache,
    templatesById,
    templatesLoading,
    triggerNodesForSelectedThread,
    graphPickerOpen,
    setGraphPickerOpen,
    graphPickerLoading,
    graphPickerError,
    graphPickerGraphs,
    threadsContainerRef,
    pendingThreadSelectionRef,
    threadsRef,
    graphFilterId,
    graphIsRunning,
    selectedThreadIsDraft,
    selectedThread,
    filteredThreads,
    shouldShowDraftThread,
    filteredGraphLabel,
    getThreadTimestamp,
    sortThreadsByTimestampDesc,
    ensureGraphsLoaded,
    handleThreadsScroll,
    handleThreadStatusTabChange,
    handleClearGraphFilter,
    handleDeleteThread,
    handleCreateDraftThread,
    handleGraphPickerSelect,
    handleThreadChatSwitchRequest,
  } = threadList;

  // --- Usage stats hook ---
  const {
    setThreadTokenUsageByNode,
    selectedThreadUsageByNode,
    selectedThreadThreadUsage,
    selectedThreadContextPercent,
    selectedThreadContextMaxTokens,
    selectedThreadHeaderUsage,
    selectedThreadHeaderContextPercent,
    selectedThreadHeaderContextMaxTokens,
    getNodeConfigString,
    getNodeConfigNumber,
    getNodeTemplateId,
    formatNodeLabel,
    handleOpenUsageStatsModal,
    handleCloseUsageStatsModal,
    invalidateThreadUsageStats,
    usageStatsModalOpen,
    usageStatsModalThreadId,
    threadUsageStats,
    threadUsageStatsLoading,
  } = useChatsUsageStats({
    toastMessage,
    selectedThread,
    selectedThreadId,
    selectedThreadIsDraft,
    selectedAgentNodeId,
    graphCache,
  });

  // --- WebSocket hook ---
  const { applyThreadCreate, isAgentNodeIdInGraph, threadSocketEvents } =
    useChatsWebSocket({
      graphFilterId,
      selectedThreadId,
      draftThread,
      threadsRef,
      pendingThreadSelectionRef,
      setThreads,
      setSelectedThreadId,
      setSelectedThreadShadow,
      setDraftThread,
      setExternalThreadIds,
      setMessageMeta,
      setThreadTokenUsageByNode,
      messages,
      pendingMessages,
      updateMessages,
      updatePendingMessages,
      externalThreadIds,
      sortThreadsByTimestampDesc,
      getThreadTimestamp,
      ensureGraphsLoaded,
      graphCache,
      templatesById,
      invalidateThreadUsageStats,
    });

  const socketEventsForUsageStatsThread = useMemo(() => {
    if (!usageStatsModalThreadId) return [];
    return threadSocketEvents[usageStatsModalThreadId] ?? [];
  }, [threadSocketEvents, usageStatsModalThreadId]);

  // --- Analysis hook ---
  const analysis = useChatsAnalysis({
    toastMessage,
    selectedThread,
    selectedThreadId,
    selectedThreadIsDraft,
    graphIsRunning,
    threadSocketEvents,
  });

  const {
    analyzeModalOpen,
    analyzeLoading,
    analysisResult,
    analysisUserInput,
    setAnalysisUserInput,
    analysisModel,
    setAnalysisModel,
    liteLlmModels,
    litellmModelsLoading,
    analysisButtonDisabled,
    handleOpenAnalyzeModal,
    handleCloseAnalyzeModal,
    handleAnalyzeThread,
    threadSocketEventsModalOpen,
    socketEventsForModalThread,
    handleOpenThreadSocketEventsModal,
    handleCloseThreadSocketEventsModal,
    handleCopyThreadSocketEventsJson,
    threadSocketEventsModalThreadId,
  } = analysis;

  // --- Runtime sidebar ---
  const [runtimeSidebarOpen, setRuntimeSidebarOpen] = useState(false);

  const runtimeNodeNames = useMemo(() => {
    if (!selectedThread || selectedThreadIsDraft) return undefined;
    const graph = graphCache[selectedThread.graphId]?.graph;
    if (!graph) return undefined;
    const metadataNames =
      graphCache[selectedThread.graphId]?.nodeDisplayNames ?? {};
    const names: Record<string, string> = {};
    for (const node of graph.schema?.nodes ?? []) {
      const configName = getNodeConfigString(node.id, 'name');
      names[node.id] =
        configName ?? metadataNames[node.id] ?? formatNodeLabel(node.id);
    }
    return names;
  }, [
    graphCache,
    selectedThread,
    selectedThreadIsDraft,
    getNodeConfigString,
    formatNodeLabel,
  ]);

  const {
    runtimes,
    loading: runtimesLoading,
    error: runtimesError,
    refresh: refreshRuntimes,
  } = useThreadRuntimes(
    selectedThreadId && !selectedThreadIsDraft ? selectedThreadId : undefined,
    selectedThread && !selectedThreadIsDraft
      ? selectedThread.graphId
      : undefined,
  );

  // --- Auto-load messages for selected thread ---

  const messagesRef = useRef(messages);
  useEffect(() => {
    messagesRef.current = messages;
  }, [messages]);

  useEffect(() => {
    if (
      !selectedThread ||
      ('isDraft' in selectedThread && selectedThread.isDraft)
    )
      return;

    const meta = getMessageMeta(selectedThread.id);
    const existingMessages =
      messagesRef.current[selectedThread.id]?.['all'] ?? [];

    if (existingMessages.length > 0) {
      if (meta.offset === 0) {
        updateMessageMeta(selectedThread.id, (prev) => ({
          ...prev,
          loading: false,
          loadingMore: false,
          offset: existingMessages.length,
        }));
      }
      return;
    }

    if (meta.initialLoadFailed) {
      return;
    }

    if (meta.offset === 0 && !meta.loading) {
      void loadMessagesForThread(selectedThread.id);
    }
  }, [
    selectedThread,
    getMessageMeta,
    loadMessagesForThread,
    updateMessageMeta,
  ]);

  // --- Derived thread data ---

  const threadStatusMeta = selectedThread
    ? 'isDraft' in selectedThread && selectedThread.isDraft
      ? null
      : getThreadStatusDisplay((selectedThread as ThreadDto).status)
    : null;

  const selectedThreadAllMessages = useMemo(() => {
    if (!selectedThreadId) return [];
    return messages[selectedThreadId]?.['all'] || [];
  }, [messages, selectedThreadId]);

  const agentsForSelectedThread = useMemo(() => {
    if (!selectedThreadId || !selectedThread || selectedThreadIsDraft) {
      return [];
    }

    // Use thread.agents from API when available
    const apiAgents = (selectedThread as ThreadDto).agents;
    if (apiAgents && apiAgents.length > 0) {
      return apiAgents.map((a) => ({
        nodeId: a.nodeId,
        label: a.name,
        description: a.description,
      }));
    }

    // Fallback to graph cache for threads without agents
    const agents: {
      nodeId: string;
      label: string;
      description?: string;
    }[] = [];

    const graphId = selectedThread.graphId;
    const graph = graphCache[graphId]?.graph;
    const schemaNodes = graph?.schema?.nodes ?? [];

    schemaNodes.forEach((node) => {
      const nodeId = node.id;
      if (!isAgentNodeIdInGraph(graphId, nodeId)) return;

      const configName = getNodeConfigString(nodeId, 'name');
      const configDescription = getNodeConfigString(nodeId, 'description');

      agents.push({
        nodeId,
        label: configName ?? formatNodeLabel(nodeId),
        description: configDescription,
      });
    });

    return agents;
  }, [
    formatNodeLabel,
    graphCache,
    getNodeConfigString,
    isAgentNodeIdInGraph,
    selectedThread,
    selectedThreadId,
    selectedThreadIsDraft,
  ]);

  // Agents by graphId — used to show avatars in every thread list item
  const agentsByGraphId = useMemo(() => {
    const result: Record<string, { nodeId: string; label: string }[]> = {};

    for (const t of [
      ...filteredThreads,
      ...(draftThread ? [draftThread] : []),
    ]) {
      // Draft threads don't have agents from API
      if ('isDraft' in t && t.isDraft) continue;
      const apiAgents = (t as ThreadDto).agents;
      if (!apiAgents || result[t.graphId]) continue;
      result[t.graphId] = apiAgents.map((a) => ({
        nodeId: a.nodeId,
        label: a.name,
      }));
    }

    // Fallback to graph cache for graphIds not covered by thread.agents
    const graphIds = new Set<string>();
    for (const t of filteredThreads) graphIds.add(t.graphId);
    if (draftThread) graphIds.add(draftThread.graphId);

    for (const gId of graphIds) {
      if (result[gId]) continue;
      const cached = graphCache[gId];
      if (!cached) continue;
      const graph = cached.graph;
      const displayNames = cached.nodeDisplayNames ?? {};
      const agents: (typeof result)[string] = [];

      for (const node of graph.schema?.nodes ?? []) {
        if (!isAgentNodeIdInGraph(gId, node.id)) continue;
        const config = node.config as Record<string, unknown> | undefined;
        const configName =
          config && typeof config.name === 'string' && config.name.trim()
            ? config.name.trim()
            : undefined;
        const label =
          configName ??
          (displayNames[node.id] && displayNames[node.id]!.trim()
            ? displayNames[node.id]
            : node.id.length <= 10
              ? node.id
              : `Node ${node.id.slice(-6)}`);
        agents.push({
          nodeId: node.id,
          label,
        });
      }
      result[gId] = agents;
    }
    return result;
  }, [filteredThreads, draftThread, graphCache, isAgentNodeIdInGraph]);

  const runtimeAgentNames = useMemo(() => {
    if (!selectedThread || selectedThreadIsDraft) return {};
    const graph = graphCache[selectedThread.graphId]?.graph;
    if (!graph) return {};

    const edges = graph.schema?.edges ?? [];
    const agentNodeIds = new Set(agentsForSelectedThread.map((a) => a.nodeId));

    // Build child -> parents adjacency
    const parentMap: Record<string, string[]> = {};
    for (const edge of edges) {
      if (!parentMap[edge.to]) parentMap[edge.to] = [];
      parentMap[edge.to]!.push(edge.from);
    }

    // BFS from a node upward to find agent ancestors
    const findAgentAncestors = (nodeId: string): string[] => {
      const visited = new Set<string>();
      const queue = [nodeId];
      const agents: string[] = [];
      while (queue.length > 0) {
        const current = queue.shift()!;
        if (visited.has(current)) continue;
        visited.add(current);
        if (agentNodeIds.has(current)) {
          agents.push(current);
          continue;
        }
        for (const parent of parentMap[current] ?? []) {
          queue.push(parent);
        }
      }
      return agents;
    };

    const result: Record<string, string> = {};
    for (const node of graph.schema?.nodes ?? []) {
      const agentAncestors = findAgentAncestors(node.id);
      if (agentAncestors.length > 0) {
        const labels = agentAncestors.map((agentId) => {
          const agent = agentsForSelectedThread.find(
            (a) => a.nodeId === agentId,
          );
          return agent?.label ?? agentId;
        });
        result[node.id] = labels.join(', ');
      }
    }
    return result;
  }, [
    graphCache,
    selectedThread,
    selectedThreadIsDraft,
    agentsForSelectedThread,
  ]);

  const visibleMessagesForSelectedThread = useMemo(() => {
    if (!selectedThreadId) return [];
    if (!selectedAgentNodeId) return selectedThreadAllMessages;
    return selectedThreadAllMessages.filter(
      (msg) => msg.nodeId === selectedAgentNodeId,
    );
  }, [selectedAgentNodeId, selectedThreadAllMessages, selectedThreadId]);

  const visiblePendingMessagesForSelectedThread = useMemo(() => {
    if (!selectedThreadId) return [];
    if (selectedAgentNodeId) return [];
    return pendingMessages[selectedThreadId]?.['all'] || [];
  }, [pendingMessages, selectedAgentNodeId, selectedThreadId]);

  // --- Empty state ---

  const threadsEmpty =
    !threadsLoading &&
    !threadsLoadingMore &&
    filteredThreads.length === 0 &&
    !shouldShowDraftThread;

  const threadsEmptyDescription = useMemo(() => {
    const scopeSuffix = graphFilterId ? ' for this graph' : '';
    if (threadStatusTab === 'resolved')
      return `No resolved threads${scopeSuffix}`;
    if (threadStatusTab === 'open') return `No open threads${scopeSuffix}`;
    return graphFilterId ? 'No threads found for this graph' : 'No threads yet';
  }, [graphFilterId, threadStatusTab]);

  // --- Render ---

  return (
    <div className="h-[calc(100vh-64px)] max-h-[calc(100vh-64px)] flex flex-col overflow-hidden">
      <div className="flex flex-1 min-h-0 overflow-hidden">
        {/* Left sidebar: thread list */}
        <aside className="w-72 bg-card border-r border-border flex flex-col overflow-hidden">
          {/* Header */}
          {graphFilterId ? (
            <div className="px-4 py-3 border-b border-border flex items-center justify-between shrink-0">
              <span className="text-sm font-semibold text-foreground">
                Chats
              </span>
              <Button
                variant="outline"
                size="sm"
                className="w-7 h-7 p-0"
                onClick={handleCreateDraftThread}>
                <Plus className="w-3.5 h-3.5" />
              </Button>
            </div>
          ) : (
            <Popover open={graphPickerOpen} onOpenChange={setGraphPickerOpen}>
              <PopoverAnchor asChild>
                <div className="px-4 py-3 border-b border-border flex items-center justify-between shrink-0">
                  <span className="text-sm font-semibold text-foreground">
                    Chats
                  </span>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      className="w-7 h-7 p-0"
                      onClick={handleCreateDraftThread}>
                      <Plus className="w-3.5 h-3.5" />
                    </Button>
                  </PopoverTrigger>
                </div>
              </PopoverAnchor>
              <PopoverContent
                align="center"
                className="w-[calc(18rem-1rem)] p-1">
                <GraphPickerContent
                  graphs={graphPickerGraphs}
                  loading={graphPickerLoading}
                  error={graphPickerError}
                  onSelect={handleGraphPickerSelect}
                />
              </PopoverContent>
            </Popover>
          )}

          {/* Filter tabs */}
          <div className="px-3 py-2 border-b border-border shrink-0">
            <Tabs
              value={threadStatusTab}
              onValueChange={handleThreadStatusTabChange}
              className="w-full">
              <TabsList className="w-full h-7 grid grid-cols-3 p-0.5">
                <TabsTrigger value="all" className="text-xs h-6">
                  All
                </TabsTrigger>
                <TabsTrigger value="open" className="text-xs h-6">
                  Open
                </TabsTrigger>
                <TabsTrigger value="resolved" className="text-xs h-6">
                  Resolved
                </TabsTrigger>
              </TabsList>
            </Tabs>
          </div>
          {graphFilterId && (
            <div className="px-3 py-2 border-b border-border shrink-0">
              <div className="flex items-center gap-2 min-w-0">
                <Badge
                  variant="secondary"
                  className="gap-1.5 pl-1.5 pr-1 py-0.5 min-w-0 max-w-full"
                  title={filteredGraphLabel}>
                  <Network className="w-3 h-3 shrink-0" />
                  <span className="truncate">{filteredGraphLabel}</span>
                  <button
                    type="button"
                    className="ml-0.5 rounded-sm hover:bg-muted-foreground/20 p-0.5 shrink-0 transition-colors"
                    onClick={handleClearGraphFilter}
                    aria-label="Clear graph filter">
                    <X className="h-3 w-3" />
                  </button>
                </Badge>
              </div>
            </div>
          )}
          <div
            ref={threadsContainerRef}
            onScroll={handleThreadsScroll}
            className="flex-1 min-h-0 overflow-y-auto py-1">
            {shouldShowDraftThread && draftThread ? (
              <ThreadListItem
                thread={draftThread}
                isActive={draftThread.id === selectedThreadId}
                graphCache={graphCache}
                onSelect={setSelectedThreadId}
                onDeleteThread={handleDeleteThread}
                agents={[]}
              />
            ) : null}
            {filteredThreads.map((thread) => (
              <ThreadListItem
                key={thread.id}
                thread={thread}
                isActive={thread.id === selectedThreadId}
                graphCache={graphCache}
                onSelect={setSelectedThreadId}
                onDeleteThread={handleDeleteThread}
                agents={
                  thread.id === selectedThreadId
                    ? agentsForSelectedThread
                    : (agentsByGraphId[thread.graphId] ?? [])
                }
              />
            ))}
            {threadsLoading && (
              <div className="py-6 text-center">
                <Loader2 className="h-5 w-5 animate-spin mx-auto text-muted-foreground" />
              </div>
            )}
            {threadsEmpty && (
              <div className="py-10 px-4">
                <div className="flex flex-col items-center justify-center text-center">
                  <MessageSquare className="w-10 h-10 text-muted-foreground/30 mb-3" />
                  <p className="text-sm font-medium text-muted-foreground mb-1">
                    {threadsEmptyDescription}
                  </p>
                  <p className="text-xs text-muted-foreground/70">
                    Start a new chat to begin a conversation
                  </p>
                </div>
              </div>
            )}
            {threadsLoadingMore && (
              <div className="py-3 text-center">
                <Loader2 className="h-4 w-4 animate-spin mx-auto text-muted-foreground" />
              </div>
            )}
          </div>
        </aside>

        {/* Right panel: chat + runtime sidebar */}
        <div className="flex-1 min-h-0 flex overflow-hidden">
          <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
            <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
              {selectedThread ? (
                <>
                  {/* Chat Header */}
                  <div className="px-5 py-4 border-b border-border bg-card flex-shrink-0">
                    <div className="flex items-start gap-4">
                      {/* Left: title + graph link + agent cards */}
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                          <h2 className="text-base font-semibold m-0">
                            {selectedThread.name || 'New Thread'}
                          </h2>
                          {threadStatusMeta && (
                            <Badge
                              className={`text-[10px] px-1.5 py-0 h-4 font-medium ${getStatusBadgeClass(threadStatusMeta.label)}`}>
                              {threadStatusMeta.label}
                            </Badge>
                          )}
                        </div>
                        <p className="text-xs text-muted-foreground flex items-center gap-1 mb-3">
                          <Network className="w-3 h-3" />
                          <Link
                            to={
                              projectId
                                ? `/projects/${projectId}/graphs/${selectedThread.graphId}`
                                : `/graphs/${selectedThread.graphId}`
                            }
                            className="hover:text-foreground hover:underline transition-colors inline-flex items-center gap-1">
                            {graphCache[selectedThread.graphId]?.graph.name ||
                              'Loading\u2026'}
                            <ExternalLink className="h-3 w-3" />
                          </Link>
                        </p>
                        {/* Agent cards with ContextUsageGauge */}
                        <div className="flex items-center gap-2 flex-wrap">
                          {agentsForSelectedThread.map((agent) => {
                            const usage =
                              selectedThreadUsageByNode?.[agent.nodeId];
                            const pct =
                              usage?.currentContext &&
                              selectedThreadContextMaxTokens
                                ? Math.round(
                                    (usage.currentContext /
                                      selectedThreadContextMaxTokens) *
                                      100,
                                  )
                                : 0;
                            const parsed = parseAgentLabel(agent.label);
                            const displayRole =
                              parsed.role ?? agent.description;
                            return (
                              <Popover key={agent.nodeId}>
                                <PopoverTrigger asChild>
                                  <div className="flex items-center gap-2 px-2.5 py-1.5 bg-muted/60 hover:bg-muted rounded-lg cursor-pointer transition-colors">
                                    <Avatar className="w-6 h-6 flex-shrink-0">
                                      <AvatarFallback
                                        className={`${getAgentColor(agent.nodeId)} text-white text-[10px]`}>
                                        {getAgentInitials(agent.label)}
                                      </AvatarFallback>
                                    </Avatar>
                                    <div className="text-xs min-w-0">
                                      <div className="font-medium leading-tight truncate">
                                        {parsed.name}
                                      </div>
                                      {displayRole && (
                                        <div className="text-muted-foreground leading-tight">
                                          {displayRole}
                                        </div>
                                      )}
                                    </div>
                                    <div className="flex items-center gap-1 ml-1 flex-shrink-0">
                                      <ContextUsageGauge
                                        percent={pct}
                                        size={18}
                                      />
                                      <span className="text-[10px] text-muted-foreground">
                                        {pct}%
                                      </span>
                                    </div>
                                  </div>
                                </PopoverTrigger>
                                <PopoverContent
                                  className="w-60 p-3 text-xs space-y-1.5"
                                  align="start">
                                  <div className="font-semibold text-foreground mb-2">
                                    {parsed.name}
                                    {displayRole && (
                                      <span className="font-normal text-muted-foreground ml-1">
                                        ({displayRole})
                                      </span>
                                    )}
                                  </div>
                                  {usage && (
                                    <div className="space-y-1">
                                      {(
                                        [
                                          [
                                            'Input tokens',
                                            usage.inputTokens?.toLocaleString() ??
                                              '\u2014',
                                          ],
                                          [
                                            'Cached input',
                                            usage.cachedInputTokens?.toLocaleString() ??
                                              '\u2014',
                                          ],
                                          [
                                            'Output tokens',
                                            usage.outputTokens?.toLocaleString() ??
                                              '\u2014',
                                          ],
                                          [
                                            'Total tokens',
                                            usage.totalTokens?.toLocaleString() ??
                                              '\u2014',
                                          ],
                                          [
                                            'Total cost',
                                            formatUsd(usage.totalPrice),
                                          ],
                                          ['Context usage', `${pct}%`],
                                        ] as [string, string][]
                                      ).map(([label, val]) => (
                                        <div
                                          key={label}
                                          className="flex justify-between text-muted-foreground">
                                          <span>{label}</span>
                                          <span className="text-foreground font-medium">
                                            {val}
                                          </span>
                                        </div>
                                      ))}
                                    </div>
                                  )}
                                </PopoverContent>
                              </Popover>
                            );
                          })}
                        </div>
                      </div>

                      {/* Right: action buttons + token usage */}
                      <div className="flex flex-col items-end gap-2 flex-shrink-0">
                        <div className="flex items-center gap-1.5">
                          <Button
                            variant="outline"
                            size="sm"
                            className="h-7 px-2.5 text-xs"
                            onClick={handleOpenAnalyzeModal}
                            disabled={analysisButtonDisabled}
                            title={
                              selectedThreadIsDraft
                                ? 'Create the thread before analyzing it'
                                : undefined
                            }>
                            Analyze thread
                          </Button>
                          {!selectedThreadIsDraft && (
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button
                                  variant={
                                    runtimeSidebarOpen ? 'default' : 'outline'
                                  }
                                  size="icon"
                                  className="h-7 w-7 p-0"
                                  onClick={() =>
                                    setRuntimeSidebarOpen((v) => !v)
                                  }>
                                  <Server className="h-3.5 w-3.5" />
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent>
                                {runtimeSidebarOpen
                                  ? 'Hide runtimes'
                                  : 'Show runtimes'}
                              </TooltipContent>
                            </Tooltip>
                          )}
                          {selectedThreadHeaderUsage && (
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  className="h-7 w-7"
                                  onClick={handleOpenUsageStatsModal}>
                                  <BarChart3 className="h-4 w-4" />
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent>
                                View detailed usage statistics
                              </TooltipContent>
                            </Tooltip>
                          )}
                        </div>
                        <ThreadTokenUsageLine
                          usage={selectedThreadHeaderUsage}
                          withPopover
                          contextPercent={selectedThreadHeaderContextPercent}
                          contextMaxTokens={
                            selectedThreadHeaderContextMaxTokens
                          }
                        />
                      </div>
                    </div>
                  </div>

                  <div className="flex-1 min-h-0 flex flex-col p-6 pt-4">
                    <ThreadChatPanel
                      graphId={selectedThread.graphId}
                      thread={selectedThread as ThreadDto}
                      triggerNodes={triggerNodesForSelectedThread}
                      templatesLoading={templatesLoading}
                      nodeDisplayNames={
                        graphCache[selectedThread.graphId]?.nodeDisplayNames
                      }
                      graphLoaded={Boolean(graphCache[selectedThread.graphId])}
                      graphIsRunning={graphIsRunning}
                      onRequestThreadSwitch={handleThreadChatSwitchRequest}
                      isDraft={draftThread?.id === selectedThreadId}
                      onDraftMessageSent={applyThreadCreate}
                      messages={
                        selectedThreadId ? visibleMessagesForSelectedThread : []
                      }
                      messagesLoading={
                        selectedThreadId
                          ? (messageMeta[selectedThreadId]?.loading ?? false)
                          : false
                      }
                      hasMoreMessages={
                        selectedThreadId
                          ? isDraftThreadId(selectedThreadId)
                            ? false
                            : (messageMeta[selectedThreadId]?.hasMore ?? true)
                          : false
                      }
                      loadingMoreMessages={
                        selectedThreadId
                          ? (messageMeta[selectedThreadId]?.loadingMore ??
                            false)
                          : false
                      }
                      pendingMessages={
                        selectedThreadId
                          ? visiblePendingMessagesForSelectedThread
                          : []
                      }
                      externalThreadId={
                        selectedThreadId
                          ? externalThreadIds[selectedThreadId]
                          : undefined
                      }
                      onLoadMoreMessages={
                        selectedThreadId
                          ? isDraftThreadId(selectedThreadId)
                            ? undefined
                            : () => loadMoreMessagesForThread(selectedThreadId)
                          : undefined
                      }
                      onUpdateSharedMessages={updateMessages}
                      onUpdatePendingMessages={updatePendingMessages}
                    />
                  </div>
                </>
              ) : (
                <div className="flex-1 flex items-center justify-center">
                  <p className="text-sm text-muted-foreground">
                    Select a thread to view its messages
                  </p>
                </div>
              )}
            </div>
          </div>

          <ThreadRuntimeSidebar
            open={
              runtimeSidebarOpen && !!selectedThread && !selectedThreadIsDraft
            }
            onClose={() => setRuntimeSidebarOpen(false)}
            runtimes={runtimes}
            loading={runtimesLoading}
            error={runtimesError}
            onRefresh={refreshRuntimes}
            nodeDisplayNames={runtimeNodeNames}
            nodeAgentNames={runtimeAgentNames}
          />
        </div>
      </div>

      <AnalyzeThreadModal
        open={analyzeModalOpen}
        onCancel={handleCloseAnalyzeModal}
        onAnalyze={handleAnalyzeThread}
        loading={analyzeLoading}
        disabled={analysisButtonDisabled}
        result={analysisResult}
        userInput={analysisUserInput}
        onUserInputChange={setAnalysisUserInput}
        model={analysisModel}
        onModelChange={setAnalysisModel}
        models={liteLlmModels}
        modelsLoading={litellmModelsLoading}
      />

      <UsageStatsModal
        open={usageStatsModalOpen}
        onClose={handleCloseUsageStatsModal}
        threadId={usageStatsModalThreadId}
        threads={threads}
        graphCache={graphCache}
        templatesById={templatesById}
        threadUsageStats={threadUsageStats}
        threadUsageStatsLoading={threadUsageStatsLoading}
        socketEventsCount={socketEventsForUsageStatsThread.length}
        onShowLocalEvents={handleOpenThreadSocketEventsModal}
      />

      <SocketEventsModal
        open={threadSocketEventsModalOpen}
        onClose={handleCloseThreadSocketEventsModal}
        threadId={threadSocketEventsModalThreadId}
        events={socketEventsForModalThread}
        onCopyJson={handleCopyThreadSocketEventsJson}
      />
    </div>
  );
};

export default ChatsPage;
