import { ThreadDto, ThreadDtoStatusEnum } from '../autogenerated';

export const THREAD_STATUS_STYLES: Record<
  ThreadDto['status'],
  { label: string; color: string }
> = {
  [ThreadDtoStatusEnum.Running]: {
    label: 'Running',
    color: 'var(--color-blue-500)',
  },
  [ThreadDtoStatusEnum.Done]: {
    label: 'Done',
    color: 'var(--color-green-500)',
  },
  [ThreadDtoStatusEnum.NeedMoreInfo]: {
    label: 'Need More Info',
    color: 'var(--color-amber-500)',
  },
  [ThreadDtoStatusEnum.Stopped]: {
    label: 'Stopped',
    color: 'var(--muted-foreground)',
  },
} as const;

export const getThreadStatusDisplay = (status?: ThreadDto['status']) => {
  if (!status) return null;
  return (
    THREAD_STATUS_STYLES[status] ?? {
      label: status.replace(/_/g, ' '),
      color: 'var(--muted-foreground)',
    }
  );
};

export function getStatusBadgeClass(label: string): string {
  if (label === 'Done' || label === 'done')
    return 'bg-green-100 text-green-700 hover:bg-green-100';
  if (label === 'Running' || label === 'running')
    return 'bg-blue-100 text-blue-700 hover:bg-blue-100';
  if (label === 'Need More Info')
    return 'bg-amber-100 text-amber-700 hover:bg-amber-100';
  if (label === 'Stopped' || label === 'stopped')
    return 'bg-muted text-muted-foreground hover:bg-muted';
  return 'bg-muted text-muted-foreground hover:bg-muted';
}
