import { createContext, useContext } from 'react';

import type { GraphNodeWithStatusDto } from '../../../autogenerated';
import type { GraphNode } from '../types';
import type { ConnectionPreview } from '../utils/graphCanvasUtils';

export interface NodeDynamicContext {
  compiledNodes?: Record<string, GraphNodeWithStatusDto>;
  compiledNodesLoading?: boolean;
  connectionPreview: ConnectionPreview | null;
  onNodeEdit: (node: GraphNode) => void;
  onNodeDelete: (nodeId: string) => void;
}

const noop = () => {};

export const NodeDynamicCtx = createContext<NodeDynamicContext>({
  compiledNodes: undefined,
  compiledNodesLoading: false,
  connectionPreview: null,
  onNodeEdit: noop as (node: GraphNode) => void,
  onNodeDelete: noop as (nodeId: string) => void,
});

export const useNodeDynamicCtx = () => useContext(NodeDynamicCtx);
