import {
  App,
  Button,
  Card,
  ColorPicker,
  Form,
  Input,
  Space,
  Spin,
  Steps,
  Typography,
} from 'antd';
import { useState } from 'react';
import { useNavigate } from 'react-router';

import { graphsApi, projectsApi } from '../../api';
import type {
  CreateGraphDto,
  CreateProjectDto,
  ProjectDto,
  UpdateProjectDto,
} from '../../autogenerated';
import { useProjectContext } from '../../contexts/ProjectContext';
import { extractApiErrorMessage } from '../../utils/errors';

const { Title, Paragraph } = Typography;

interface ProjectFormValues {
  name: string;
  description?: string;
  icon?: string;
}

interface GraphFormValues {
  name: string;
  description?: string;
}

const DEFAULT_PROJECT_COLORS = [
  '#3B82F6',
  '#10B981',
  '#F59E0B',
  '#EF4444',
  '#8B5CF6',
  '#EC4899',
  '#06B6D4',
  '#84CC16',
];

export const CreateProjectPage = () => {
  const { message } = App.useApp();
  const navigate = useNavigate();
  const { loading: projectsLoading, loadProjects } = useProjectContext();

  const [projectForm] = Form.useForm<ProjectFormValues>();
  const [graphForm] = Form.useForm<GraphFormValues>();

  const [currentStep, setCurrentStep] = useState<0 | 1>(0);
  const [createdProject, setCreatedProject] = useState<ProjectDto | null>(null);
  const [colorValue, setColorValue] = useState<string>('#3B82F6');
  const [saving, setSaving] = useState(false);

  const handleProjectSubmit = async () => {
    try {
      const values = await projectForm.validateFields();
      setSaving(true);

      if (createdProject) {
        const updatePayload: UpdateProjectDto = {
          name: values.name.trim(),
          description: values.description?.trim() || null,
          icon: values.icon?.trim() || null,
          color: colorValue || null,
        };
        const res = await projectsApi.updateProject(
          createdProject.id,
          updatePayload,
        );
        await loadProjects();
        setCreatedProject(res.data);
      } else {
        const createPayload: CreateProjectDto = {
          name: values.name.trim(),
          description: values.description?.trim() || null,
          icon: values.icon?.trim() || null,
          color: colorValue || null,
        };
        const res = await projectsApi.createProject(createPayload);
        await loadProjects();
        setCreatedProject(res.data);
      }

      setCurrentStep(1);
    } catch (err: unknown) {
      if (typeof err === 'object' && err !== null && 'errorFields' in err) {
        return;
      }
      message.error(
        extractApiErrorMessage(
          err,
          createdProject
            ? 'Failed to update project'
            : 'Failed to create project',
        ),
      );
    } finally {
      setSaving(false);
    }
  };

  const handleGraphSubmit = async () => {
    if (!createdProject) return;

    try {
      const values = await graphForm.validateFields();
      setSaving(true);

      const graphPayload: CreateGraphDto = {
        name: values.name.trim(),
        description: values.description?.trim() || null,
        schema: { nodes: [], edges: [] },
      };

      const res = await graphsApi.createGraph(graphPayload, {
        headers: { 'x-project-id': createdProject.id },
      });

      navigate(`/projects/${createdProject.id}/graphs/${res.data.id}`, {
        replace: true,
      });
    } catch (err: unknown) {
      if (typeof err === 'object' && err !== null && 'errorFields' in err) {
        return;
      }
      message.error(extractApiErrorMessage(err, 'Failed to create graph'));
    } finally {
      setSaving(false);
    }
  };

  const handleBack = () => {
    if (createdProject) {
      projectForm.setFieldsValue({
        name: createdProject.name,
        description: createdProject.description ?? undefined,
        icon: createdProject.icon ?? undefined,
      });
      setColorValue(createdProject.color ?? '#3B82F6');
    }
    setCurrentStep(0);
  };

  if (projectsLoading) {
    return (
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          height: '100vh',
        }}>
        <Spin size="large" />
      </div>
    );
  }

  return (
    <div
      style={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#f5f5f5',
        padding: 24,
      }}>
      <Card
        style={{
          width: '100%',
          maxWidth: 520,
          borderRadius: 16,
          boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
        }}
        styles={{ body: { padding: 32 } }}>
        <Steps
          current={currentStep}
          items={[{ title: 'Project' }, { title: 'First Graph' }]}
          style={{ marginBottom: 32 }}
        />

        {currentStep === 0 && (
          <>
            <div style={{ textAlign: 'center', marginBottom: 28 }}>
              <div style={{ fontSize: 40, marginBottom: 8 }}>🚀</div>
              <Title level={3} style={{ marginBottom: 8 }}>
                Create your first project
              </Title>
              <Paragraph type="secondary" style={{ marginBottom: 0 }}>
                Projects help you organize your graphs, knowledge, and
                repositories.
              </Paragraph>
            </div>

            <Form
              form={projectForm}
              layout="vertical"
              onFinish={handleProjectSubmit}>
              <Form.Item
                name="name"
                label="Project name"
                rules={[
                  { required: true, message: 'Project name is required' },
                ]}>
                <Input placeholder="My First Project" size="large" autoFocus />
              </Form.Item>
              <Form.Item name="description" label="Description">
                <Input.TextArea
                  rows={3}
                  placeholder="Describe what this project is for"
                />
              </Form.Item>
              <Form.Item
                name="icon"
                label="Icon"
                extra="Emoji or icon slug, e.g. 🚀">
                <Input placeholder="🚀" />
              </Form.Item>
              <Form.Item label="Color" extra="Accent color for this project">
                <ColorPicker
                  value={colorValue}
                  onChange={(color) => setColorValue(color.toHexString())}
                  presets={[
                    {
                      label: 'Recommended',
                      colors: DEFAULT_PROJECT_COLORS,
                    },
                  ]}
                  showText
                />
              </Form.Item>
              <Form.Item style={{ marginBottom: 0, marginTop: 8 }}>
                <Button
                  type="primary"
                  htmlType="submit"
                  size="large"
                  loading={saving}
                  style={{ width: '100%' }}>
                  {createdProject ? 'Update & Continue' : 'Create Project'}
                </Button>
              </Form.Item>
            </Form>
          </>
        )}

        {currentStep === 1 && (
          <>
            <div style={{ textAlign: 'center', marginBottom: 28 }}>
              <div style={{ fontSize: 40, marginBottom: 8 }}>📊</div>
              <Title level={3} style={{ marginBottom: 8 }}>
                Create your first graph
              </Title>
              <Paragraph type="secondary" style={{ marginBottom: 0 }}>
                A graph is a visual workflow where you wire together AI agents,
                tools, and triggers.
              </Paragraph>
            </div>

            <Form
              form={graphForm}
              layout="vertical"
              onFinish={handleGraphSubmit}>
              <Form.Item
                name="name"
                label="Graph name"
                rules={[{ required: true, message: 'Graph name is required' }]}>
                <Input placeholder="My First Graph" size="large" autoFocus />
              </Form.Item>
              <Form.Item name="description" label="Description">
                <Input.TextArea
                  rows={3}
                  placeholder="What will this graph do?"
                />
              </Form.Item>
              <Form.Item style={{ marginBottom: 0, marginTop: 8 }}>
                <Space
                  style={{ width: '100%', justifyContent: 'space-between' }}>
                  <Button size="large" onClick={handleBack}>
                    Back
                  </Button>
                  <Button
                    type="primary"
                    htmlType="submit"
                    size="large"
                    loading={saving}>
                    Create Graph
                  </Button>
                </Space>
              </Form.Item>
            </Form>
          </>
        )}
      </Card>
    </div>
  );
};
