import { Folder, Loader2, Plus } from 'lucide-react';
import { useState } from 'react';
import { Navigate, useNavigate } from 'react-router';
import { toast } from 'sonner';

import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { ProjectCard } from '@/components/ui/project-card';
import { Skeleton } from '@/components/ui/skeleton';
import { Textarea } from '@/components/ui/textarea';

import { projectsApi } from '../../api';
import type { CreateProjectDto, ProjectDto } from '../../autogenerated';
import { useProjectContext } from '../../contexts/ProjectContext';
import { extractApiErrorMessage } from '../../utils/errors';
import { ProjectModelSettingsModal } from './ProjectModelSettingsModal';

interface ProjectFormValues {
  name: string;
  description?: string;
  icon?: string;
}

const DEFAULT_PROJECT_COLORS = [
  '#3B82F6',
  '#10B981',
  '#F59E0B',
  '#EF4444',
  '#8B5CF6',
  '#EC4899',
  '#06B6D4',
  '#84CC16',
];

export const ProjectsListPage = () => {
  const navigate = useNavigate();
  const { projects, loading, loadProjects, setCurrentProjectId } =
    useProjectContext();
  const [modalOpen, setModalOpen] = useState(false);
  const [editingProject, setEditingProject] = useState<ProjectDto | null>(null);
  const [saving, setSaving] = useState(false);
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [deleteConfirmId, setDeleteConfirmId] = useState<string | null>(null);
  const [modelSettingsProject, setModelSettingsProject] =
    useState<ProjectDto | null>(null);
  const [colorValue, setColorValue] = useState<string>('#3B82F6');
  const [formValues, setFormValues] = useState<ProjectFormValues>({
    name: '',
    description: '',
    icon: '',
  });

  const handleOpenCreate = () => {
    setEditingProject(null);
    setColorValue('#3B82F6');
    setFormValues({ name: '', description: '', icon: '' });
    setModalOpen(true);
  };

  const handleOpenEdit = (project: ProjectDto) => {
    setEditingProject(project);
    setColorValue(project.color ?? '#3B82F6');
    setFormValues({
      name: project.name,
      description: project.description ?? '',
      icon: project.icon ?? '',
    });
    setModalOpen(true);
  };

  const handleCloseModal = () => {
    setModalOpen(false);
    setEditingProject(null);
    setFormValues({ name: '', description: '', icon: '' });
  };

  const handleSubmit = async () => {
    if (!formValues.name.trim()) return;

    try {
      setSaving(true);

      const payload: CreateProjectDto = {
        name: formValues.name.trim(),
        description: formValues.description?.trim() || null,
        icon: formValues.icon?.trim() || null,
        color: colorValue || null,
      };

      if (editingProject) {
        await projectsApi.updateProject(editingProject.id, payload);
        toast.success('Project updated');
        handleCloseModal();
        await loadProjects();
      } else {
        const res = await projectsApi.createProject(payload);
        toast.success('Project created');
        handleCloseModal();
        await loadProjects();
        setCurrentProjectId(res.data.id);
        navigate('/dashboard');
      }
    } catch (err) {
      if (typeof err === 'object' && err !== null && 'errorFields' in err) {
        return;
      }
      toast.error(extractApiErrorMessage(err, 'Failed to save project'));
    } finally {
      setSaving(false);
    }
  };

  const handleDeleteConfirm = async () => {
    if (!deleteConfirmId) return;
    setDeletingId(deleteConfirmId);
    try {
      await projectsApi.deleteProject(deleteConfirmId);
      toast.success('Project deleted');
      await loadProjects();
    } catch (err) {
      toast.error(extractApiErrorMessage(err, 'Failed to delete project'));
    } finally {
      setDeletingId(null);
      setDeleteConfirmId(null);
    }
  };

  const handleOpenProject = (id: string) => {
    setCurrentProjectId(id);
    navigate('/dashboard');
  };

  if (loading) {
    return (
      <div className="p-6">
        <div className="mb-8">
          <Skeleton className="h-8 w-32 mb-2" />
          <Skeleton className="h-5 w-80" />
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-36 rounded-xl" />
          ))}
        </div>
      </div>
    );
  }

  if (projects.length === 0) {
    return <Navigate to="/onboarding" replace />;
  }

  return (
    <div className="min-h-full">
      <div className="p-6">
        <div className="flex justify-between gap-6 flex-wrap items-center mb-8">
          <div>
            <h1 className="text-2xl font-semibold text-foreground mb-1">
              Projects
            </h1>
            <p className="text-muted-foreground">
              Organize your agent graphs, knowledge, and repositories by project
            </p>
          </div>
          <Button className="gap-2" onClick={handleOpenCreate}>
            <Plus className="w-4 h-4" />
            New Project
          </Button>
        </div>

        {projects.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <Folder className="w-12 h-12 text-muted-foreground/30 mb-4" />
            <p className="text-sm font-medium text-muted-foreground mb-4">
              No projects yet
            </p>
            <Button onClick={handleOpenCreate}>
              Create your first project
            </Button>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {projects.map((project) => (
              <ProjectCard
                key={project.id}
                name={project.name}
                icon={project.icon}
                color={project.color}
                description={project.description}
                graphCount={project.graphCount}
                threadCount={project.threadCount}
                updatedAt={project.updatedAt}
                onClick={() => handleOpenProject(project.id)}
                onEdit={() => handleOpenEdit(project)}
                onDelete={() => setDeleteConfirmId(project.id)}
                onSettings={() => setModelSettingsProject(project)}
              />
            ))}
          </div>
        )}
      </div>

      {/* Create / Edit Dialog */}
      <Dialog
        open={modalOpen}
        onOpenChange={(open) => !open && handleCloseModal()}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>
              {editingProject ? 'Edit Project' : 'New Project'}
            </DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>
                <span className="text-destructive">* </span>Name
              </Label>
              <Input
                value={formValues.name}
                onChange={(e) =>
                  setFormValues({ ...formValues, name: e.target.value })
                }
                placeholder="My Project"
              />
            </div>
            <div className="space-y-2">
              <Label>Description</Label>
              <Textarea
                value={formValues.description || ''}
                onChange={(e) =>
                  setFormValues({ ...formValues, description: e.target.value })
                }
                placeholder="Describe what this project is for"
                rows={3}
              />
            </div>
            <div className="space-y-2">
              <Label>Icon</Label>
              <Input
                value={formValues.icon || ''}
                onChange={(e) =>
                  setFormValues({ ...formValues, icon: e.target.value })
                }
                placeholder="🚀"
              />
              <p className="text-xs text-muted-foreground">
                Emoji or icon slug, e.g. 🚀 or robot
              </p>
            </div>
            <div className="space-y-2">
              <Label>Color</Label>
              <div className="flex flex-wrap gap-2">
                {DEFAULT_PROJECT_COLORS.map((color) => (
                  <button
                    key={color}
                    type="button"
                    className="w-8 h-8 rounded-lg border-2 transition-all"
                    style={{
                      backgroundColor: color,
                      borderColor: colorValue === color ? color : 'transparent',
                      boxShadow:
                        colorValue === color
                          ? `0 0 0 2px white, 0 0 0 4px ${color}`
                          : 'none',
                    }}
                    onClick={() => setColorValue(color)}
                  />
                ))}
              </div>
              <p className="text-xs text-muted-foreground">
                Accent color for this project
              </p>
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={handleCloseModal}>
              Cancel
            </Button>
            <Button
              onClick={handleSubmit}
              disabled={!formValues.name.trim() || saving}>
              {saving && <Loader2 className="w-4 h-4 animate-spin mr-1" />}
              Save
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Model Settings Dialog */}
      {modelSettingsProject && (
        <ProjectModelSettingsModal
          open={!!modelSettingsProject}
          onClose={() => setModelSettingsProject(null)}
          project={modelSettingsProject}
          onSaved={() => loadProjects()}
        />
      )}

      {/* Delete Confirmation Dialog */}
      <Dialog
        open={!!deleteConfirmId}
        onOpenChange={(open) => !open && setDeleteConfirmId(null)}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle>Delete project</DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground py-2">
            Are you sure you want to delete &quot;
            {projects.find((p) => p.id === deleteConfirmId)?.name ??
              'this project'}
            &quot;? All graphs, knowledge documents, and repositories inside it
            will also be deleted. This action cannot be undone.
          </p>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setDeleteConfirmId(null)}>
              Cancel
            </Button>
            <Button
              variant="destructive"
              onClick={handleDeleteConfirm}
              disabled={!!deletingId}>
              {deletingId && <Loader2 className="w-4 h-4 animate-spin mr-1" />}
              Delete
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};
