import {
  AnalyticsApi,
  Configuration,
  GitRepositoriesApi,
  GraphRevisionsApi,
  GraphsApi,
  KnowledgeApi,
  LitellmApi,
  ProjectsApi,
  RuntimesApi,
  TemplatesApi,
  ThreadsApi,
} from './autogenerated';
import { API_URL } from './config';

const configuration = new Configuration({
  basePath: API_URL,
});

export const graphsApi = new GraphsApi(configuration);
export const templatesApi = new TemplatesApi(configuration);
export const threadsApi = new ThreadsApi(configuration);
export const graphRevisionsApi = new GraphRevisionsApi(configuration);
export const litellmApi = new LitellmApi(configuration);
export const knowledgeApi = new KnowledgeApi(configuration);
export const gitRepositoriesApi = new GitRepositoriesApi(configuration);
export const analyticsApi = new AnalyticsApi(configuration);
export const runtimesApi = new RuntimesApi(configuration);
export const projectsApi = new ProjectsApi(configuration);
