import {
  Handle,
  NodeProps,
  Position,
  useReactFlow,
  useStore,
} from '@xyflow/react';
import {
  AlertCircle,
  BookOpen,
  ChevronDown,
  ChevronUp,
  Cpu,
  Play,
  Plug,
  Server,
  Trash2,
  Wrench,
  Zap,
} from 'lucide-react';
import type { CSSProperties } from 'react';
import React, { useCallback, useEffect, useMemo, useState } from 'react';

import { GraphDtoStatusEnum, TemplateDto } from '../../autogenerated';
import { useNodeDynamicCtx } from '../../pages/graphs/contexts/nodeContext';
import type {
  GraphEdge,
  GraphNode,
  GraphNodeData,
} from '../../pages/graphs/types';
import type { ConnectionRule } from '../../pages/graphs/utils/graphCanvasUtils';
import { makeHandleId } from '../../pages/graphs/utils/graphCanvasUtils';
import { GraphValidationService } from '../../services/GraphValidationService';
import { getAgentAvatarDataUri } from '../../utils/agentAvatars';
import { Avatar, AvatarFallback, AvatarImage } from './avatar';
import { Badge } from './badge';
import { Button } from './button';
import { Tooltip, TooltipContent, TooltipTrigger } from './tooltip';

// ── GraphNodeCard ─────────────────────────────────────────────────────────────

export interface GraphNodeCardProps {
  // Content
  label: string;
  templateKind?: string;
  template?: string;
  metadataProperties?: { key: string; value: string; title: string }[];
  description?: string;

  // State
  selected?: boolean;
  hasValidationErrors?: boolean;

  // Slots
  statusDot?: React.ReactNode;
  avatar?: React.ReactNode;
  /** Error icons, trash button, etc. — rendered at end of header row */
  actionsSlot?: React.ReactNode;
  /** Optional bottom row (e.g. trigger button) */
  footer?: React.ReactNode;

  // Handles columns — separate expanded/collapsed views
  inputsExpanded?: React.ReactNode;
  inputsCollapsed?: React.ReactNode;
  outputsExpanded?: React.ReactNode;
  outputsCollapsed?: React.ReactNode;

  defaultExpanded?: boolean;

  onClick?: React.MouseEventHandler<HTMLDivElement>;
}

export const GraphNodeCard: React.FC<GraphNodeCardProps> = ({
  label,
  templateKind,
  template,
  metadataProperties,
  description,
  selected = false,
  hasValidationErrors = false,
  statusDot,
  avatar,
  actionsSlot,
  footer,
  inputsExpanded,
  inputsCollapsed,
  outputsExpanded,
  outputsCollapsed,
  defaultExpanded = false,
  onClick,
}) => {
  const [expanded, setExpanded] = useState(defaultExpanded);

  const borderClass = hasValidationErrors
    ? 'ring-2 ring-destructive border-destructive'
    : selected
      ? 'ring-2 ring-primary border-primary'
      : 'border border-border';

  return (
    <div
      className={[
        'bg-card rounded-xl shadow-sm hover:shadow-md transition-all cursor-pointer',
        borderClass,
      ]
        .filter(Boolean)
        .join(' ')}
      onClick={onClick}>
      {/* ── Header ─────────────────────────────────────────────── */}
      <div className="p-4 border-b border-border/50">
        {/* Row 1: status dot + avatar + label + actions */}
        <div className="flex items-center gap-2 mb-1.5 min-w-0">
          {statusDot}
          {avatar}
          <span className="text-sm font-semibold truncate flex-1 min-w-0">
            {label}
          </span>
          {actionsSlot}
        </div>

        {/* Row 2: type badges */}
        {(templateKind || template) && (
          <div className="flex items-center gap-1.5 mb-2">
            {templateKind && (
              <Badge className="bg-primary hover:bg-primary text-primary-foreground text-[11px] px-2 py-0 h-5">
                {templateKind}
              </Badge>
            )}
            {template && (
              <Badge
                variant="outline"
                className="text-[11px] border-primary/50 text-primary px-2 py-0 h-5">
                {template}
              </Badge>
            )}
          </div>
        )}

        {/* Row 3: metadata chips */}
        {metadataProperties && metadataProperties.length > 0 && (
          <div className="flex gap-1.5 mb-2 flex-wrap">
            {metadataProperties.map(({ key, value, title }) => (
              <span
                key={key}
                className="text-[11px] bg-muted text-muted-foreground px-2 py-0.5 rounded">
                {title}: {value}
              </span>
            ))}
          </div>
        )}

        {/* Description */}
        {description && (
          <p className="text-xs text-muted-foreground leading-relaxed">
            {description}
          </p>
        )}
      </div>

      {/* ── Chevron toggle ─────────────────────────────────────── */}
      <div className="relative h-0 flex justify-center z-10">
        <button
          className="nodrag absolute -top-[9px] w-[18px] h-[18px] rounded-full bg-card border border-border/60 flex items-center justify-center text-muted-foreground hover:text-foreground hover:border-border transition-colors"
          onPointerDown={(e) => {
            e.preventDefault();
            e.stopPropagation();
          }}
          onClick={(e) => {
            e.stopPropagation();
            setExpanded((v) => !v);
          }}>
          {expanded ? (
            <ChevronUp className="w-2.5 h-2.5" />
          ) : (
            <ChevronDown className="w-2.5 h-2.5" />
          )}
        </button>
      </div>

      {/* ── Handles area ───────────────────────────────────────── */}
      <div className="flex gap-4 px-3 pt-3 pb-2.5">
        <div className="flex-1">
          {expanded ? inputsExpanded : inputsCollapsed}
        </div>
        <div className="flex-1 flex flex-col items-end">
          {expanded ? outputsExpanded : outputsCollapsed}
        </div>
      </div>

      {/* ── Footer (e.g. trigger button) ───────────────────────── */}
      {footer && (
        <div className="flex justify-center px-3 py-2.5 border-t border-border/50">
          {footer}
        </div>
      )}
    </div>
  );
};

// ── CustomNode (React Flow canvas node) ──────────────────────────────────────

const ensureNodeStatusPulseStyle = (() => {
  let injected = false;
  return () => {
    if (injected || typeof document === 'undefined') {
      return;
    }
    if (document.getElementById('graph-node-status-pulse-style')) {
      injected = true;
      return;
    }
    const styleEl = document.createElement('style');
    styleEl.id = 'graph-node-status-pulse-style';
    styleEl.textContent = `
      @keyframes graph-node-status-pulse {
        0% { box-shadow: 0 0 0 0 rgba(82, 196, 26, 0.6); }
        70% { box-shadow: 0 0 0 8px rgba(82, 196, 26, 0); }
        100% { box-shadow: 0 0 0 0 rgba(82, 196, 26, 0); }
      }
    `;
    document.head.appendChild(styleEl);
    injected = true;
  };
})();

const slug = (v: string | number | undefined | null): string =>
  String(v ?? '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '-');

type HandleHighlight = 'allowed' | 'blocked' | 'none';

interface CustomNodeProps extends NodeProps {
  templates?: TemplateDto[];
  graphStatus?: GraphDtoStatusEnum;
  onTriggerClick?: (nodeId: string) => void;
}

export const CustomNode = React.memo(
  ({
    id: nodeId,
    data,
    selected,
    templates = [],
    isConnectable = true,
    graphStatus,
    onTriggerClick,
  }: CustomNodeProps) => {
    // Read frequently-changing data from context instead of props so that
    // nodeTypes in GraphCanvas stays stable and doesn't remount all nodes.
    const {
      compiledNodes,
      compiledNodesLoading,
      connectionPreview,
      onNodeDelete: ctxOnNodeDelete,
    } = useNodeDynamicCtx();
    const compiledNode = compiledNodes?.[nodeId];
    const nodeData = data as unknown as GraphNodeData;

    // Subscribe to edges connected to this node only.  Custom equality avoids
    // re-renders when unrelated edges change or when only positions update.
    const connectedEdges = useStore(
      useCallback(
        (s) =>
          (s.edges as GraphEdge[]).filter(
            (e) => e.source === nodeId || e.target === nodeId,
          ),
        [nodeId],
      ),
      // Shallow-compare the filtered list: same length + same ids/handles.
      useCallback((a: GraphEdge[], b: GraphEdge[]) => {
        if (a.length !== b.length) return false;
        for (let i = 0; i < a.length; i++) {
          if (
            a[i].id !== b[i].id ||
            a[i].source !== b[i].source ||
            a[i].target !== b[i].target ||
            a[i].sourceHandle !== b[i].sourceHandle ||
            a[i].targetHandle !== b[i].targetHandle
          )
            return false;
        }
        return true;
      }, []),
    );

    // For validation we need all nodes (to look up connected peers) but only
    // care about topology (id, type, data), NOT positions.  Build a stable
    // fingerprint so dragging doesn't cause re-renders.
    const allNodes = useStore(
      useCallback((s) => s.nodes as GraphNode[], []),
      useCallback((a: GraphNode[], b: GraphNode[]) => {
        if (a.length !== b.length) return false;
        for (let i = 0; i < a.length; i++) {
          if (a[i].id !== b[i].id || a[i].data !== b[i].data) return false;
        }
        return true;
      }, []),
    );

    const { setNodes: setReactFlowNodes, setEdges: setReactFlowEdges } =
      useReactFlow();
    const nodeTemplate = templates?.find((t) => t.id === nodeData.template);

    useEffect(() => {
      ensureNodeStatusPulseStyle();
    }, []);

    const metadataProperties = useMemo(() => {
      if (!nodeData.templateSchema?.properties)
        return [] as { key: string; value: unknown; title: string }[];
      return Object.entries(nodeData.templateSchema.properties)
        .filter(([, prop]) => prop['x-ui:show-on-node'] === true)
        .map(([key, prop]) => ({
          key,
          value: nodeData.config[key] ?? prop.const ?? prop.default ?? '',
          title: prop['x-ui:label'] ?? prop.title ?? key,
        }))
        .filter(
          (x) => x.value !== undefined && x.value !== null && x.value !== '',
        );
    }, [nodeData.templateSchema?.properties, nodeData.config]);

    const validationErrors = useMemo(
      () =>
        templates.length > 0 && allNodes.length > 0
          ? GraphValidationService.getNodeValidationErrors(
              nodeId,
              allNodes,
              connectedEdges,
              templates,
            )
          : [],
      [connectedEdges, allNodes, nodeId, templates],
    );
    const inputRules = useMemo(
      () =>
        templates.length > 0 && nodeId
          ? GraphValidationService.getAvailableConnectionTypes(
              {
                id: nodeId,
                data: nodeData as unknown as Record<string, unknown>,
                position: { x: 0, y: 0 },
                type: 'custom',
              } satisfies GraphNode,
              templates,
            )
          : [],
      [nodeData, nodeId, templates],
    );

    const hasValidationErrors = validationErrors.length > 0;

    const outMissing =
      inputRules.some((r) => r.required) &&
      !connectedEdges.some((e) => e.source === nodeId);

    // Check if this is a trigger node and if graph is running
    const isTriggerNode = nodeTemplate?.kind === 'trigger';
    const isGraphRunning = graphStatus === GraphDtoStatusEnum.Running;
    const isGraphCompiling = graphStatus === GraphDtoStatusEnum.Compiling;
    const isGraphActive = isGraphRunning || isGraphCompiling;
    const canTrigger = isTriggerNode && isGraphRunning;
    const color = (
      role: 'target' | 'source',
      _required: boolean,
      missing: boolean,
    ) => {
      if (missing) {
        return {
          bg: '#ff4d4f',
          br: '2px solid white',
          sh: '0 0 0 1px rgba(255,77,79,0.5)',
        };
      }
      if (role === 'source') {
        return {
          bg: '#52c41a',
          br: '2px solid white',
          sh: '0 0 0 1px rgba(82,196,26,0.5)',
        };
      }
      return {
        bg: '#1890ff',
        br: '2px solid white',
        sh: '0 0 0 1px rgba(24,144,255,0.5)',
      };
    };

    const matchesRuleForTemplate = (
      rule: Pick<ConnectionRule, 'type' | 'value'> | undefined,
      template?: TemplateDto,
    ) => {
      if (!rule || !template) {
        return false;
      }
      if (rule.type === 'kind') {
        return slug(rule.value) === slug(template.kind);
      }
      if (rule.type === 'template') {
        return String(template.id) === String(rule.value);
      }
      return false;
    };

    const getHandleHighlight = (
      role: 'target' | 'source',
      rule: ConnectionRule,
    ): HandleHighlight => {
      if (!connectionPreview?.template || !nodeTemplate) {
        return 'none';
      }

      if (role === 'target' && connectionPreview.fromHandleType === 'source') {
        const inputAllowsSource = matchesRuleForTemplate(
          rule,
          connectionPreview.template,
        );
        const outputAllowsTarget = connectionPreview.rule
          ? matchesRuleForTemplate(connectionPreview.rule, nodeTemplate)
          : true;
        if (!inputAllowsSource || !outputAllowsTarget) {
          return 'blocked';
        }
        return 'allowed';
      }

      if (role === 'source' && connectionPreview.fromHandleType === 'target') {
        const outputAllowsTarget = matchesRuleForTemplate(
          rule,
          connectionPreview.template,
        );
        const inputAllowsSource = connectionPreview.rule
          ? matchesRuleForTemplate(connectionPreview.rule, nodeTemplate)
          : true;
        if (!outputAllowsTarget || !inputAllowsSource) {
          return 'blocked';
        }
        return 'allowed';
      }

      return 'none';
    };

    const resolveHandleVisuals = (
      base: { bg: string; br: string; sh: string },
      missing: boolean,
      highlight: HandleHighlight,
    ) => {
      const isAllowed = highlight === 'allowed';
      const isBlocked = highlight === 'blocked';

      const background = isBlocked
        ? '#bfbfbf'
        : isAllowed
          ? '#52c41a'
          : missing
            ? '#ff5d5d'
            : base.bg;

      const boxShadow = isBlocked
        ? '0 0 0 1px rgba(191,191,191,0.8)'
        : isAllowed
          ? '0 0 0 1px rgba(82,196,26,0.6)'
          : base.sh;

      return {
        background,
        border: base.br,
        boxShadow,
        textColor: isBlocked || isAllowed || missing ? '#ffffff' : undefined,
      };
    };

    const statusDotColorMap: Record<string, string> = {
      running: '#52c41a',
      idle: '#1890ff',
      starting: '#2f54eb',
      stopped: '#ff4d4f',
    };

    const templateKind = nodeTemplate?.kind ?? nodeData.templateKind;
    const templateKindLower = (templateKind || '').toLowerCase();
    const isAgentNode = templateKindLower === 'simpleagent';
    const showNodeStatus = ['runtime', 'mcp', 'trigger'].includes(
      templateKindLower,
    );

    const formattedStatus = compiledNode?.status
      ? `${compiledNode.status.charAt(0).toUpperCase()}${compiledNode.status.slice(1)}`
      : isGraphCompiling
        ? 'Compiling'
        : 'Unknown';

    const statusTooltip = !isGraphActive
      ? 'Not running'
      : compiledNodesLoading
        ? 'Loading status...'
        : formattedStatus;

    const statusDotColor = !isGraphActive
      ? '#d9d9d9'
      : compiledNodesLoading
        ? '#1890ff'
        : compiledNode?.status
          ? (statusDotColorMap[compiledNode.status] ?? '#d9d9d9')
          : '#d9d9d9';

    const isStatusRunning =
      isGraphActive &&
      !compiledNodesLoading &&
      compiledNode?.status === 'running';

    const statusDotStyle: CSSProperties = {
      width: 8,
      height: 8,
      borderRadius: '50%',
      backgroundColor: statusDotColor,
      display: 'inline-block',
      cursor: 'help',
      boxShadow: isStatusRunning ? '0 0 0 0 rgba(82, 196, 26, 0.6)' : 'none',
      animation: isStatusRunning
        ? 'graph-node-status-pulse 1.5s ease-out infinite'
        : undefined,
    };

    const statusDot = showNodeStatus ? (
      <Tooltip>
        <TooltipTrigger asChild>
          <span style={statusDotStyle} />
        </TooltipTrigger>
        <TooltipContent side="top">{statusTooltip}</TooltipContent>
      </Tooltip>
    ) : null;

    const agentAvatar = isAgentNode ? (
      <Avatar className="size-6 shrink-0">
        <AvatarImage src={getAgentAvatarDataUri(nodeId, 48)} />
        <AvatarFallback className="text-[9px]">AG</AvatarFallback>
      </Avatar>
    ) : null;

    // ── Slots for GraphNodeCard ──────────────────────────────────────────────

    const actionsSlot = (
      <>
        {compiledNode?.error && (
          <Tooltip>
            <TooltipTrigger asChild>
              <AlertCircle className="size-3.5 shrink-0 text-destructive" />
            </TooltipTrigger>
            <TooltipContent side="top">{compiledNode.error}</TooltipContent>
          </Tooltip>
        )}
        {hasValidationErrors && (
          <Tooltip>
            <TooltipTrigger asChild>
              <AlertCircle className="size-3.5 shrink-0 text-destructive cursor-help" />
            </TooltipTrigger>
            <TooltipContent side="top">
              <div>
                <div className="font-bold mb-1">Validation Errors:</div>
                {validationErrors.map((e, i) => (
                  <div key={i} className="text-xs">
                    {'\u2022'} {e.message}
                  </div>
                ))}
              </div>
            </TooltipContent>
          </Tooltip>
        )}
        {ctxOnNodeDelete && (
          <button
            className="nodrag text-muted-foreground/40 hover:text-destructive transition-colors flex-shrink-0"
            onPointerDown={(e) => {
              e.preventDefault();
              e.stopPropagation();
              setReactFlowEdges((edges) =>
                edges.filter(
                  (edge) => edge.source !== nodeId && edge.target !== nodeId,
                ),
              );
              setReactFlowNodes((nodes) =>
                nodes.filter((node) => node.id !== nodeId),
              );
              ctxOnNodeDelete(nodeId);
            }}>
            <Trash2 className="size-3.5" />
          </button>
        )}
      </>
    );

    const kindIconMap: Record<string, React.ReactNode> = {
      tool: <Wrench className="w-3 h-3" />,
      runtime: <Server className="w-3 h-3" />,
      mcp: <Plug className="w-3 h-3" />,
      trigger: <Zap className="w-3 h-3" />,
      knowledge: <BookOpen className="w-3 h-3" />,
      resource: <Cpu className="w-3 h-3" />,
    };

    const avatar = agentAvatar ?? (
      <div className="w-6 h-6 rounded-full bg-primary/15 flex items-center justify-center flex-shrink-0 text-primary">
        {kindIconMap[templateKindLower] ?? <Play className="w-3 h-3" />}
      </div>
    );

    // ── Inputs ───────────────────────────────────────────────────────────────

    const inputsExpanded = (
      <div className="flex flex-col gap-1.5">
        {inputRules.map((t) => {
          const id = makeHandleId('target', t);
          const miss = Boolean(
            t.required &&
            !connectedEdges.some(
              (e) => e.target === nodeId && e.targetHandle === id,
            ),
          );
          const c = color('target', t.required, miss);
          const highlight = getHandleHighlight('target', t);
          const visuals = resolveHandleVisuals(c, miss, highlight);
          const isDefault = highlight === 'none' && !miss && c.bg === '#1890ff';
          return (
            <div
              key={id}
              className="relative flex items-center"
              style={{ minHeight: 18 }}>
              <Handle
                type="target"
                id={id}
                isConnectable={isConnectable ?? true}
                position={Position.Left}
                style={{
                  width: '12px',
                  height: '12px',
                  position: 'absolute',
                  left: '-18px',
                  background: visuals.background,
                  border: visuals.border,
                  boxShadow: visuals.boxShadow,
                }}
              />
              <div
                className="w-full px-2 py-1 rounded"
                style={{
                  background: isDefault
                    ? 'rgba(107,143,212,0.12)'
                    : `${visuals.background}20`,
                  minHeight: 28,
                }}>
                <div
                  className="text-[10px] font-semibold leading-tight truncate"
                  style={{
                    color: isDefault ? '#4a6fa8' : visuals.background,
                  }}>
                  {t.value}
                </div>
                {(t.required || t.multiple) && (
                  <div
                    className="text-[10px] leading-tight"
                    style={{
                      color: isDefault ? '#4a6fa8' : visuals.background,
                      opacity: 0.6,
                    }}>
                    {[t.required && 'required', t.multiple && 'multiple']
                      .filter(Boolean)
                      .join(' · ')}
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    );

    const inputsCollapsed =
      inputRules.length > 0 ? (
        <div className="relative" style={{ minHeight: 28 }}>
          {inputRules.map((t) => {
            const id = makeHandleId('target', t);
            const miss = Boolean(
              t.required &&
              !connectedEdges.some(
                (e) => e.target === nodeId && e.targetHandle === id,
              ),
            );
            const c = color('target', t.required, miss);
            const highlight = getHandleHighlight('target', t);
            const visuals = resolveHandleVisuals(c, miss, highlight);
            return (
              <Handle
                key={id}
                type="target"
                id={id}
                isConnectable={isConnectable ?? true}
                position={Position.Left}
                style={{
                  width: '12px',
                  height: '12px',
                  position: 'absolute',
                  left: '-18px',
                  top: '50%',
                  transform: 'translateY(-50%)',
                  background: visuals.background,
                  border: visuals.border,
                  boxShadow: visuals.boxShadow,
                }}
              />
            );
          })}
          <div className="bg-[#6b8fd4]/12 px-2 py-1 rounded">
            <div className="text-[10px] font-semibold text-[#4a6fa8] leading-tight">
              inputs
            </div>
            <div className="text-[10px] text-[#4a6fa8]/60 leading-tight">
              {inputRules.length} connections
            </div>
          </div>
        </div>
      ) : null;

    // ── Outputs ──────────────────────────────────────────────────────────────

    const outputsExpanded = (
      <div className="flex flex-col gap-1.5 items-end w-full">
        {nodeTemplate?.outputs?.map((output) => {
          const outRule: {
            type: 'kind' | 'template';
            value: string;
            required?: boolean;
            multiple?: boolean;
          } = {
            type: output.type as 'kind' | 'template',
            value: String(output.value),
            required: output.required,
            multiple: output.multiple,
          };
          const id = makeHandleId('source', outRule);
          const miss = Boolean(
            output.required &&
            !connectedEdges.some(
              (e) => e.source === nodeId && e.sourceHandle === id,
            ),
          );
          const c = color('source', output.required || false, miss);
          const highlight = getHandleHighlight('source', outRule);
          const visuals = resolveHandleVisuals(c, miss, highlight);
          const isDefault = highlight === 'none' && !miss && c.bg === '#52c41a';
          return (
            <div
              key={id}
              className="relative flex items-center justify-end w-full"
              style={{ minHeight: 18 }}>
              <div
                className="w-full px-2 py-1 rounded text-right"
                style={{
                  background: isDefault
                    ? 'rgba(90,158,113,0.12)'
                    : `${visuals.background}20`,
                  minHeight: 28,
                }}>
                <div
                  className="text-[10px] font-semibold leading-tight truncate"
                  style={{
                    color: isDefault ? '#3d7a52' : visuals.background,
                  }}>
                  {output.value}
                </div>
                {(output.required || output.multiple) && (
                  <div
                    className="text-[10px] leading-tight"
                    style={{
                      color: isDefault ? '#3d7a52' : visuals.background,
                      opacity: 0.6,
                    }}>
                    {[
                      output.required && 'required',
                      output.multiple && 'multiple',
                    ]
                      .filter(Boolean)
                      .join(' · ')}
                  </div>
                )}
              </div>
              <Handle
                type="source"
                id={id}
                isConnectable={isConnectable ?? true}
                position={Position.Right}
                style={{
                  background: visuals.background,
                  border: visuals.border,
                  boxShadow: visuals.boxShadow,
                  width: '12px',
                  height: '12px',
                  position: 'absolute',
                  right: '-18px',
                }}
              />
            </div>
          );
        })}
        {nodeTemplate?.outputs === undefined && (
          <div
            className="relative flex items-center justify-end"
            style={{ minHeight: 18 }}>
            <span className="text-[10px] text-muted-foreground mr-2 whitespace-nowrap">
              output
            </span>
            <Handle
              type="source"
              id="source-out"
              isConnectable={isConnectable ?? true}
              position={Position.Right}
              style={{
                background: color('source', false, outMissing).bg,
                border: color('source', false, outMissing).br,
                boxShadow: color('source', false, outMissing).sh,
                width: '12px',
                height: '12px',
                position: 'absolute',
                right: '-18px',
              }}
            />
          </div>
        )}
      </div>
    );

    const outputsCollapsed = nodeTemplate?.outputs ? (
      nodeTemplate.outputs.length > 0 ? (
        <div className="relative w-full" style={{ minHeight: 28 }}>
          {nodeTemplate.outputs.map((output) => {
            const outRule: {
              type: 'kind' | 'template';
              value: string;
              required?: boolean;
              multiple?: boolean;
            } = {
              type: output.type as 'kind' | 'template',
              value: String(output.value),
              required: output.required,
              multiple: output.multiple,
            };
            const id = makeHandleId('source', outRule);
            const miss = Boolean(
              output.required &&
              !connectedEdges.some(
                (e) => e.source === nodeId && e.sourceHandle === id,
              ),
            );
            const c = color('source', output.required || false, miss);
            const highlight = getHandleHighlight('source', outRule);
            const visuals = resolveHandleVisuals(c, miss, highlight);
            return (
              <Handle
                key={id}
                type="source"
                id={id}
                isConnectable={isConnectable ?? true}
                position={Position.Right}
                style={{
                  width: '12px',
                  height: '12px',
                  position: 'absolute',
                  right: '-18px',
                  top: '50%',
                  transform: 'translateY(-50%)',
                  background: visuals.background,
                  border: visuals.border,
                  boxShadow: visuals.boxShadow,
                }}
              />
            );
          })}
          <div className="bg-[#5a9e71]/12 px-2 py-1 rounded text-right">
            <div className="text-[10px] font-semibold text-[#3d7a52] leading-tight">
              outputs
            </div>
            <div className="text-[10px] text-[#3d7a52]/60 leading-tight">
              {nodeTemplate.outputs.length} connections
            </div>
          </div>
        </div>
      ) : null
    ) : (
      <div
        className="relative flex items-center justify-end"
        style={{ minHeight: 18 }}>
        <span className="text-[10px] text-muted-foreground mr-2 whitespace-nowrap">
          output
        </span>
        <Handle
          type="source"
          id="source-out"
          isConnectable={isConnectable ?? true}
          position={Position.Right}
          style={{
            background: color('source', false, outMissing).bg,
            border: color('source', false, outMissing).br,
            boxShadow: color('source', false, outMissing).sh,
            width: '12px',
            height: '12px',
            position: 'absolute',
            right: '-18px',
          }}
        />
      </div>
    );

    return (
      <div style={{ minWidth: 300, position: 'relative', zIndex: 1 }}>
        <GraphNodeCard
          label={nodeData.label}
          templateKind={templateKind}
          template={nodeData.template}
          metadataProperties={metadataProperties.map((p) => ({
            ...p,
            value: String(p.value),
          }))}
          description={nodeTemplate?.description}
          selected={selected}
          hasValidationErrors={hasValidationErrors}
          statusDot={statusDot}
          avatar={avatar}
          actionsSlot={actionsSlot}
          inputsExpanded={inputsExpanded}
          inputsCollapsed={inputsCollapsed}
          outputsExpanded={outputsExpanded}
          outputsCollapsed={outputsCollapsed}
          footer={
            isTriggerNode ? (
              <Button
                size="sm"
                disabled={!canTrigger}
                onClick={() => onTriggerClick?.(nodeId)}
                className="text-[11px] px-5">
                <Play className="size-3.5" />
                Trigger
              </Button>
            ) : undefined
          }
        />
      </div>
    );
  },
  (prevProps, nextProps) => {
    // compiledNodes, compiledNodesLoading, and connectionPreview are
    // delivered via NodeDynamicCtx (context), so they bypass React.memo.
    // We only compare the remaining props here.
    const prevData = prevProps.data as unknown as GraphNodeData;
    const nextData = nextProps.data as unknown as GraphNodeData;

    const configChanged =
      JSON.stringify(prevData?.config) !== JSON.stringify(nextData?.config);

    return (
      prevProps.id === nextProps.id &&
      prevProps.selected === nextProps.selected &&
      prevData?.label === nextData?.label &&
      prevData?.template === nextData?.template &&
      prevProps.graphStatus === nextProps.graphStatus &&
      prevProps.templates?.length === nextProps.templates?.length &&
      !configChanged
    );
  },
);

CustomNode.displayName = 'CustomNode';
